schema: DVSYS
name: IS_SECURE_APPLICATION_ROLE
routineType: FUNCTION
returnParamater:
  name: (--return--)
  dataType: PL/SQL BOOLEAN
  parameterMode: OUT
  ordinalPosition: 0
parameters:
- name: P_ROLE
  dataType: VARCHAR2
  parameterMode: IN
  ordinalPosition: 1
routineDefinition: |-
  FUNCTION is_secure_application_role(p_role VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN dvsys.dbms_macsec.is_secure_application_role(p_role = > p_role);
  END;
