schema: SYS
name: ALL_MINING_MODEL_SETTINGS
updatedAllowed: true
insertAllowed: true
viewDefinition: |-
  select
    u.name,
    o.name,
    s.name,
    s.value,
    decode(s.properties, 1, 'INPUT', 'DEFAULT')
  from
    sys.modelset$ s,
    sys.obj$ o,
    sys.user$ u
  where
    s.mod# = o.obj#
    and o.owner# = u.user#
    and (
      o.owner# = userenv('SCHEMAID')
      or o.obj# in (
        select
          oa.obj#
        from
          sys.objauth$ oa
        where
          oa.grantee# in (
            select
              kzsrorol
            from
              x$kzsro
          )
      )
      or
      /* user has system privileges */
      exists (
        select
          null
        from
          v$enabledprivs
        where
          priv_number in (
            -293
            /* SELECT ANY MINING MODEL */
          )
      )
    )
    and bitand(s.properties, 2) != 2
columns: []
referencedTables: []
