schema: SYS
name: USER_PLSQL_OBJECT_SETTINGS
updatedAllowed: true
insertAllowed: true
columns:
- name: NAME
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 128
- name: NLS_LENGTH_SEMANTICS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 4000
- name: ORIGIN_CON_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 10
  dataTypeLength:
- name: PLSCOPE_SETTINGS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 4000
- name: PLSQL_CCFLAGS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 4000
- name: PLSQL_CODE_TYPE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 4
  dataTypeLength: 4000
- name: PLSQL_DEBUG
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 5
  dataTypeLength: 4000
- name: PLSQL_OPTIMIZE_LEVEL
  dataType: NUMBER
  nullable: true
  ordinalPosition: 3
  dataTypeLength:
- name: PLSQL_WARNINGS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 4000
- name: TYPE
  dataType: VARCHAR2
  textMaxLength: 12
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 12
referencedTables:
- schema: SYS
  name: INT$DBA_PLSQL_OBJECT_SETTINGS
viewDefinition: |-
  select
    NAME,
    TYPE,
    PLSQL_OPTIMIZE_LEVEL,
    PLSQL_CODE_TYPE,
    PLSQL_DEBUG,
    PLSQL_WARNINGS,
    NLS_LENGTH_SEMANTICS,
    PLSQL_CCFLAGS,
    PLSCOPE_SETTINGS,
    ORIGIN_CON_ID
  from
    NO_ROOT_SW_FOR_LOCAL(INT $DBA_PLSQL_OBJECT_SETTINGS)
  where
    OWNER = SYS_CONTEXT('USERENV', 'CURRENT_USER')
