schema: SYS
name: USER_APPLICATION_ROLES
updatedAllowed: true
insertAllowed: true
columns:
- name: PACKAGE
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 3
  dataTypeLength: 128
- name: ROLE
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 128
- name: SCHEMA
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 2
  dataTypeLength: 128
referencedTables:
- schema: SYS
  name: APPROLE$
- schema: SYS
  name: USER$
viewDefinition: |-
  select
    u.name,
    schema,
    package
  from
    user $ u,
    approle$ a
  where
    u.user# = a .role#
    and u.user# = uid
