schema: SYS
name: USER_STORED_SETTINGS
updatedAllowed: true
insertAllowed: true
columns:
- name: OBJECT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 2
  dataTypeLength:
- name: OBJECT_NAME
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 128
- name: OBJECT_TYPE
  dataType: VARCHAR2
  textMaxLength: 12
  nullable: true
  ordinalPosition: 3
  dataTypeLength: 12
- name: ORIGIN_CON_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 6
  dataTypeLength:
- name: PARAM_NAME
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 128
- name: PARAM_VALUE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 5
  dataTypeLength: 4000
referencedTables:
- schema: SYS
  name: INT$DBA_STORED_SETTINGS
viewDefinition: |-
  SELECT
    object_name,
    object_id,
    object_type,
    param_name,
    param_value,
    origin_con_id
  from
    NO_ROOT_SW_FOR_LOCAL(int $dba_stored_settings)
  where
    OWNER = SYS_CONTEXT('USERENV', 'CURRENT_USER')
