schema: SYS
name: USER_WARNING_SETTINGS
updatedAllowed: true
insertAllowed: true
columns:
- name: OBJECT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 2
  dataTypeLength:
- name: OBJECT_NAME
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 128
- name: OBJECT_TYPE
  dataType: VARCHAR2
  textMaxLength: 12
  nullable: true
  ordinalPosition: 3
  dataTypeLength: 12
- name: SETTING
  dataType: VARCHAR2
  textMaxLength: 7
  nullable: true
  ordinalPosition: 5
  dataTypeLength: 7
- name: WARNING
  dataType: VARCHAR2
  textMaxLength: 40
  nullable: true
  ordinalPosition: 4
  dataTypeLength: 40
referencedTables:
- schema: SYS
  name: _CURRENT_EDITION_OBJ
viewDefinition: |-
  SELECT
    o.name,
    o.obj#,
    DECODE(
      o.type#,
      7,
      'PROCEDURE',
      8,
      'FUNCTION',
      9,
      'PACKAGE',
      11,
      'PACKAGE BODY',
      12,
      'TRIGGER',
      13,
      'TYPE',
      14,
      'TYPE BODY',
      'UNDEFINED'
    ),
    DECODE(
      w.warning,
      -1,
      'INFORMATIONAL',
      -2,
      'PERFORMANCE',
      -3,
      'SEVERE',
      -4,
      'ALL',
      w.warning
    ),
    DECODE(
      w.setting,
      0,
      'DISABLE',
      1,
      'ENABLE',
      2,
      'ERROR',
      'INVALID'
    )
  FROM
    sys. "_CURRENT_EDITION_OBJ" o,
    TABLE(
      dbms_warning_internal.show_warning_settings(o.obj#)
    ) w
  WHERE
    o.linkname IS NULL
    AND o.obj# = w.obj_no
    AND o.type# IN (7, 8, 9, 11, 12, 13, 14)
    AND o.owner# = userenv('SCHEMAID')
