schema: CTXSYS
name: CTX_USER_PREFERENCE_VALUES
updatedAllowed: true
insertAllowed: true
viewDefinition: |-
  select
    /*+ ORDERED INDEX(dr$preference_value) */
    pre_name prv_preference,
    oat_name prv_attribute,
    decode(
      oat_datatype,
      'B',
      decode(prv_value, 1, 'YES', 'NO'),
      nvl(oal_label, prv_value)
    ) prv_value
  from
    dr$preference,
    dr$preference_value,
    dr$object_attribute,
    dr$object_attribute_lov
  where
    oat_id = oal_oat_id (+)
    and prv_value = nvl(oal_value, prv_value)
    and pre_id = prv_pre_id
    and oat_id = prv_oat_id
    and pre_owner# = userenv('SCHEMAID')
columns: []
referencedTables: []
