schema: APEX_050000
name: APEX_APPLICATION_PAGE_GROUPS
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: GROUP_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 7
  dataTypeLength:
- name: PAGE_GROUP_DESCRIPTION
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 4000
- name: PAGE_GROUP_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PAGE_GROUPS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    g.flow_id application_id,
    f.name application_name,
    g.group_name page_group_name,
    g.group_desc page_group_description,
    g.id group_id
  from
    wwv_flow_page_groups g,
    wwv_flows f,
    wwv_flow_company_schemas s,
    wwv_flow_companies w,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = g.security_group_id
    and f.id = g.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
