schema: APEX_050000
name: APEX_APPLICATION_TRANS_MAP
updatedAllowed: true
insertAllowed: true
columns:
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 14
  dataTypeLength:
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 12
  dataTypeLength:
- name: MAP_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: PRIMARY_APPLICATION_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 4
  dataTypeLength:
- name: PRIMARY_APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: TRANSLATED_APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: TRANSLATED_APPL_IMG_DIR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: TRANSLATED_APP_LANGUAGE
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: false
  ordinalPosition: 7
  dataTypeLength: 30
- name: TRANSLATION_COMMENTS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 4000
- name: TRANSLATION_MAP_COMMENTS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOW_AUTHORIZED
- schema: APEX_050000
  name: WWV_FLOW_LANGUAGE_MAP
viewDefinition: |-
  select
    f.workspace workspace,
    f.workspace_display_name,
    m.ID map_id,
    m.primary_language_flow_id primary_application_id,
    f.application_name primary_application_name,
    m.translation_flow_id translated_application_id,
    m.translation_flow_language_code translated_app_language,
    m.translation_image_directory translated_appl_img_dir,
    m.translation_comments translation_comments,
    m.map_comments translation_map_comments,
    m.last_updated_by,
    m.last_updated_on,
    m.created_by,
    m.created_on
  from
    wwv_flow_authorized f,
    wwv_flow_language_map m
  where
    m.primary_language_flow_id = f.application_id
