schema: APEX_050000
name: APEX_APPLICATION_PAGE_BUTTONS
updatedAllowed: true
insertAllowed: true
columns:
- name: ALIGNMENT
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 30
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: AUTHORIZATION_SCHEME
  dataType: VARCHAR2
  textMaxLength: 259
  nullable: true
  ordinalPosition: 41
  dataTypeLength: 259
- name: AUTHORIZATION_SCHEME_ID
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 42
  dataTypeLength: 255
- name: BUILD_OPTION
  dataType: VARCHAR2
  textMaxLength: 261
  nullable: true
  ordinalPosition: 40
  dataTypeLength: 261
- name: BUTTON_ACTION
  dataType: VARCHAR2
  textMaxLength: 36
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 36
- name: BUTTON_ACTION_CODE
  dataType: VARCHAR2
  textMaxLength: 13
  nullable: false
  ordinalPosition: 28
  dataTypeLength: 13
- name: BUTTON_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 2000
  nullable: true
  ordinalPosition: 38
  dataTypeLength: 2000
- name: BUTTON_CSS_CLASSES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 255
- name: BUTTON_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 47
  dataTypeLength:
- name: BUTTON_IS_HOT
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 3
- name: BUTTON_NAME
  dataType: VARCHAR2
  textMaxLength: 2000
  nullable: false
  ordinalPosition: 10
  dataTypeLength: 2000
- name: BUTTON_POSITION
  dataType: VARCHAR2
  textMaxLength: 18
  nullable: true
  ordinalPosition: 46
  dataTypeLength: 18
- name: BUTTON_SEQUENCE
  dataType: NUMBER
  nullable: false
  ordinalPosition: 7
  dataTypeLength:
- name: BUTTON_STATIC_ID
  dataType: VARCHAR2
  textMaxLength: 2000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 2000
- name: BUTTON_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 255
- name: BUTTON_TEMPLATE_ID
  dataType: VARCHAR2
  textMaxLength: 40
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 40
- name: BUTTON_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 255
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 48
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION1
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION2
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 4000
- name: CONDITION_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 255
- name: CONDITION_TYPE_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 255
- name: DATABASE_ACTION
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 39
  dataTypeLength: 30
- name: DISPLAY_POSITION
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 30
- name: EXECUTE_VALIDATIONS
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 3
- name: GRID_COLUMN
  dataType: NUMBER
  nullable: true
  ordinalPosition: 22
  dataTypeLength:
- name: GRID_COLUMN_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: GRID_COLUMN_CSS_CLASSES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 255
- name: GRID_COLUMN_SPAN
  dataType: NUMBER
  nullable: true
  ordinalPosition: 23
  dataTypeLength:
- name: ICON_CSS_CLASSES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 255
- name: IMAGE_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 10
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 10
- name: IMAGE_NAME
  dataType: VARCHAR2
  textMaxLength: 10
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 10
- name: LABEL
  dataType: VARCHAR2
  textMaxLength: 2000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 2000
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 44
  dataTypeLength:
- name: NEW_GRID
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 3
- name: NEW_GRID_COLUMN
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 3
- name: NEW_GRID_ROW
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 3
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 5
  dataTypeLength:
- name: PAGE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 6
  dataTypeLength: 255
- name: POST_ELEMENT_TEXT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 50
  dataTypeLength: 4000
- name: PRE_ELEMENT_TEXT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 49
  dataTypeLength: 4000
- name: REDIRECT_URL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 4000
- name: REGION
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: REGION_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 9
  dataTypeLength:
- name: REQUEST_SOURCE_TYPE
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 51
  dataTypeLength: 30
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: APEX_STANDARD_CONDITIONS
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_BUTTON_TEMPLATES
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PAGE_PLUGS
- schema: APEX_050000
  name: WWV_FLOW_PATCHES
- schema: APEX_050000
  name: WWV_FLOW_SECURITY_SCHEMES
- schema: APEX_050000
  name: WWV_FLOW_STEPS
- schema: APEX_050000
  name: WWV_FLOW_STEP_BUTTONS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    p.flow_id application_id,
    f.name application_name,
    p.id page_id,
    p.name page_name,
    --
    b.BUTTON_SEQUENCE button_sequence,
    (
      select
        plug_name
      from
        wwv_flow_page_plugs
      where
        id = b.BUTTON_PLUG_ID
    ) region,
    b.button_plug_id region_id,
    b.BUTTON_NAME button_name,
    b.button_static_id button_static_id,
    (
      select
        template_name
      from
        wwv_flow_button_templates
      where
        id = b.button_template_id
        and flow_id = f.id
    ) button_template,
    to_char(b.button_template_id) button_template_id,
    b.button_template_options button_template_options,
    case
      b.button_is_hot
      when 'Y' then 'Yes'
      when 'N' then 'No'
    end button_is_hot,
    cast(null as varchar2(10)) image_name,
    b.BUTTON_IMAGE_ALT label,
    nullif(b.BUTTON_POSITION, 'BODY') display_position,
    case
      b.grid_new_grid
      when 'Y' then 'Yes'
      else 'No'
    end new_grid,
    case
      b.grid_new_row
      when 'Y' then 'Yes'
      else 'No'
    end new_grid_row,
    case
      b.grid_new_column
      when 'Y' then 'Yes'
      else 'No'
    end new_grid_column,
    grid_column,
    grid_column_span,
    grid_column_css_classes,
    grid_column_attributes,
    b.BUTTON_ALIGNMENT alignment,
    --
    decode(
      b.button_action,
      'SUBMIT',
      'Submit Page',
      'REDIRECT_PAGE',
      'Redirect to Page in this Application',
      'REDIRECT_URL',
      'Redirect to URL',
      'DEFINED_BY_DA',
      'Defined by Dynamic Action',
      b.button_action
    ) button_action,
    b.button_action button_action_code,
    b.BUTTON_REDIRECT_URL redirect_url,
    case
      nvl(b.button_execute_validations, 'Y')
      when 'Y' then 'Yes'
      when 'N' then 'No'
    end execute_validations,
    --
    nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = b.BUTTON_CONDITION_TYPE
      ),
      b.BUTTON_CONDITION_TYPE
    ) condition_type,
    b.button_condition_type condition_type_code,
    b.BUTTON_CONDITION condition_expression1,
    b.BUTTON_CONDITION2 condition_expression2,
    cast(null as varchar2(10)) image_attributes,
    b.button_css_classes button_css_classes,
    b.icon_css_classes icon_css_classes,
    b.BUTTON_CATTRIBUTES button_attributes,
    decode(
      b.DATABASE_ACTION,
      'DELETE',
      'SQL DELETE action',
      'INSERT',
      'SQL INSERT action',
      'UPDATE',
      'SQL UPDATE action',
      b.DATABASE_ACTION
    ) database_action,
    --
    (
      select
        case
          when b.required_patch > 0 then PATCH_NAME
          else '{Not ' || PATCH_NAME || '}'
        end PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(b.REQUIRED_PATCH)
    ) build_option,
    --
    decode(substr(b.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(b.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      b.SECURITY_SCHEME
    ) authorization_scheme,
    b.SECURITY_SCHEME authorization_scheme_id,
    --
    b.LAST_UPDATED_BY last_updated_by,
    b.LAST_UPDATED_ON last_updated_on,
    b.BUTTON_COMMENT component_comment,
    case
      button_position
      when 'BODY' then 'Among region items'
      else 'Region Position'
    end button_position,
    b.id button_id,
    --
    b.BUTTON_NAME || ',s=' || rpad(b.BUTTON_SEQUENCE, 5, '00000') || ',r='(
      select
        plug_name
      from
        wwv_flow_page_plugs
      where
        id = b.BUTTON_PLUG_ID
    ) || ',bs=' || b.button_static_id || ' t='(
      select
        template_name
      from
        wwv_flow_button_templates t
      where
        b.button_template_id = t.id
        and t.flow_id = f.id
    ) || ' label=' || b.BUTTON_IMAGE_ALT || ' p=' || b.BUTTON_POSITION || ' a=' || b.BUTTON_ALIGNMENT || ' ba=' || b.button_action || ' u=' || substr(b.BUTTON_REDIRECT_URL, 1, 30) || length(b.BUTTON_REDIRECT_URL) || ' c=' || b.BUTTON_CONDITION_TYPE || substr(b.BUTTON_CONDITION, 1, 20) || length(b.BUTTON_CONDITION) || '.' || substr(b.BUTTON_CONDITION2, 1, 20) || length(b.BUTTON_CONDITION2) || ' ca=' || substr(b.BUTTON_CATTRIBUTES, 1, 20) || length(b.BUTTON_CATTRIBUTES) || ' b=' || decode(
      b.DATABASE_ACTION,
      'DELETE',
      'SQLDELETE',
      'INSERT',
      'SQLINSERT',
      'UPDATE',
      'SQLUPDATE',
      b.DATABASE_ACTION
    ) || ' b='(
      select
        PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(b.REQUIRED_PATCH)
    ) || ' s=' || decode(substr(b.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(b.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      'Not found'
    ) component_signature,
    b.PRE_ELEMENT_TEXT pre_element_text,
    b.POST_ELEMENT_TEXT post_element_text,
    b.request_source_type request_source_type
  from
    wwv_flow_step_buttons b,
    wwv_flow_steps p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = p.security_group_id
    and f.security_group_id = b.security_group_id
    and f.id = p.flow_id
    and f.id = b.flow_id
    and p.id = b.flow_step_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
