schema: APEX_050000
name: APEX_APPLICATION_TEMP_PAGE
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 65
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 68
  dataTypeLength: 4000
- name: CSS_FILE_URLS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: CURRENT_IMAGE_TAB
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 4000
- name: CURRENT_PARENT_TAB
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: CURRENT_PARENT_TAB_ATTR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 255
- name: CURRENT_TAB
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 4000
- name: CURRENT_TAB_FONT_ATTR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 255
- name: DEFAULT_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 60
  dataTypeLength: 255
- name: DIALOG_BROWSER_FRAME
  dataType: VARCHAR2
  textMaxLength: 20
  nullable: true
  ordinalPosition: 51
  dataTypeLength: 20
- name: DIALOG_CSS_CLASSES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 50
  dataTypeLength: 255
- name: DIALOG_HEIGHT
  dataType: VARCHAR2
  textMaxLength: 20
  nullable: true
  ordinalPosition: 47
  dataTypeLength: 20
- name: DIALOG_JS_CANCEL_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 255
- name: DIALOG_JS_CLOSE_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 255
- name: DIALOG_JS_INIT_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 255
- name: DIALOG_MAX_WIDTH
  dataType: VARCHAR2
  textMaxLength: 20
  nullable: true
  ordinalPosition: 49
  dataTypeLength: 20
- name: DIALOG_WIDTH
  dataType: VARCHAR2
  textMaxLength: 20
  nullable: true
  ordinalPosition: 48
  dataTypeLength: 20
- name: ERROR_PAGE_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 55
  dataTypeLength: 4000
- name: FOOTER_TEMPLATE
  dataType: CLOB
  nullable: true
  ordinalPosition: 17
  dataTypeLength:
- name: GRID_ALWAYS_EMIT
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 3
- name: GRID_ALWAYS_USE_MAX_COLUMNS
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 3
- name: GRID_COLUMN_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 4000
- name: GRID_DEFAULT_LABEL_COL_SPAN
  dataType: NUMBER
  nullable: true
  ordinalPosition: 40
  dataTypeLength:
- name: GRID_EMIT_EMPTY_LEADING_COLS
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 38
  dataTypeLength: 3
- name: GRID_EMIT_EMPTY_TRAILING_COLS
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 39
  dataTypeLength: 3
- name: GRID_FIRST_COLUMN_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 44
  dataTypeLength: 255
- name: GRID_HAS_COLUMN_SPAN
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 3
- name: GRID_JAVASCRIPT_DEBUG_CODE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 46
  dataTypeLength: 4000
- name: GRID_LAST_COLUMN_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 255
- name: GRID_MAX_COLUMNS
  dataType: NUMBER
  numericPrecision: 2
  numericScale: 0
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 2,0
- name: GRID_ROW_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 42
  dataTypeLength: 4000
- name: GRID_TABLE_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 52
  dataTypeLength: 255
- name: GRID_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 41
  dataTypeLength: 4000
- name: GRID_TYPE
  dataType: VARCHAR2
  textMaxLength: 8
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 8
- name: GRID_TYPE_CODE
  dataType: VARCHAR2
  textMaxLength: 8
  nullable: false
  ordinalPosition: 33
  dataTypeLength: 8
- name: HAS_EDIT_LINKS
  dataType: CHAR
  textMaxLength: 1
  nullable: true
  ordinalPosition: 54
  dataTypeLength: 1
- name: HEADER_TEMPLATE
  dataType: CLOB
  nullable: true
  ordinalPosition: 15
  dataTypeLength:
- name: INLINE_CSS
  dataType: CLOB
  nullable: true
  ordinalPosition: 14
  dataTypeLength:
- name: IS_POPUP
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: false
  ordinalPosition: 6
  dataTypeLength: 1
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 56
  dataTypeLength: 3
- name: JAVASCRIPT_CODE
  dataType: CLOB
  nullable: true
  ordinalPosition: 8
  dataTypeLength:
- name: JAVASCRIPT_CODE_ONLOAD
  dataType: CLOB
  nullable: true
  ordinalPosition: 9
  dataTypeLength:
- name: JAVASCRIPT_FILE_URLS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 4000
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 62
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 63
  dataTypeLength:
- name: MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 4000
- name: MULTICOLUMN_REGION_TABLE_ATTR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 53
  dataTypeLength: 255
- name: NAVBAR_ENTRY
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: NAVIGATION_BAR
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 4000
- name: NONCURRENT_PARENT_TAB
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 4000
- name: NONCURRENT_PARENT_TAB_ATTR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 255
- name: NON_CURRENT_IMAGE_TAB
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: NON_CURRENT_TAB
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: NON_CURRENT_TAB_FONT_ATTR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 255
- name: PAGE_BODY
  dataType: CLOB
  nullable: true
  ordinalPosition: 16
  dataTypeLength:
- name: PAGE_TEMPLATE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 67
  dataTypeLength:
- name: PRESET_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 61
  dataTypeLength: 255
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 57
  dataTypeLength: 297
- name: SUCCESS_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: TEMPLATE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 66
  dataTypeLength:
- name: TEMPLATE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: THEME_CLASS
  dataType: VARCHAR2
  textMaxLength: 40
  nullable: true
  ordinalPosition: 59
  dataTypeLength: 40
- name: THEME_NUMBER
  dataType: NUMBER
  nullable: true
  ordinalPosition: 58
  dataTypeLength:
- name: TRANSLATABLE
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 64
  dataTypeLength: 3
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_TEMPLATES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.NAME template_name,
    --t.LOOK
    --
    t.is_popup,
    t.javascript_file_urls,
    t.javascript_code,
    t.javascript_code_onload,
    t.dialog_js_init_code,
    t.dialog_js_close_code,
    t.dialog_js_cancel_code,
    t.css_file_urls,
    t.inline_css,
    t.HEADER_TEMPLATE,
    t.BOX page_body,
    t.FOOTER_TEMPLATE,
    --
    t.SUCCESS_MESSAGE,
    t.CURRENT_TAB,
    t.CURRENT_TAB_FONT_ATTR,
    t.NON_CURRENT_TAB,
    t.NON_CURRENT_TAB_FONT_ATTR,
    t.CURRENT_IMAGE_TAB,
    t.NON_CURRENT_IMAGE_TAB,
    t.TOP_CURRENT_TAB Current_Parent_Tab,
    t.TOP_CURRENT_TAB_FONT_ATTR Current_Parent_Tab_attr,
    t.TOP_NON_CURRENT_TAB NonCurrent_Parent_Tab,
    t.TOP_NON_CURRENT_TAB_FONT_ATTR NonCurrent_Parent_Tab_attr,
    --
    t.NAVIGATION_BAR,
    t.NAVBAR_ENTRY,
    --t.BODY_TITLE                     ,
    t.MESSAGE,
    --t.ATTRIBUTE1                     ,
    --t.ATTRIBUTE2                     ,
    --t.ATTRIBUTE3                     ,
    --t.ATTRIBUTE4                     ,
    --t.ATTRIBUTE5                     ,
    --t.ATTRIBUTE6                     ,
    --t.DEFAULT_BUTTON_POSITION        ,
    --t.TABLE_BGCOLOR                  ,
    --t.HEADING_BGCOLOR                ,
    --t.TABLE_CATTRIBUTES              ,
    --t.FONT_SIZE                      ,
    --t.FONT_FACE                      ,
    case
      t.grid_type
      when 'TABLE' then 'Table'
      when 'FIXED' then 'Fixed'
      when 'VARIABLE' then 'Variable'
    end as grid_type,
    t.grid_type as grid_type_code,
    t.grid_max_columns,
    case
      t.grid_always_use_max_columns
      when 'Y' then 'Yes'
      when 'N' then 'No'
    end as grid_always_use_max_columns,
    case
      t.grid_has_column_span
      when 'Y' then 'Yes'
      when 'N' then 'No'
    end as grid_has_column_span,
    case
      t.grid_always_emit
      when 'Y' then 'Yes'
      when 'N' then 'No'
    end as grid_always_emit,
    case
      t.grid_emit_empty_leading_cols
      when 'Y' then 'Yes'
      when 'N' then 'No'
    end as grid_emit_empty_leading_cols,
    case
      t.grid_emit_empty_trailing_cols
      when 'Y' then 'Yes'
      when 'N' then 'No'
    end as grid_emit_empty_trailing_cols,
    t.grid_default_label_col_span,
    t.grid_template,
    t.grid_row_template,
    t.grid_column_template,
    t.grid_first_column_attributes,
    t.grid_last_column_attributes,
    t.grid_javascript_debug_code,
    t.dialog_height,
    t.dialog_width,
    t.dialog_max_width,
    t.dialog_css_classes,
    t.dialog_browser_frame,
    t.REGION_TABLE_CATTRIBUTES as grid_table_attributes,
    t.REGION_TABLE_CATTRIBUTES as MultiColumn_Region_Table_Attr,
    /* for backward compatibility */
    --
    --t.APP_TAB_BEFORE_TABS            ,
    --t.APP_TAB_CURRENT_TAB            ,
    --t.APP_TAB_NON_CURRENT_TAB        ,
    --t.APP_TAB_AFTER_TABS             ,
    --
    'Y' as has_edit_links,
    --
    t.ERROR_PAGE_TEMPLATE,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        wwv_flow_templates
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    --t.BREADCRUMB_DEF_REG_POS         ,
    --t.SIDEBAR_DEF_REG_POS            ,
    --t.REQUIRED_PATCH                 ,
    t.THEME_ID theme_number,
    decode(
      t.THEME_CLASS_ID,
      '1',
      'One Level Tabs',
      '2',
      'Two Level Tabs',
      '3',
      'No Tabs',
      '4',
      'Popup',
      '5',
      'Printer Friendly',
      '6',
      'Login',
      '7',
      'Unknown',
      '8',
      'Custom 1',
      '9',
      'Custom 2',
      '10',
      'Custom 3',
      '11',
      'Custom 4',
      '12',
      'Custom 5',
      '13',
      'Custom 6',
      '14',
      'Custom 7',
      '15',
      'Custom 8',
      '16',
      'One Level Tabs with Sidebar',
      '17',
      'No Tabs with Sidebar',
      '18',
      'Two Level Tabs with Sidebar',
      t.THEME_CLASS_ID
    ) theme_class,
    t.default_template_options default_template_options,
    t.preset_template_options preset_template_options,
    t.LAST_UPDATED_BY last_updated_by,
    t.LAST_UPDATED_ON last_updated_on,
    decode(
      t.TRANSLATE_THIS_TEMPLATE,
      'N',
      'No',
      'Y',
      'Yes',
      'Yes'
    ) translatable,
    t.TEMPLATE_COMMENT component_comment,
    t.id template_id,
    t.id page_template_id,
    --
    substr(t.NAME, 1, 40) || '.' || length(t.NAME) || ' h=' || sys.dbms_lob.substr(t.HEADER_TEMPLATE, 40, 1) || '.' || sys.dbms_lob.getlength(t.HEADER_TEMPLATE) || ' b=' || sys.dbms_lob.substr(t.BOX, 40, 1) || '.' || sys.dbms_lob.getlength(t.BOX) || ' f=' || sys.dbms_lob.substr(t.FOOTER_TEMPLATE, 40, 1) || '.' || sys.dbms_lob.getlength(t.FOOTER_TEMPLATE) || ' s=' || substr(t.SUCCESS_MESSAGE, 1, 40) || '.' || length(t.SUCCESS_MESSAGE) || ' t=' || substr(t.CURRENT_TAB, 1, 40) || '.' || length(t.CURRENT_TAB) || ' t=' || substr(t.CURRENT_TAB_FONT_ATTR, 1, 40) || '.' || length(t.CURRENT_TAB_FONT_ATTR) || ' n=' || substr(t.NON_CURRENT_TAB, 1, 40) || '.' || length(t.NON_CURRENT_TAB) || ' n=' || substr(t.NON_CURRENT_TAB_FONT_ATTR, 1, 40) || '.' || length(t.NON_CURRENT_TAB_FONT_ATTR) || ' i=' || substr(t.CURRENT_IMAGE_TAB, 1, 40) || '.' || length(t.CURRENT_IMAGE_TAB) || ' i=' || substr(t.NON_CURRENT_IMAGE_TAB, 1, 40) || '.' || length(t.NON_CURRENT_IMAGE_TAB) || ' t=' || substr(t.TOP_CURRENT_TAB, 1, 40) || '.' || length(t.TOP_CURRENT_TAB) || ' t=' || substr(t.TOP_CURRENT_TAB_FONT_ATTR, 1, 40) || '.' || length(t.TOP_CURRENT_TAB_FONT_ATTR) || ' t=' || substr(t.TOP_NON_CURRENT_TAB, 1, 40) || '.' || length(t.TOP_NON_CURRENT_TAB) || ' t=' || substr(t.TOP_NON_CURRENT_TAB_FONT_ATTR, 1, 40) || '.' || length(t.TOP_NON_CURRENT_TAB_FONT_ATTR) || ' n=' || substr(t.NAVIGATION_BAR, 1, 40) || '.' || length(t.NAVIGATION_BAR) || ' n=' || substr(t.NAVBAR_ENTRY, 1, 40) || '.' || length(t.NAVBAR_ENTRY) || ' m=' || substr(t.MESSAGE, 1, 40) || '.' || length(t.MESSAGE) || ' e=' || substr(t.ERROR_PAGE_TEMPLATE, 1, 40) || '.' || length(t.ERROR_PAGE_TEMPLATE) --
    || ' s=' || decode(t.REFERENCE_ID, null, 'No', 'Yes') || ' t=' || t.THEME_ID || ' c=' || decode(
      t.THEME_CLASS_ID,
      '1',
      'One Level Tabs',
      '2',
      'Two Level Tabs',
      '3',
      'No Tabs',
      '4',
      'Popup',
      '5',
      'Printer Friendly',
      '6',
      'Login',
      '7',
      'Unknown',
      '8',
      'Custom 1',
      '9',
      'Custom 2',
      '10',
      'Custom 3',
      '11',
      'Custom 4',
      '12',
      'Custom 5',
      '13',
      'Custom 6',
      '14',
      'Custom 7',
      '15',
      'Custom 8',
      '16',
      'One Level Tabs with Sidebar',
      '17',
      'No Tabs with Sidebar',
      '18',
      'Two Level Tabs with Sidebar',
      t.THEME_CLASS_ID
    ) || ' t=' || t.TRANSLATE_THIS_TEMPLATE component_signature
  from
    wwv_flow_templates t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
