schema: APEX_050000
name: APEX_APPLICATION_THEME_FILES
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 4
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 15
  dataTypeLength:
- name: FILE_CHARSET
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 128
- name: FILE_CONTENT
  dataType: BLOB
  nullable: true
  ordinalPosition: 10
  dataTypeLength:
- name: FILE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 7
  dataTypeLength: 255
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 17
  dataTypeLength:
- name: MIME_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 8
  dataTypeLength: 255
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 297
- name: SUBSCRIBED_FROM_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 13
  dataTypeLength:
- name: THEME_FILE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 1
  dataTypeLength:
- name: THEME_NUMBER
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 2
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 3
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOW_AUTHORIZED
- schema: APEX_050000
  name: WWV_FLOW_THEME_FILES
viewDefinition: |-
  select
    a .id as theme_file_id,
    f.workspace,
    f.workspace_display_name,
    f.application_id,
    f.application_name,
    a .theme_id as theme_number,
    a .file_name,
    a .mime_type,
    a .file_charset,
    a .file_content,
    nvl2(a .reference_id, 'Yes', 'No') as is_subscribed,
    (
      select
        a2.flow_id || '. ' || a2.file_name
      from
        wwv_flow_theme_files a2
      where
        a2.id = a .reference_id
    ) as subscribed_from,
    a .reference_id as subscribed_from_id,
    a .created_by,
    a .created_on,
    a .last_updated_by,
    a .last_updated_on
  from
    wwv_flow_authorized f,
    wwv_flow_theme_files a
  where
    a .flow_id = f.application_id
