schema: APEX_050000
name: APEX_APPLICATION_BC_ENTRIES
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    m.PARENT_ID parent_breadcrumb_id,
    m.MENU_ID breadcrumb_id,
    --m.OPTION_SEQUENCE                display_sequence,
    m.SHORT_NAME entry_label,
    m.LONG_NAME entry_long_label,
    m.LINK url,
    m.PAGE_ID defined_for_page,
    m.ALSO_CURRENT_FOR_PAGES current_for_pages,
    --
    nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = m.DISPLAY_WHEN_COND_TYPE
      ),
      m.DISPLAY_WHEN_COND_TYPE
    ) condition_type,
    m.display_when_cond_type condition_type_code,
    m.DISPLAY_WHEN_CONDITION condition_expression1,
    m.DISPLAY_WHEN_CONDITION2 condition_expression2,
    --
    decode(substr(m.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(m.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      m.SECURITY_SCHEME
    ) authorization_scheme,
    m.SECURITY_SCHEME authorization_scheme_id,
    --
    (
      select
        case
          when m.required_patch > 0 then PATCH_NAME
          else '{Not ' || PATCH_NAME || '}'
        end PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(m.REQUIRED_PATCH)
    ) build_option,
    m.LAST_UPDATED_BY last_updated_by,
    m.LAST_UPDATED_ON last_updated_on,
    m.MENU_OPTION_COMMENT component_comment,
    m.id breadcrumb_entry_id,
    --
    substr(m.SHORT_NAME, 1, 30) || length(m.SHORT_NAME) || substr(m.LONG_NAME, 1, 30) || length(m.LONG_NAME) || ' l=' || substr(m.LINK, 1, 30) || length(m.LINK) || ' p=' || PAGE_ID || ' c=' || substr(m.ALSO_CURRENT_FOR_PAGES, 1, 30) || length(m.ALSO_CURRENT_FOR_PAGES) || ' cond=' || m.DISPLAY_WHEN_COND_TYPE || substr(m.DISPLAY_WHEN_CONDITION, 1, 30) || length(m.DISPLAY_WHEN_CONDITION) || substr(m.DISPLAY_WHEN_CONDITION2, 1, 30) || length(m.DISPLAY_WHEN_CONDITION2) || ' sec=' || decode(substr(m.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(m.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      'Not found'
    ) || ' bo='(
      select
        PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(m.REQUIRED_PATCH)
    ) component_signature
  from
    wwv_flow_menu_options m,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = m.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
