schema: APEX_050000
name: APEX_APPL_PLUGIN_SETTINGS
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 4
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: ATTRIBUTE_01
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 4000
- name: ATTRIBUTE_02
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: ATTRIBUTE_03
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: ATTRIBUTE_04
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: ATTRIBUTE_05
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: ATTRIBUTE_06
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: ATTRIBUTE_07
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: ATTRIBUTE_08
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: ATTRIBUTE_09
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: ATTRIBUTE_10
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: ATTRIBUTE_11
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 4000
- name: ATTRIBUTE_12
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: ATTRIBUTE_13
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: ATTRIBUTE_14
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 4000
- name: ATTRIBUTE_15
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 4000
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 25
  dataTypeLength:
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 27
  dataTypeLength:
- name: PLUGIN
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 255
- name: PLUGIN_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 8
  dataTypeLength: 255
- name: PLUGIN_SETTING_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 1
  dataTypeLength:
- name: PLUGIN_TYPE
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: false
  ordinalPosition: 6
  dataTypeLength: 30
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 2
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 3
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOW_AUTHORIZED
- schema: APEX_050000
  name: WWV_FLOW_PLUGINS
- schema: APEX_050000
  name: WWV_FLOW_PLUGIN_SETTINGS
viewDefinition: |-
  select
    p.id as plugin_setting_id,
    f.workspace,
    f.workspace_display_name,
    f.application_id,
    f.application_name,
    p.plugin_type,
    case
      substr(p.plugin, 1, 7)
      when 'NATIVE_' then (
        select
          display_name
        from
          wwv_flow_plugins
        where
          flow_id = 4411
          and plugin_type = p.plugin_type
          and name = substr(p.plugin, 8)
      )
      when 'PLUGIN_' then (
        select
          display_name
        from
          wwv_flow_plugins
        where
          flow_id = p.flow_id
          and plugin_type = p.plugin_type
          and name = substr(p.plugin, 8)
      )
      else p.plugin
    end as plugin,
    p.plugin as plugin_code,
    p.attribute_01,
    p.attribute_02,
    p.attribute_03,
    p.attribute_04,
    p.attribute_05,
    p.attribute_06,
    p.attribute_07,
    p.attribute_08,
    p.attribute_09,
    p.attribute_10,
    p.attribute_11,
    p.attribute_12,
    p.attribute_13,
    p.attribute_14,
    p.attribute_15,
    p.created_by,
    p.created_on,
    p.last_updated_by,
    p.last_updated_on
  from
    wwv_flow_authorized f,
    wwv_flow_plugin_settings p
  where
    p.flow_id = f.application_id
