schema: APEX_050000
name: APEX_APPLICATION_PAGE_TREES
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 22
  dataTypeLength:
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 5
  dataTypeLength:
- name: PAGE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 6
  dataTypeLength: 255
- name: REGION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 7
  dataTypeLength:
- name: REGION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 8
  dataTypeLength: 255
- name: SHOW_HINTS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: TREE_BUTTON_OPTION
  dataType: VARCHAR2
  textMaxLength: 10
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 10
- name: TREE_CLICK_ACTION
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: TREE_HAS_FOCUS
  dataType: VARCHAR2
  textMaxLength: 10
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 10
- name: TREE_HINT_TEXT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: TREE_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 9
  dataTypeLength:
- name: TREE_QUERY
  dataType: CLOB
  nullable: true
  ordinalPosition: 10
  dataTypeLength:
- name: TREE_SELECTED_NODE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: TREE_SOURCE
  dataType: CLOB
  nullable: true
  ordinalPosition: 11
  dataTypeLength:
- name: TREE_START_ITEM
  dataType: VARCHAR2
  textMaxLength: 10
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 10
- name: TREE_START_VALUE
  dataType: VARCHAR2
  textMaxLength: 10
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 10
- name: TREE_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PAGE_PLUGS
- schema: APEX_050000
  name: WWV_FLOW_STEPS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    p.id page_id,
    p.name page_name,
    t.id region_id,
    t.plug_name region_name,
    --
    case
      when regexp_like(t.attribute_06, '^tree\d+$') then to_number(regexp_substr(t.attribute_06, '\d+'))
      else t.id
    end tree_id,
    t.plug_source tree_query,
    regexp_substr (
      t.plug_source,
      'from[:space:]*"?([^"[:space:]]+)',
      1,
      1,
      'i',
      1
    ) tree_source,
    t.attribute_01 tree_template,
    t.attribute_02 tree_click_action,
    cast(null as varchar2(10)) tree_start_value,
    cast(null as varchar2(10)) tree_start_item,
    t.attribute_03 tree_selected_node,
    t.attribute_04 show_hints,
    t.attribute_05 tree_hint_text,
    cast(null as varchar2(10)) tree_has_focus,
    cast(null as varchar2(10)) tree_button_option,
    --
    t.last_updated_by last_updated_by,
    t.last_updated_on last_updated_on,
    --
    t.plug_comment component_comment,
    --
    p.name || ' t=' || sys.dbms_lob.substr(t.plug_source, 50) || sys.dbms_lob.getlength(t.plug_source) || ' template=' || t.attribute_01 || ' links=' || t.attribute_02 || ' sel=' || t.attribute_03 || ' hints=' || t.attribute_04 || ':' || t.attribute_05 component_signature
  from
    wwv_flow_page_plugs t,
    wwv_flow_steps p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.provisioning_company_id
    )
    and f.security_group_id = w.provisioning_company_id
    and s.security_group_id = w.provisioning_company_id
    and s.schema = f.owner
    and f.security_group_id = p.security_group_id
    and f.security_group_id = t.security_group_id
    and f.id = p.flow_id
    and f.id = t.flow_id
    and p.id = t.page_id
    and t.plug_source_type = 'NATIVE_JSTREE'
    and (
      d.sgid != 0
      or nvl(f.build_status, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.provisioning_company_id != 0
