schema: APEX_050000
name: APEX_APPLICATION_PAGE_DB_ITEMS
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: DB_COLUMN_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: DB_TABLE_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: DISPLAY_AS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 9
  dataTypeLength: 255
- name: DISPLAY_SEQUENCE
  dataType: NUMBER
  nullable: false
  ordinalPosition: 10
  dataTypeLength:
- name: HELP_TEXT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: ITEM_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 15
  dataTypeLength:
- name: ITEM_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: ITEM_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 8
  dataTypeLength: 255
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 5
  dataTypeLength:
- name: PAGE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 6
  dataTypeLength: 255
- name: REGION
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PAGE_PLUGS
- schema: APEX_050000
  name: WWV_FLOW_STEPS
- schema: APEX_050000
  name: WWV_FLOW_STEP_ITEMS
- schema: APEX_050000
  name: WWV_FLOW_STEP_ITEM_HELP
- schema: APEX_050000
  name: WWV_FLOW_STEP_PROCESSING
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    p.flow_id application_id,
    f.name application_name,
    p.id page_id,
    p.name page_name,
    (
      select
        plug_name
      from
        wwv_flow_page_plugs
      where
        id = i.ITEM_PLUG_ID
    ) region,
    --
    i.name item_name,
    i.display_as display_as,
    i.ITEM_SEQUENCE display_sequence,
    --
    i.PROMPT item_label,
    i.SOURCE db_column_name,
    (
      select
        attribute_02
      from
        wwv_flow_step_processing proc
      where
        proc.security_group_id = p.security_group_id
        and proc.flow_id = p.flow_id
        and proc.flow_step_id = p.id
        and proc.process_type = 'NATIVE_FORM_FETCH'
    ) db_table_name,
    h.help_text help_text,
    i.id item_id
  from
    wwv_flow_step_items i,
    wwv_flow_step_item_help h,
    wwv_flow_steps p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = p.security_group_id
    and i.id = h.flow_item_id (+)
    and f.id = p.flow_id
    and f.id = i.flow_id
    and p.id = i.flow_step_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and i.source_type = 'DB_COLUMN'
    and w.PROVISIONING_COMPANY_ID != 0
