schema: APEX_050000
name: APEX_APPLICATION_TABS
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: AUTHORIZATION_SCHEME
  dataType: VARCHAR2
  textMaxLength: 259
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 259
- name: AUTHORIZATION_SCHEME_ID
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 255
- name: BUILD_OPTION
  dataType: VARCHAR2
  textMaxLength: 261
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 261
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 2636
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 2636
- name: CONDITION_EXPRESSION1
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION2
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: CONDITION_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 255
- name: CONDITION_TYPE_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 255
- name: DISPLAY_SEQUENCE
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 23
  dataTypeLength:
- name: PARENT_TABSET
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 255
- name: TAB_ALSO_CURRENT_FOR_PAGES
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: TAB_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 25
  dataTypeLength:
- name: TAB_IMAGE_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 255
- name: TAB_LABEL
  dataType: VARCHAR2
  textMaxLength: 2000
  nullable: false
  ordinalPosition: 11
  dataTypeLength: 2000
- name: TAB_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 7
  dataTypeLength: 255
- name: TAB_PAGE
  dataType: NUMBER
  nullable: false
  ordinalPosition: 12
  dataTypeLength:
- name: TAB_SET
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: WHEN_CURRENT_TAB_IMAGE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: WHEN_NOT_CURRENT_TAB_IMAGE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: APEX_STANDARD_CONDITIONS
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PATCHES
- schema: APEX_050000
  name: WWV_FLOW_SECURITY_SCHEMES
- schema: APEX_050000
  name: WWV_FLOW_TABS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.TAB_SET tab_set,
    t.TAB_SEQUENCE display_sequence,
    t.TAB_NAME tab_name,
    t.TAB_IMAGE when_current_tab_image,
    t.TAB_NON_CURRENT_IMAGE when_not_current_tab_image,
    t.TAB_IMAGE_ATTRIBUTES tab_image_attributes,
    t.TAB_TEXT tab_label,
    t.TAB_STEP tab_page,
    t.TAB_ALSO_CURRENT_FOR_PAGES tab_also_current_for_pages,
    t.TAB_PARENT_TABSET parent_tabset,
    --
    nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = t.DISPLAY_CONDITION_TYPE
      ),
      t.DISPLAY_CONDITION_TYPE
    ) condition_type,
    t.display_condition_type condition_type_code,
    t.TAB_PLSQL_CONDITION condition_expression1,
    t.TAB_DISP_COND_TEXT condition_expression2,
    --
    (
      select
        case
          when t.required_patch > 0 then PATCH_NAME
          else '{Not ' || PATCH_NAME || '}'
        end PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(t.REQUIRED_PATCH)
    ) build_option,
    --
    decode(substr(t.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(t.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      t.SECURITY_SCHEME
    ) authorization_scheme,
    t.SECURITY_SCHEME authorization_scheme_id,
    --
    t.LAST_UPDATED_BY last_updated_by,
    t.LAST_UPDATED_ON last_updated_on,
    t.TAB_COMMENT component_comment,
    t.id tab_id,
    --
    t.TAB_SET || ' ' || lpad(t.TAB_SEQUENCE, 5, '00000') || ' ' || t.TAB_NAME || substr(t.TAB_IMAGE, 1, 30) || length(t.TAB_IMAGE) || substr(t.TAB_NON_CURRENT_IMAGE, 1, 30) || length(t.TAB_NON_CURRENT_IMAGE) || substr(t.TAB_IMAGE_ATTRIBUTES, 1, 30) || length(t.TAB_IMAGE_ATTRIBUTES) || ' text=' || substr(t.TAB_TEXT, 1, 30) || length(t.TAB_TEXT) || ' p=' || t.TAB_STEP || ' a=' || substr(t.TAB_ALSO_CURRENT_FOR_PAGES, 1, 30) || length(t.TAB_ALSO_CURRENT_FOR_PAGES) || substr(t.TAB_PARENT_TABSET, 1, 30) || length(t.TAB_PARENT_TABSET) || ' c=' || t.DISPLAY_CONDITION_TYPE || substr(t.TAB_PLSQL_CONDITION, 1, 30) || length(t.TAB_PLSQL_CONDITION) || substr(t.TAB_DISP_COND_TEXT, 1, 30) || length(t.TAB_DISP_COND_TEXT)(
      select
        PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(t.REQUIRED_PATCH)
    ) || decode(substr(t.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(t.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      'Not found'
    ) component_signature
  from
    wwv_flow_tabs t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
