schema: APEX_050000
name: APEX_APPLICATION_TREES
updatedAllowed: true
insertAllowed: true
columns:
- name: AFTER_TREE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 4000
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: APPLICATION_TREE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 34
  dataTypeLength:
- name: BEFORE_TREE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 1690
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 1690
- name: DRILL_UP
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: EXPANDED_PARENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: EXPANDED_PARENT_LAST
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: FLOW_ITEM
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: INDENT_VERTICAL_LINE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 4000
- name: INDENT_VERTICAL_LINE_LAST
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 32
  dataTypeLength:
- name: LEAF_NODE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: LEAF_NODE_LAST
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: LEVEL_1_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 4000
- name: LEVEL_2_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: LEVEL_3_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: LEVEL_4_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 4000
- name: LEVEL_5_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 4000
- name: LEVEL_6_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 4000
- name: LEVEL_7_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 4000
- name: LEVEL_8_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: MAXIMUM_LEVELS
  dataType: NUMBER
  nullable: false
  ordinalPosition: 9
  dataTypeLength:
- name: NAME_LINK_ANCHOR_TAG
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: NAME_LINK_NOT_ANCHOR_TAG
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: TREE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: TREE_QUERY
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 4000
- name: TREE_TYPE
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 30
- name: UNEXPANDED_PARENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: UNEXPANDED_PARENT_LAST
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_TREES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.TREE_NAME tree_name,
    t.TREE_TYPE tree_type,
    t.TREE_QUERY tree_query,
    t.FLOW_ITEM,
    t.MAX_LEVELS maximum_levels,
    t.UNEXPANDED_PARENT,
    t.UNEXPANDED_PARENT_LAST,
    t.EXPANDED_PARENT,
    t.EXPANDED_PARENT_LAST,
    t.LEAF_NODE,
    t.LEAF_NODE_LAST,
    t.DRILL_UP,
    t.NAME_LINK_ANCHOR_TAG,
    t.NAME_LINK_NOT_ANCHOR_TAG,
    t.INDENT_VERTICAL_LINE,
    t.INDENT_VERTICAL_LINE_LAST,
    t.BEFORE_TREE,
    t.AFTER_TREE,
    t.LEVEL_1_TEMPLATE,
    t.LEVEL_2_TEMPLATE,
    t.LEVEL_3_TEMPLATE,
    t.LEVEL_4_TEMPLATE,
    t.LEVEL_5_TEMPLATE,
    t.LEVEL_6_TEMPLATE,
    t.LEVEL_7_TEMPLATE,
    t.LEVEL_8_TEMPLATE,
    --
    t.LAST_UPDATED_BY last_updated_by,
    t.LAST_UPDATED_ON last_updated_on,
    --
    t.TREE_COMMENT component_comment,
    t.id application_tree_id,
    --
    t.TREE_NAME || ' t=' || t.TREE_TYPE || substr(t.TREE_QUERY, 1, 50) || length(t.tree_query) || ' i=' || t.FLOW_ITEM || ' l=' || t.MAX_LEVELS || '.' || length(t.UNEXPANDED_PARENT) || '.' || length(t.UNEXPANDED_PARENT_LAST) || '.' || length(t.EXPANDED_PARENT) || '.' || length(t.EXPANDED_PARENT_LAST) || '.' || length(t.LEAF_NODE) || '.' || length(t.LEAF_NODE_LAST) || '.' || length(t.DRILL_UP) || '.' || length(t.NAME_LINK_ANCHOR_TAG) || '.' || length(t.NAME_LINK_NOT_ANCHOR_TAG) || '.' || length(t.INDENT_VERTICAL_LINE) || '.' || length(t.INDENT_VERTICAL_LINE_LAST) || '.' || length(t.BEFORE_TREE) || '.' || length(t.AFTER_TREE) || '.' || length(t.LEVEL_1_TEMPLATE) || '.' || length(t.LEVEL_2_TEMPLATE) || '.' || length(t.LEVEL_3_TEMPLATE) || '.' || length(t.LEVEL_4_TEMPLATE) || '.' || length(t.LEVEL_5_TEMPLATE) || '.' || length(t.LEVEL_6_TEMPLATE) || '.' || length(t.LEVEL_7_TEMPLATE) || '.' || length(t.LEVEL_8_TEMPLATE) component_signature
  from
    wwv_flow_trees t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
