schema: APEX_050000
name: APEX_APPLICATION_PAGE_IR_RPT
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: APPLICATION_USER
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 255
- name: AVG_COLUMNS_ON_BREAK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 38
  dataTypeLength: 4000
- name: BASE_REPORT_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 13
  dataTypeLength:
- name: BREAK_ENABLED_ON
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 4000
- name: BREAK_ON
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 4000
- name: CATEGORY_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 18
  dataTypeLength:
- name: CHART_AGGREGATE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 50
  dataTypeLength: 255
- name: CHART_LABEL_COLUMN
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 47
  dataTypeLength: 255
- name: CHART_LABEL_TITLE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 48
  dataTypeLength: 255
- name: CHART_SORT_ORDER
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 52
  dataTypeLength: 30
- name: CHART_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 46
  dataTypeLength: 255
- name: CHART_VALUE_COLUMN
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 49
  dataTypeLength: 255
- name: CHART_VALUE_TITLE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 51
  dataTypeLength: 255
- name: COUNT_COLUMNS_ON_BREAK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 42
  dataTypeLength: 4000
- name: COUNT_DISTNT_COL_ON_BREAK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 4000
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 54
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 53
  dataTypeLength:
- name: DISPLAY_ROWS
  dataType: NUMBER
  nullable: true
  ordinalPosition: 21
  dataTypeLength:
- name: DISPLAY_SEQUENCE
  dataType: NUMBER
  nullable: false
  ordinalPosition: 15
  dataTypeLength:
- name: FLASHBACK_ENABLED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 3
- name: FLASHBACK_MINUTES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 44
  dataTypeLength: 255
- name: INTERACTIVE_REPORT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 7
  dataTypeLength:
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 56
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 55
  dataTypeLength:
- name: MAX_COLUMNS_ON_BREAK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 39
  dataTypeLength: 4000
- name: MEDIAN_COLUMNS_ON_BREAK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 41
  dataTypeLength: 4000
- name: MIN_COLUMNS_ON_BREAK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 40
  dataTypeLength: 4000
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 5
  dataTypeLength:
- name: REGION_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 6
  dataTypeLength:
- name: REPORT_ALIAS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 255
- name: REPORT_COLUMNS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 4000
- name: REPORT_DESCRIPTION
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: REPORT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 8
  dataTypeLength:
- name: REPORT_LINK_EXAMPLE
  dataType: VARCHAR2
  textMaxLength: 583
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 583
- name: REPORT_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 255
- name: REPORT_TYPE
  dataType: VARCHAR2
  textMaxLength: 19
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 19
- name: REPORT_VIEW_MODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 255
- name: SESSION_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 12
  dataTypeLength:
- name: SORT_COLUMN_1
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 255
- name: SORT_COLUMN_2
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 255
- name: SORT_COLUMN_3
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 255
- name: SORT_COLUMN_4
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 255
- name: SORT_COLUMN_5
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 255
- name: SORT_COLUMN_6
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 255
- name: SORT_DIRECTION_1
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 255
- name: SORT_DIRECTION_2
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 255
- name: SORT_DIRECTION_3
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 255
- name: SORT_DIRECTION_4
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 255
- name: SORT_DIRECTION_5
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 255
- name: SORT_DIRECTION_6
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 255
- name: STATUS
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 30
- name: SUM_COLUMNS_ON_BREAK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 4000
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PAGE_PLUGS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEETS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEET_RPTS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    r.page_id page_id,
    ws.region_id region_id,
    r.worksheet_id interactive_report_id,
    r.id report_id,
    r.application_user application_user,
    r.name report_name,
    r.report_alias,
    r.session_id,
    r.base_report_id,
    r.description report_description,
    r.report_seq display_sequence,
    (
      case
        when r.view_mode is null
        or r.view_mode = 'REPORT' then r.report_type
        else r.view_mode
      end
    ) report_view_mode,
    r.status,
    r.category_id,
    (
      case
        when r.is_default = 'Y'
        and r.application_user = 'APXWS_DEFAULT' then 'PRIMARY_DEFAULT'
        when r.is_default = 'Y'
        and r.application_user = 'APXWS_ALTERNATIVE' then 'ALTERNATIVE_DEFAULT'
        when r.session_id is null
        and r.status = 'PUBLIC' then 'PUBLIC'
        when r.session_id is null
        and r.status = 'PRIVATE' then 'PRIVATE'
        else 'SESSION'
      end
    ) report_type,
    (
      case
        when r.report_alias is not null then 'f?p=' || chr(38) || 'APP_ID.:' || r.page_id || ':' || chr(38) || 'APP_SESSION.:IR' || case
          when p.region_name is not null then '[' || p.region_name || ']'
        end || '_' || r.report_alias
      end
    ) report_link_example,
    r.display_rows,
    r.report_columns,
    --
    r.sort_column_1,
    r.sort_direction_1,
    r.sort_column_2,
    r.sort_direction_2,
    r.sort_column_3,
    r.sort_direction_3,
    r.sort_column_4,
    r.sort_direction_4,
    r.sort_column_5,
    r.sort_direction_5,
    r.sort_column_6,
    r.sort_direction_6,
    --
    r.break_on,
    r.break_enabled_on,
    --
    r.sum_columns_on_break,
    r.avg_columns_on_break,
    r.max_columns_on_break,
    r.min_columns_on_break,
    r.median_columns_on_break,
    r.count_columns_on_break,
    r.count_distnt_col_on_break,
    --
    r.flashback_mins_ago flashback_minutes,
    decode(
      r.flashback_enabled,
      'Y',
      'Yes',
      'N',
      'No',
      r.flashback_enabled
    ) flashback_enabled,
    --
    r.chart_type,
    r.chart_label_column,
    r.chart_label_title,
    r.chart_value_column,
    r.chart_aggregate,
    r.chart_value_title,
    decode(
      r.chart_sorting,
      'DEFAULT',
      'Default',
      'VALUE_DESC',
      'Value - Descending',
      'VALUE_ASC',
      'Value - Ascending',
      'LABEL_DESC',
      'Label - Descending',
      'LAVEL_ASC',
      'Label - Ascending',
      r.chart_sorting
    ) chart_sort_order,
    --
    r.created_on,
    r.created_by,
    r.updated_on last_updated_on,
    r.updated_by last_updated_by --
  from
    wwv_flow_worksheet_rpts r,
    wwv_flow_worksheets ws,
    wwv_flow_page_plugs p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = r.security_group_id
    and f.id = ws.flow_id
    and ws.id = r.worksheet_id
    and ws.region_id = p.id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
