schema: APEX_050000
name: APEX_APPLICATION_WEB_SERVICES
updatedAllowed: true
insertAllowed: true
columns:
- name: ACTION
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 4000
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 972
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 972
- name: FLOW_ITEMS_COMMA_DELIMITED
  dataType: CLOB
  nullable: true
  ordinalPosition: 11
  dataTypeLength:
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 26
  dataTypeLength:
- name: PROXY_OVERRIDE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 4000
- name: SOAP_ENVELOPE
  dataType: CLOB
  nullable: true
  ordinalPosition: 10
  dataTypeLength:
- name: SOAP_VERSION
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 30
- name: STATIC_PARM_01
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: STATIC_PARM_02
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: STATIC_PARM_03
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: STATIC_PARM_04
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: STATIC_PARM_05
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: STATIC_PARM_06
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: STATIC_PARM_07
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: STATIC_PARM_08
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 4000
- name: STATIC_PARM_09
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: STATIC_PARM_10
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: STYLESHEET
  dataType: CLOB
  nullable: true
  ordinalPosition: 22
  dataTypeLength:
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 297
- name: URL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 4000
- name: WEB_SERVICE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 27
  dataTypeLength:
- name: WEB_SERVICE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_SHARED_WEB_SERVICES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    ws.short_name workspace,
    ws.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    w.NAME web_service_name,
    w.URL,
    w.ACTION,
    w.PROXY_OVERRIDE,
    w.soap_version,
    w.SOAP_ENVELOPE,
    w.FLOW_ITEMS_COMMA_DELIMITED,
    w.STATIC_PARM_01,
    w.STATIC_PARM_02,
    w.STATIC_PARM_03,
    w.STATIC_PARM_04,
    w.STATIC_PARM_05,
    w.STATIC_PARM_06,
    w.STATIC_PARM_07,
    w.STATIC_PARM_08,
    w.STATIC_PARM_09,
    w.STATIC_PARM_10,
    w.STYLESHEET,
    --
    decode(w.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name n
      from
        wwv_flow_shared_web_services
      where
        id = w.id
    ) subscribed_from,
    --
    w.LAST_UPDATED_BY last_updated_by,
    w.LAST_UPDATED_ON last_updated_on,
    --
    w.id web_service_id,
    --
    substr(w.name, 1, 30) || length(w.name) || ' u=' || substr(w.url, 1, 30) || length(w.url) || ' a=' || substr(w.action, 1, 30) || ' sv=' || w.soap_version || ' p1=' || substr(w.static_parm_01, 1, 30) || length(w.static_parm_01) || ' p2=' || substr(w.static_parm_02, 1, 30) || length(w.static_parm_02) || ' p3=' || substr(w.static_parm_03, 1, 30) || length(w.static_parm_03) as component_signature
  from
    wwv_flow_shared_web_services w,
    wwv_flows f,
    wwv_flow_companies ws,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = ws.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = ws.PROVISIONING_COMPANY_ID
    and s.security_group_id = ws.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = w.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and ws.PROVISIONING_COMPANY_ID != 0
    and (
      user in ('SYS', 'SYSTEM', 'APEX_050000')
      or ws.PROVISIONING_COMPANY_ID != 10
    )
