schema: APEX_050000
name: APEX_APPLICATION_PAGE_BRANCHES
updatedAllowed: true
insertAllowed: true
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    p.flow_id application_id,
    f.name application_name,
    p.id page_id,
    p.name page_name,
    --
    b.branch_name branch_name,
    b.BRANCH_ACTION branch_action,
    b.BRANCH_POINT branch_point,
    decode(
      b.BRANCH_WHEN_BUTTON_ID,
      null,
      null,(
        select
          button_name
        from
          wwv_flow_step_buttons
        where
          id = b.BRANCH_WHEN_BUTTON_ID
        union
        select
          name
        from
          wwv_flow_step_items
        where
          id = b.BRANCH_WHEN_BUTTON_ID
      )
    ) when_button_pressed,
    decode(
      b.BRANCH_TYPE,
      'BRANCH_TO_FUNCTION_RETURNING_PAGE',
      'Branch to Function Returning a Page',
      'BRANCH_TO_FUNCTION_RETURNING_URL',
      'Branch to Function Returning a URL',
      'BRANCH_TO_PAGE_IDENT_BY_ITEM',
      'Branch to Page Identified by Item (Use Item Name)',
      'BRANCH_TO_PAGE_ACCEPT',
      'Branch to Page Accept Processing (not common)',
      'BRANCH_TO_STEP',
      'Branch to Page',
      'BRANCH_TO_URL_IDENT_BY_ITEM',
      'Branch to URL Identified by Item (Use Item Name)',
      'PLSQL',
      'Branch to PL/SQL Procedure',
      'REDIRECT_URL',
      'Branch to Page or URL',
      b.BRANCH_TYPE
    ) branch_type,
    b.BRANCH_SEQUENCE process_sequence,
    --b.CLEAR_PAGE_CACHE,
    nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = b.BRANCH_CONDITION_TYPE
      ),
      b.BRANCH_CONDITION_TYPE
    ) condition_type,
    b.branch_condition_type condition_type_code,
    b.BRANCH_CONDITION condition_expression1,
    b.BRANCH_CONDITION_TEXT condition_expression2,
    decode(
      nvl(b.save_state_before_branch_yn, 'N'),
      'N',
      'No',
      'Yes'
    ) save_state_before_branch,
    (
      select
        case
          when b.required_patch > 0 then PATCH_NAME
          else '{Not ' || PATCH_NAME || '}'
        end PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(b.REQUIRED_PATCH)
    ) build_option,
    --
    decode(substr(b.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(b.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      b.SECURITY_SCHEME
    ) authorization_scheme,
    b.SECURITY_SCHEME authorization_scheme_id,
    b.LAST_UPDATED_BY last_updated_by,
    b.LAST_UPDATED_ON last_updated_on,
    b.BRANCH_COMMENT component_comment,
    b.id branch_id,
    b.BRANCH_WHEN_BUTTON_ID branch_when_button_id,
    --
    'Point=' || BRANCH_POINT || ',seq=' || lpad(b.BRANCH_SEQUENCE, 5, '00000') || ',act=' || substr(b.BRANCH_ACTION, 1, 30) || '.' || length(b.BRANCH_ACTION) || ',type=' || decode(
      b.BRANCH_TYPE,
      'BRANCH_TO_FUNCTION_RETURNING_PAGE',
      'Branch to Function Returning a Page',
      'BRANCH_TO_FUNCTION_RETURNING_URL',
      'Branch to Function Returning a URL',
      'BRANCH_TO_PAGE_IDENT_BY_ITEM',
      'Branch to Page Identified by Item (Use Item Name)',
      'BRANCH_TO_PAGE_ACCEPT',
      'Branch to Page Accept Processing (not common)',
      'BRANCH_TO_STEP',
      'Branch to Page',
      'BRANCH_TO_URL_IDENT_BY_ITEM',
      'Branch to URL Identified by Item (Use Item Name)',
      'PLSQL',
      'Branch to PL/SQL Procedure',
      'REDIRECT_URL',
      'Branch to Page or URL',
      b.BRANCH_TYPE
    ) || '.' || decode(
      b.BRANCH_WHEN_BUTTON_ID,
      null,
      null,(
        select
          button_name
        from
          wwv_flow_step_buttons
        where
          id = b.BRANCH_WHEN_BUTTON_ID
        union
        select
          name
        from
          wwv_flow_step_items
        where
          id = b.BRANCH_WHEN_BUTTON_ID
      )
    ) || decode(substr(b.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(b.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      'Not found'
    ) || 'cond=' || nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = b.BRANCH_CONDITION_TYPE
      ),
      b.BRANCH_CONDITION_TYPE
    ) || '.' || substr(b.BRANCH_CONDITION, 1, 20) || '.' || length(b.BRANCH_CONDITION) || '.' || length(b.BRANCH_CONDITION_TEXT) || 'save=' || decode(
      nvl(b.save_state_before_branch_yn, 'N'),
      'N',
      'No',
      'Yes'
    ) || 'build='(
      select
        PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(b.REQUIRED_PATCH)
    ) component_signature
  from
    wwv_flow_step_branches b,
    wwv_flow_steps p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = p.security_group_id
    and f.security_group_id = b.security_group_id
    and f.id = p.flow_id
    and f.id = b.flow_id
    and p.id = b.flow_step_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
columns: []
referencedTables: []
