schema: APEX_050000
name: APEX_APPLICATION_TEMP_LABEL
updatedAllowed: true
insertAllowed: true
columns:
- name: AFTER_ELEMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: AFTER_ITEM
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: AFTER_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: BEFORE_ELEMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: BEFORE_ITEM
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: BEFORE_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 1161
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 1161
- name: DEFAULT_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 255
- name: ERROR_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: HELP_LINK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 3
- name: LABEL_TEMPLATE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 26
  dataTypeLength:
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 22
  dataTypeLength:
- name: ON_ERROR_AFTER_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: ON_ERROR_BEFORE_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: PRESET_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 297
- name: TEMPLATE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 9
  dataTypeLength: 255
- name: THEME_CLASS
  dataType: VARCHAR2
  textMaxLength: 40
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 40
- name: THEME_NUMBER
  dataType: NUMBER
  nullable: true
  ordinalPosition: 5
  dataTypeLength:
- name: TRANSLATE_THIS_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 1
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_FIELD_TEMPLATES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.THEME_ID theme_number,
    decode(
      t.THEME_CLASS_ID,
      '1',
      'Optional Label with Help',
      '2',
      'Required Label with Help',
      '3',
      'Optional Label',
      '4',
      'Required Label',
      '5',
      'Custom 1',
      '6',
      'Custom 2',
      '7',
      'Custom 3',
      '8',
      'Custom 4',
      '9',
      'Custom 5',
      '10',
      'Custom 6',
      '11',
      'Custom 7',
      '12',
      'Custom 8',
      '13',
      'No Label',
      t.THEME_CLASS_ID
    ) theme_class,
    t.default_template_options default_template_options,
    t.preset_template_options preset_template_options,
    --
    t.TEMPLATE_NAME template_name,
    t.TEMPLATE_BODY1 before_label,
    t.TEMPLATE_BODY2 after_label,
    --
    t.BEFORE_ITEM before_item,
    t.AFTER_ITEM after_item,
    --
    t.BEFORE_ELEMENT before_element,
    t.AFTER_ELEMENT after_element,
    t.HELP_LINK help_link,
    t.ERROR_TEMPLATE error_template,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        WWV_FLOW_FIELD_TEMPLATES
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    t.ON_ERROR_BEFORE_LABEL,
    t.ON_ERROR_AFTER_LABEL,
    t.LAST_UPDATED_ON last_updated_on,
    t.LAST_UPDATED_BY last_updated_by,
    t.TRANSLATE_THIS_TEMPLATE,
    t.TEMPLATE_COMMENT component_comment,
    t.id label_template_id,
    --
    t.TEMPLATE_NAME || ' t=' || t.THEME_ID || ' c=' || t.THEME_CLASS_ID || ' 1=' || substr(t.TEMPLATE_BODY1, 1, 40) || length(t.TEMPLATE_BODY1) || ' 2=' || substr(t.TEMPLATE_BODY2, 1, 40) || length(t.TEMPLATE_BODY2) || ' r=' || decode(t.REFERENCE_ID, null, 'N', 'Y') || ' e=' || substr(t.ON_ERROR_BEFORE_LABEL, 1, 40) || length(t.ON_ERROR_BEFORE_LABEL) || ' e=' || substr(t.ON_ERROR_AFTER_LABEL, 1, 40) || length(t.ON_ERROR_AFTER_LABEL) || ' t=' || t.TRANSLATE_THIS_TEMPLATE component_signature
  from
    WWV_FLOW_FIELD_TEMPLATES t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
