schema: APEX_050000
name: APEX_APPLICATION_TEMP_CALENDAR
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.NAME template_name,
    t.LAST_UPDATED_BY,
    t.LAST_UPDATED_ON,
    t.THEME_ID theme_number,
    decode(
      t.THEME_CLASS_ID,
      '1',
      'Calendar',
      '2',
      'Calendar, Alternative 1',
      '3',
      'Small Calendar',
      '4',
      'Custom 1',
      '5',
      'Custom 2',
      '6',
      'Custom 3',
      '7',
      'Custom 4',
      '8',
      'Custom 5',
      '9',
      'Custom 6',
      '10',
      'Custom 7',
      '11',
      'Custom 8',
      t.THEME_CLASS_ID
    ) theme_class,
    --
    decode(
      t.TRANSLATE_THIS_TEMPLATE,
      'Y',
      'Yes',
      'N',
      'No',
      'Yes'
    ) translatable,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        WWV_FLOW_CAL_TEMPLATES
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    t.MONTH_TITLE_FORMAT,
    t.DAY_OF_WEEK_FORMAT,
    t.MONTH_OPEN_FORMAT,
    t.MONTH_CLOSE_FORMAT,
    t.DAY_TITLE_FORMAT,
    t.DAY_OPEN_FORMAT,
    t.DAY_CLOSE_FORMAT,
    t.TODAY_OPEN_FORMAT,
    t.WEEKEND_TITLE_FORMAT,
    t.WEEKEND_OPEN_FORMAT,
    t.WEEKEND_CLOSE_FORMAT,
    t.NONDAY_TITLE_FORMAT,
    t.NONDAY_OPEN_FORMAT,
    t.NONDAY_CLOSE_FORMAT,
    t.WEEK_TITLE_FORMAT,
    t.WEEK_OPEN_FORMAT,
    t.WEEK_CLOSE_FORMAT,
    t.DAILY_TITLE_FORMAT,
    t.DAILY_OPEN_FORMAT,
    t.DAILY_CLOSE_FORMAT,
    t.weekly_title_format,
    t.weekly_day_of_week_format,
    t.weekly_month_open_format,
    t.weekly_month_close_format,
    t.weekly_day_title_format,
    t.weekly_day_open_format,
    t.weekly_day_close_format,
    t.weekly_today_open_format,
    t.weekly_weekend_title_format,
    t.weekly_weekend_open_format,
    t.weekly_weekend_close_format,
    t.weekly_time_open_format,
    t.weekly_time_close_format,
    t.weekly_time_title_format,
    t.weekly_hour_open_format,
    t.weekly_hour_close_format,
    t.daily_day_of_week_format,
    t.daily_month_title_format,
    t.daily_month_open_format,
    t.daily_month_close_format,
    t.daily_day_title_format,
    t.daily_day_open_format,
    t.daily_day_close_format,
    t.daily_today_open_format,
    t.daily_time_open_format,
    t.daily_time_close_format,
    t.daily_time_title_format,
    t.daily_hour_open_format,
    t.daily_hour_close_format,
    t.agenda_format,
    t.agenda_past_day_format,
    t.agenda_today_day_format,
    t.agenda_future_day_format,
    t.agenda_past_entry_format,
    t.agenda_today_entry_format,
    t.agenda_future_entry_format,
    t.month_data_format,
    t.month_data_entry_format,
    t.TEMPLATE_COMMENTS component_comment,
    t.id calendar_template_id,
    --
    t.NAME || ' t=' || t.THEME_ID || ' c=' || t.THEME_CLASS_ID component_signature
  from
    WWV_FLOW_CAL_TEMPLATES t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
