schema: APEX_050000
name: APEX_APPLICATION_PAGE_IR_PIVOT
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    r.page_id page_id,
    r.worksheet_id interactive_report_id,
    p.websheet_id websheet_id,
    r.id report_id,
    r.application_user application_user,
    r.name report_name,
    p.id pivot_id,
    p.pivot_columns,
    p.row_columns,
    p.created_on,
    p.created_by,
    p.updated_on last_updated_on,
    p.updated_by last_updated_by --
  from
    wwv_flow_worksheet_pivot p,
    wwv_flow_worksheet_rpts r,
    wwv_flow_worksheets ws,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = r.security_group_id
    and f.id = ws.flow_id
    and ws.id = r.worksheet_id
    and r.id = p.report_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
