schema: APEX_050000
name: APEX_APPLICATION_PAGE_IR_COND
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: APPLICATION_USER
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: CONDITION_ALLOW_DELETE
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 3
- name: CONDITION_COLUMN_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: CONDITION_DISPLAY
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: CONDITION_ENABLED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 3
- name: CONDITION_EXPRESSION
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION2
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 4000
- name: CONDITION_EXPR_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 255
- name: CONDITION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 10
  dataTypeLength:
- name: CONDITION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 255
- name: CONDITION_OPERATOR
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 30
- name: CONDITION_SQL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: CONDITION_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 255
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 28
  dataTypeLength:
- name: HIGHLIGHT_CELL_COLOR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 255
- name: HIGHLIGHT_CELL_FONT_COLOR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 255
- name: HIGHLIGHT_ROW_COLOR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 255
- name: HIGHLIGHT_ROW_FONT_COLOR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 255
- name: HIGHLIGHT_SEQUENCE
  dataType: NUMBER
  nullable: true
  ordinalPosition: 23
  dataTypeLength:
- name: INTERACTIVE_REPORT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 30
  dataTypeLength:
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 5
  dataTypeLength:
- name: REPORT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 7
  dataTypeLength:
- name: REPORT_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 255
- name: TIME_ZONE
  dataType: VARCHAR2
  textMaxLength: 100
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 100
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEETS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEET_CONDITIONS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEET_RPTS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    r.page_id page_id,
    r.worksheet_id interactive_report_id,
    r.id report_id,
    r.application_user application_user,
    r.name report_name,
    c .id condition_id,
    c .name condition_name,
    decode(
      c .condition_type,
      'FILTER',
      'Filter',
      'HIGHLIGHT',
      'Highlight',
      'SEARCH',
      'Search',
      c .condition_type
    ) condition_type,
    decode(c .allow_delete, 'Y', 'Yes', 'N', 'No', c .allow_delete) condition_allow_delete,
    c .time_zone time_zone,
    -- filter expression
    c .column_name condition_column_name,
    c .operator condition_operator,
    c .expr_type condition_expr_type,
    c .expr condition_expression,
    c .expr2 condition_expression2,
    c .condition_sql condition_sql,
    c .condition_display condition_display,
    -- enabled?
    decode(c .enabled, 'Y', 'Yes', 'N', 'No', c .enabled) condition_enabled,
    -- highlighting settings
    c .highlight_sequence,
    c .row_bg_color highlight_row_color,
    c .row_font_color highlight_row_font_color,
    c .column_bg_color highlight_cell_color,
    c .column_font_color highlight_cell_font_color,
    -- audit
    --
    c .created_on,
    c .created_by,
    c .updated_on last_updated_on,
    c .updated_by last_updated_by --
  from
    wwv_flow_worksheet_conditions c,
    wwv_flow_worksheet_rpts r,
    wwv_flow_worksheets ws,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = r.security_group_id
    and f.id = ws.flow_id
    and ws.id = r.worksheet_id
    and r.id = c .report_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
