schema: APEX_050000
name: APEX_APPLICATION_GROUPS
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    g.ID application_group_id,
    g.group_name group_name,
    g.group_comment group_comment,
    w.PROVISIONING_COMPANY_ID workspace_id
  from
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    wwv_flow_application_groups g,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and w.PROVISIONING_COMPANY_ID != 0
    and w.PROVISIONING_COMPANY_ID = g.security_group_id
  group by
    w.PROVISIONING_COMPANY_ID,
    w.short_name,
    w.display_name,
    w.FIRST_SCHEMA_PROVISIONED,
    g.id,
    g.group_name,
    g.group_comment
