schema: APEX_050000
name: APEX_APPLICATION_COMPUTATIONS
updatedAllowed: true
insertAllowed: true
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    c .COMPUTATION_SEQUENCE computation_sequence,
    c .COMPUTATION_ITEM computation_item,
    c .COMPUTATION_POINT computation_point,
    --c.COMPUTATION_ITEM_TYPE
    c .COMPUTATION_TYPE computation_type,
    --c.COMPUTATION_PROCESSED          computation_processed,
    c .COMPUTATION computation,
    --
    decode(substr(c .SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(c .SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      c .SECURITY_SCHEME
    ) authorization_scheme,
    c .SECURITY_SCHEME authorization_scheme_id,
    --
    nvl(
      (
        select
          case
            when c .required_patch > 0 then PATCH_NAME
            else '{Not ' || PATCH_NAME || '}'
          end PATCH_NAME
        from
          wwv_flow_patches
        where
          id = abs(c .REQUIRED_PATCH)
      ),
      c .REQUIRED_PATCH
    ) build_option,
    --
    nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = c .COMPUTE_WHEN_TYPE
      ),
      c .COMPUTE_WHEN_TYPE
    ) condition_type,
    c .compute_when_type condition_type_code,
    c .COMPUTE_WHEN condition_expression1,
    c .COMPUTE_WHEN_TEXT condition_expression2,
    --
    c .COMPUTATION_ERROR_MESSAGE error_message,
    c .LAST_UPDATED_BY last_updated_by,
    c .LAST_UPDATED_ON last_updated_on,
    c .COMPUTATION_COMMENT component_comment,
    c .id application_computation_id,
    --
    c .COMPUTATION_ITEM || ' seq=' || lpad(c .COMPUTATION_SEQUENCE, 5, '00000') || ' p=' || c .COMPUTATION_POINT || ' t=' || c .COMPUTATION_TYPE || ' c=' || substr(c .COMPUTATION, 1, 50) || length(c .COMPUTATION) || ' s=' || decode(substr(c .SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(c .SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      'Not found'
    ) || ' c=' || c .COMPUTE_WHEN_TYPE || substr(c .COMPUTE_WHEN, 1, 30) || length(c .COMPUTE_WHEN) || substr(c .COMPUTE_WHEN_TEXT, 1, 30) || length(c .COMPUTE_WHEN_TEXT) || ' m=' || substr(c .COMPUTATION_ERROR_MESSAGE, 1, 30) || length(c .COMPUTATION_ERROR_MESSAGE) component_signature
  from
    wwv_flow_computations c,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = c .flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
columns: []
referencedTables: []
