schema: APEX_050000
name: APEX_APPLICATION_TEMP_REPORT
updatedAllowed: true
insertAllowed: true
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.ROW_TEMPLATE_NAME template_name,
    decode(
      t.ROW_TEMPLATE_TYPE,
      'GENERIC_COLUMNS',
      'Generic Columns (column template)',
      'NAMED_COLUMNS',
      'Named Column (row template)',
      t.ROW_TEMPLATE_TYPE
    ) template_type,
    --
    t.before_column_heading,
    t.COLUMN_HEADING_TEMPLATE,
    t.column_heading_sort_asc_temp,
    t.column_heading_sort_desc_temp,
    t.column_heading_sort_temp,
    t.after_column_heading,
    t.ROW_TEMPLATE1 col_TEMPLATE1,
    t.ROW_TEMPLATE_CONDITION1 col_TEMPLATE_CONDITION1,
    t.ROW_TEMPLATE_DISPLAY_COND1 col_TEMPLATE_DISPLAY_COND1,
    t.ROW_TEMPLATE2 col_TEMPLATE2,
    t.ROW_TEMPLATE_CONDITION2 col_TEMPLATE_CONDITION2,
    t.ROW_TEMPLATE_DISPLAY_COND2 col_TEMPLATE_DISPLAY_COND2,
    t.ROW_TEMPLATE3 col_TEMPLATE3,
    t.ROW_TEMPLATE_CONDITION3 col_TEMPLATE_CONDITION3,
    t.ROW_TEMPLATE_DISPLAY_COND3 col_TEMPLATE_DISPLAY_COND3,
    t.ROW_TEMPLATE4 col_TEMPLATE4,
    t.ROW_TEMPLATE_CONDITION4 col_TEMPLATE_CONDITION4,
    t.ROW_TEMPLATE_DISPLAY_COND4 col_TEMPLATE_DISPLAY_COND4,
    t.ROW_TEMPLATE_BEFORE_ROWS col_TEMPLATE_BEFORE_ROWS,
    t.ROW_TEMPLATE_AFTER_ROWS col_TEMPLATE_AFTER_ROWS,
    t.ROW_TEMPLATE_BEFORE_FIRST col_TEMPLATE_BEFORE_FIRST,
    t.ROW_TEMPLATE_AFTER_LAST col_TEMPLATE_AFTER_LAST,
    --t.ROW_TEMPLATE_TABLE_ATTRIBUTES  col_TEMPLATE_TABLE_ATTRIBUTES,
    t.PAGINATION_TEMPLATE,
    t.NEXT_PAGE_TEMPLATE,
    t.PREVIOUS_PAGE_TEMPLATE,
    t.NEXT_SET_TEMPLATE,
    t.PREVIOUS_SET_TEMPLATE,
    t.ROW_STYLE_MOUSE_OVER,
    --t.ROW_STYLE_MOUSE_OUT            ,
    t.ROW_STYLE_CHECKED,
    --t.ROW_STYLE_UNCHECKED            ,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        WWV_FLOW_ROW_TEMPLATES
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    t.LAST_UPDATED_BY,
    t.LAST_UPDATED_ON,
    t.THEME_ID theme_number,
    --
    decode(
      t.THEME_CLASS_ID,
      '1',
      'Borderless',
      '2',
      'Horizontal Border',
      '3',
      'One Column Unordered List',
      '4',
      'Standard',
      '5',
      'Standard, Alternating Row Colors',
      '6',
      'Value Attribute Pairs',
      '7',
      'Custom 1',
      '8',
      'Custom 2',
      '9',
      'Custom 3',
      '10',
      'Custom 4',
      '11',
      'Custom 5',
      '12',
      'Custom 6',
      '13',
      'Custom 7',
      '14',
      'Custom 8',
      t.THEME_CLASS_ID
    ) theme_class,
    t.default_template_options default_template_options,
    t.preset_template_options preset_template_options,
    decode(
      t.TRANSLATE_THIS_TEMPLATE,
      'Y',
      'Yes',
      'N',
      'No',
      'Yes'
    ) translate_this_template,
    t.ROW_TEMPLATE_COMMENT component_comment,
    --
    t.ROW_TEMPLATE_NAME || ' t=' || t.THEME_ID || ' c=' || t.THEME_CLASS_ID || ' t=' || t.ROW_TEMPLATE_TYPE || ' 1=' || sys.dbms_lob.substr(t.ROW_TEMPLATE1, 1, 40) || sys.dbms_lob.getlength(t.ROW_TEMPLATE1) || ' c=' || substr(t.ROW_TEMPLATE_CONDITION1, 1, 20) || length(t.ROW_TEMPLATE_CONDITION1) || ' c=' || substr(t.ROW_TEMPLATE_DISPLAY_COND1, 1, 20) || length(t.ROW_TEMPLATE_DISPLAY_COND1) || ' 2=' || sys.dbms_lob.substr(t.ROW_TEMPLATE2, 1, 40) || sys.dbms_lob.getlength(t.ROW_TEMPLATE2) || ' c=' || substr(t.ROW_TEMPLATE_CONDITION2, 1, 20) || length(t.ROW_TEMPLATE_CONDITION2) || ' c=' || substr(t.ROW_TEMPLATE_DISPLAY_COND2, 1, 20) || length(t.ROW_TEMPLATE_DISPLAY_COND2) || ' 3=' || sys.dbms_lob.substr(t.ROW_TEMPLATE3, 1, 40) || sys.dbms_lob.getlength(t.ROW_TEMPLATE3) || ' c=' || substr(t.ROW_TEMPLATE_CONDITION3, 1, 20) || length(t.ROW_TEMPLATE_CONDITION3) || ' c=' || substr(t.ROW_TEMPLATE_DISPLAY_COND3, 1, 20) || length(t.ROW_TEMPLATE_DISPLAY_COND3) || ' 4=' || sys.dbms_lob.substr(t.ROW_TEMPLATE4, 1, 40) || sys.dbms_lob.getlength(t.ROW_TEMPLATE4) || decode(t.REFERENCE_ID, null, 'N', 'Y') component_signature,
    t.id template_id
  from
    WWV_FLOW_ROW_TEMPLATES t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
columns: []
referencedTables: []
