schema: APEX_050000
name: APEX_APPLICATION_NAV_BAR
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: AUTHORIZATION_SCHEME
  dataType: VARCHAR2
  textMaxLength: 259
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 259
- name: AUTHORIZATION_SCHEME_ID
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 255
- name: BEGINS_ON_NEW_LINE
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 30
- name: BUILD_OPTION
  dataType: VARCHAR2
  textMaxLength: 261
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 261
- name: CELL_COLUMN_SPAN
  dataType: NUMBER
  nullable: true
  ordinalPosition: 7
  dataTypeLength:
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 2106
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 2106
- name: CONDITION_EXPRESSION1
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION2
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: CONDITION_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 255
- name: CONDITION_TYPE_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 255
- name: DISPLAY_SEQUENCE
  dataType: NUMBER
  nullable: false
  ordinalPosition: 5
  dataTypeLength:
- name: ICON_HEIGHT
  dataType: NUMBER
  nullable: true
  ordinalPosition: 12
  dataTypeLength:
- name: ICON_IMAGE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: ICON_IMAGE_ALT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: ICON_SUBTEXT
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 255
- name: ICON_TARGET
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: ICON_WIDTH
  dataType: NUMBER
  nullable: true
  ordinalPosition: 13
  dataTypeLength:
- name: IS_FEEDBACK_LINK
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 3
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 25
  dataTypeLength:
- name: NAV_BAR_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 27
  dataTypeLength:
- name: ONCLICK_JAVASCRIPT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: REFERENCED_NAV_BAR_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 29
  dataTypeLength:
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 297
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: APEX_STANDARD_CONDITIONS
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_ICON_BAR
- schema: APEX_050000
  name: WWV_FLOW_PATCHES
- schema: APEX_050000
  name: WWV_FLOW_SECURITY_SCHEMES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    n.ICON_SEQUENCE display_sequence,
    decode(
      n.BEGINS_ON_NEW_LINE,
      'YES',
      'Yes',
      'NO',
      'No',
      n.BEGINS_ON_NEW_LINE
    ) begins_on_new_line,
    n.CELL_COLSPAN cell_column_span,
    --
    n.ICON_IMAGE,
    --n.ICON_IMAGE2                    ,
    --n.ICON_IMAGE3                    ,
    n.ICON_SUBTEXT,
    --n.ICON_SUBTEXT2                  ,
    --n.ICON_SUBTEXT3                  ,
    n.ICON_TARGET,
    n.ICON_IMAGE_ALT,
    n.ICON_HEIGHT,
    n.ICON_WIDTH,
    --n.ICON_HEIGHT2                   ,
    --n.ICON_WIDTH2                    ,
    --n.ICON_HEIGHT3                   ,
    --n.ICON_WIDTH3                    ,
    --
    nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = n.ICON_BAR_DISP_COND_TYPE
      ),
      n.ICON_BAR_DISP_COND_TYPE
    ) condition_type,
    n.icon_bar_disp_cond_type condition_type_code,
    n.ICON_BAR_DISP_COND condition_expression1,
    n.ICON_BAR_FLOW_COND_INSTR condition_expression2,
    --
    n.ONCLICK onclick_javascript,
    --
    (
      select
        case
          when n.required_patch > 0 then PATCH_NAME
          else '{Not ' || PATCH_NAME || '}'
        end PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(n.REQUIRED_PATCH)
    ) build_option,
    --
    decode(substr(n.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(n.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      n.SECURITY_SCHEME
    ) authorization_scheme,
    n.SECURITY_SCHEME authorization_scheme_id,
    --
    decode(n.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name n
      from
        wwv_flow_icon_bar
      where
        id = n.reference_id
    ) subscribed_from,
    --
    n.LAST_UPDATED_BY last_updated_by,
    n.LAST_UPDATED_ON last_updated_on,
    n.ICON_BAR_COMMENT component_comment,
    n.id nav_bar_id,
    decode(n.nav_entry_is_feedback_yn, 'Y', 'Yes', 'No') is_feedback_link,
    n.REFERENCE_ID referenced_nav_bar_id,
    --
    lpad(n.ICON_SEQUENCE, 5, '00000') || decode(
      n.BEGINS_ON_NEW_LINE,
      'YES',
      'Yes',
      'NO',
      'No',
      n.BEGINS_ON_NEW_LINE
    ) || n.CELL_COLSPAN || ' img=' || n.ICON_IMAGE || ' ' || substr(n.ICON_SUBTEXT, 1, 30) || length(n.ICON_SUBTEXT) || ' t=' || substr(n.ICON_TARGET, 1, 30) || length(n.ICON_TARGET) || ' a=' || substr(n.ICON_IMAGE_ALT, 1, 20) || length(n.ICON_IMAGE_ALT) || n.ICON_HEIGHT || n.ICON_WIDTH || ' c=' || n.ICON_BAR_DISP_COND_TYPE || substr(n.ICON_BAR_DISP_COND, 1, 30) || length(n.ICON_BAR_DISP_COND) || substr(n.ICON_BAR_FLOW_COND_INSTR, 1, 30) || length(n.ICON_BAR_FLOW_COND_INSTR) || ' ck=' || substr(n.ONCLICK, 1, 20) || length(n.onclick) || ' bo=' || (
      select
        PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(n.REQUIRED_PATCH)
    ) || ' a=' || decode(substr(n.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(n.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      'Not found'
    ) || ' s=' || decode(n.REFERENCE_ID, null, 'No', 'Yes') component_signature
  from
    wwv_flow_icon_bar n,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = n.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
