schema: APEX_050000
name: APEX_APPLICATION_BUILD_OPTIONS
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    b.PATCH_NAME build_option_name,
    decode(
      b.PATCH_STATUS,
      'INCLUDE',
      'Include',
      'EXCLUDE',
      'Exclude',
      b.patch_status
    ) build_option_status,
    decode(
      nvl(b.DEFAULT_ON_EXPORT, b.patch_status),
      'INCLUDE',
      'Include',
      'EXCLUDE',
      'Exclude',
      b.DEFAULT_ON_EXPORT
    ) status_on_export,
    --b.ATTRIBUTE1                   attribute1,
    --b.ATTRIBUTE2                   attribute2,
    --b.ATTRIBUTE3                   attribute3,
    --b.ATTRIBUTE4                   attribute4,
    b.LAST_UPDATED_BY last_updated_by,
    b.LAST_UPDATED_ON last_updated_on,
    b.PATCH_COMMENT component_comment,
    b.id build_option_id,
    --
    b.PATCH_NAME || ' s=' || decode(
      b.PATCH_STATUS,
      'INCLUDE',
      'Include',
      'EXCLUDE',
      'Exclude',
      b.patch_status
    ) || ' e=' || decode(
      nvl(b.DEFAULT_ON_EXPORT, b.patch_status),
      'INCLUDE',
      'Include',
      'EXCLUDE',
      'Exclude',
      b.DEFAULT_ON_EXPORT
    ) component_signature
  from
    wwv_flow_patches b,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = b.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
