schema: APEX_050000
name: APEX_APPLICATION_PROCESSES
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    p.PROCESS_SEQUENCE process_sequence,
    --
    decode(
      p.PROCESS_POINT,
      'BEFORE_HEADER',
      'On Load: Before Header (page template header)',
      'AFTER_HEADER',
      'On Load: After Header (page template header)',
      'BEFORE_BOX_BODY',
      'On Load: Before Body Region(s)',
      'AFTER_BOX_BODY',
      'On Load: After Body Region(s)',
      'BEFORE_FOOTER',
      'On Load: Before Footer (page template footer)',
      'AFTER_FOOTER',
      'On Load: After Footer (page template footer)',
      'ON_SUBMIT_BEFORE_COMPUTATION',
      'On Submit: After Page Submission - Before Computations and Validations',
      'AFTER_SUBMIT',
      'On Submit: After Page Submission - After Computations and Validations',
      'ON_NEW_INSTANCE',
      'On New Session: After Authentication',
      'AFTER_LOGIN',
      'After Login',
      'ON_DEMAND',
      'On Demand: Run this application process when requested by a page process',
      p.process_point
    ) process_point,
    --
    decode(
      p.PROCESS_TYPE,
      'NATIVE_PLSQL',
      'PL/SQL Anonymous Block',
      p.PROCESS_TYPE
    ) process_type,
    decode(
      p.PROCESS_TYPE,
      'NATIVE_PLSQL',
      'PLSQL',
      p.PROCESS_TYPE
    ) process_type_code,
    p.process_type process_type_plugin_name,
    --
    p.PROCESS_NAME process_name,
    p.PROCESS_SQL_CLOB process,
    p.attribute_01,
    p.attribute_02,
    p.attribute_03,
    p.attribute_04,
    p.attribute_05,
    p.attribute_06,
    p.attribute_07,
    p.attribute_08,
    p.attribute_09,
    p.attribute_10,
    p.attribute_11,
    p.attribute_12,
    p.attribute_13,
    p.attribute_14,
    p.attribute_15,
    p.PROCESS_ERROR_MESSAGE error_message,
    p.error_display_location error_display_location,
    --
    nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = p.PROCESS_WHEN_TYPE
      ),
      p.PROCESS_WHEN_TYPE
    ) condition_type,
    p.process_when_type condition_type_code,
    p.PROCESS_WHEN condition_expression1,
    p.PROCESS_WHEN2 condition_expression2,
    --p.PROCESS_WHEN_TYPE2             ,
    --p.ITEM_NAME                      ,
    nvl(
      (
        select
          case
            when p.required_patch > 0 then PATCH_NAME
            else '{Not ' || PATCH_NAME || '}'
          end PATCH_NAME
        from
          wwv_flow_patches
        where
          id = abs(p.REQUIRED_PATCH)
      ),
      p.REQUIRED_PATCH
    ) build_option,
    --
    decode(substr(p.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(p.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      p.SECURITY_SCHEME
    ) authorization_scheme,
    p.SECURITY_SCHEME authorization_scheme_id,
    p.LAST_UPDATED_BY last_updated_by,
    p.LAST_UPDATED_ON last_updated_on,
    p.PROCESS_COMMENT component_comment,
    p.id application_process_id,
    --
    p.PROCESS_NAME || ' seq=' || lpad(p.PROCESS_SEQUENCE, 5, '00000') || ' ' || p.PROCESS_POINT || ' ' || decode(
      p.PROCESS_TYPE,
      'PLSQL',
      'PL/SQL Anonymous Block',
      p.PROCESS_TYPE
    ) || ' txt=' || sys.dbms_lob.substr(p.PROCESS_SQL_CLOB, 50, 1) || sys.dbms_lob.getlength(p.PROCESS_SQL_CLOB) || ' m=' || substr(p.PROCESS_ERROR_MESSAGE, 1, 30) || length(p.PROCESS_ERROR_MESSAGE) || ' cond=' || p.PROCESS_WHEN_TYPE || substr(p.PROCESS_WHEN, 1, 20) || length(p.PROCESS_WHEN) || substr(p.PROCESS_WHEN2, 1, 20) || length(p.PROCESS_WHEN2) || ' b=' || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = abs(p.REQUIRED_PATCH)
          and flow_id = f.id
      ),
      p.REQUIRED_PATCH
    ) || ' s=' || decode(substr(p.SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(p.SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      'Not found'
    ) component_signature
  from
    wwv_flow_processing p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and f.id = p.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
