schema: APEX_050000
name: APEX_APPLICATION_PAGE_REG_COLS
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 4
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: ATTRIBUTE_01
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: ATTRIBUTE_02
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: ATTRIBUTE_03
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 4000
- name: ATTRIBUTE_04
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 4000
- name: ATTRIBUTE_05
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: ATTRIBUTE_06
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: ATTRIBUTE_07
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 4000
- name: ATTRIBUTE_08
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 4000
- name: ATTRIBUTE_09
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 4000
- name: ATTRIBUTE_10
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 4000
- name: ATTRIBUTE_11
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: ATTRIBUTE_12
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 4000
- name: ATTRIBUTE_13
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 4000
- name: ATTRIBUTE_14
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 4000
- name: ATTRIBUTE_15
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 4000
- name: ATTRIBUTE_16
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 4000
- name: ATTRIBUTE_17
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 4000
- name: ATTRIBUTE_18
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 4000
- name: ATTRIBUTE_19
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 38
  dataTypeLength: 4000
- name: ATTRIBUTE_20
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 39
  dataTypeLength: 4000
- name: ATTRIBUTE_21
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 40
  dataTypeLength: 4000
- name: ATTRIBUTE_22
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 41
  dataTypeLength: 4000
- name: ATTRIBUTE_23
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 42
  dataTypeLength: 4000
- name: ATTRIBUTE_24
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 4000
- name: ATTRIBUTE_25
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 44
  dataTypeLength: 4000
- name: AUTHORIZATION_SCHEME
  dataType: VARCHAR2
  textMaxLength: 259
  nullable: true
  ordinalPosition: 50
  dataTypeLength: 259
- name: AUTHORIZATION_SCHEME_ID
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 51
  dataTypeLength: 255
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 52
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION1
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 48
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION2
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 49
  dataTypeLength: 4000
- name: CONDITION_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 46
  dataTypeLength: 255
- name: CONDITION_TYPE_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 47
  dataTypeLength: 255
- name: DATA_TYPE
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 11
  dataTypeLength: 128
- name: DISPLAY_SEQUENCE
  dataType: NUMBER
  nullable: false
  ordinalPosition: 13
  dataTypeLength:
- name: ESCAPE_ON_HTTP_OUTPUT
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 3
- name: FORMAT_MASK
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 255
- name: HEADING
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 255
- name: HEADING_ALIGNMENT
  dataType: VARCHAR2
  textMaxLength: 6
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 6
- name: IS_VISIBLE
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 53
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 54
  dataTypeLength:
- name: NAME
  dataType: VARCHAR2
  textMaxLength: 128
  nullable: false
  ordinalPosition: 10
  dataTypeLength: 128
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: PAGE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 7
  dataTypeLength: 255
- name: REGION_COLUMN_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 1
  dataTypeLength:
- name: REGION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 8
  dataTypeLength:
- name: REGION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 9
  dataTypeLength: 255
- name: VALUE_ALIGNMENT
  dataType: VARCHAR2
  textMaxLength: 6
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 6
- name: VALUE_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 255
- name: VALUE_CSS_CLASSES
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 2
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 3
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: APEX_STANDARD_CONDITIONS
- schema: APEX_050000
  name: WWV_FLOW_AUTHORIZED
- schema: APEX_050000
  name: WWV_FLOW_PAGE_PLUGS
- schema: APEX_050000
  name: WWV_FLOW_REGION_COLUMNS
- schema: APEX_050000
  name: WWV_FLOW_SECURITY_SCHEMES
- schema: APEX_050000
  name: WWV_FLOW_STEPS
viewDefinition: |-
  select
    c .id as region_column_id,
    f.workspace,
    f.workspace_display_name,
    f.application_id,
    f.application_name,
    c .page_id,
    p.name as page_name,
    c .region_id,
    r.plug_name as region_name,
    c .name,
    c .data_type,
    case
      c .is_visible
      when 'Y' then 'Yes'
      else 'No'
    end as is_visible,
    c .display_sequence,
    c .heading,
    c .heading_alignment,
    c .value_alignment,
    c .value_css_classes,
    c .value_attributes,
    c .format_mask,
    c .attribute_01,
    c .attribute_02,
    c .attribute_03,
    c .attribute_04,
    c .attribute_05,
    c .attribute_06,
    c .attribute_07,
    c .attribute_08,
    c .attribute_09,
    c .attribute_10,
    c .attribute_11,
    c .attribute_12,
    c .attribute_13,
    c .attribute_14,
    c .attribute_15,
    c .attribute_16,
    c .attribute_17,
    c .attribute_18,
    c .attribute_19,
    c .attribute_20,
    c .attribute_21,
    c .attribute_22,
    c .attribute_23,
    c .attribute_24,
    c .attribute_25,
    case
      c .escape_on_http_output
      when 'Y' then 'Yes'
      when 'N' then 'No'
      else c .escape_on_http_output
    end as escape_on_http_output,
    coalesce (
      (
        select
          r
        from
          apex_standard_conditions
        where
          c .display_condition_type is not null
          and d = c .display_condition_type
      ),
      c .display_condition_type
    ) as condition_type,
    c .display_condition_type as condition_type_code,
    c .display_condition as condition_expression1,
    c .display_condition2 as condition_expression2,
    case
      when substr(c .security_scheme, 1, 1) = '!' then 'Not '
    end || coalesce (
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(c .security_scheme, '!')
          and flow_id = c .flow_id
      ),
      c .security_scheme
    ) as authorization_scheme,
    c .security_scheme as authorization_scheme_id,
    c .column_comment as component_comment,
    c .last_updated_by,
    c .last_updated_on
  from
    wwv_flow_authorized f,
    wwv_flow_region_columns c,
    wwv_flow_page_plugs r,
    wwv_flow_steps p
  where
    c .flow_id = f.application_id
    and c .security_group_id = f.workspace_id
    and r.id = c .region_id
    and r.security_group_id = c .security_group_id
    and p.flow_id = c .flow_id
    and p.id = c .page_id
    and p.security_group_id = c .security_group_id
