schema: APEX_050000
name: APEX_APPLICATION_LOCKED_PAGES
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 4
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: LOCKED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 255
- name: LOCKED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 10
  dataTypeLength:
- name: LOCK_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 4000
- name: LOCK_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 1
  dataTypeLength:
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: PAGE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 7
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 2
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 3
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOW_AUTHORIZED
- schema: APEX_050000
  name: WWV_FLOW_LOCK_PAGE
- schema: APEX_050000
  name: WWV_FLOW_STEPS
viewDefinition: |-
  select
    l.id as lock_id,
    f.workspace,
    f.workspace_display_name,
    f.application_id,
    f.application_name,
    p.id as page_id,
    p.name as page_name,
    l.lock_comment,
    l.locked_by,
    l.locked_on
  from
    wwv_flow_authorized f,
    wwv_flow_lock_page l,
    wwv_flow_steps p
  where
    l.flow_id = f.application_id
    and l.security_group_id = f.workspace_id
    and p.id = l.object_id
    and p.flow_id = l.flow_id
    and p.security_group_id = l.security_group_id
