schema: APEX_050000
name: APEX_APPLICATION_TRANS_DYNAMIC
updatedAllowed: true
insertAllowed: true
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.security_group_id workspace_id,
    f.id application_id,
    f.name application_name,
    --
    t.id message_id,
    t.translate_from_text from_message,
    t.translate_to_text to_message,
    t.translate_to_lang_code language_code,
    t.last_updated_by last_updated_by,
    t.last_updated_on last_updated_on
  from
    wwv_flow_dynamic_translations$ t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    /* keep this not exists */
    and not exists (
      select
        1
      from
        wwv_flow_language_map m
      where
        m.translation_flow_id = f.id
        and m.security_group_id = f.security_group_id
        and f.authentication_id <> trunc(f.authentication_id)
    )
    and w.PROVISIONING_COMPANY_ID != 0
columns: []
referencedTables: []
