schema: APEX_050000
name: APEX_APPLICATION_PAGE_COMP
updatedAllowed: true
insertAllowed: true
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    p.flow_id application_id,
    f.name application_name,
    p.id page_id,
    p.name page_name,
    --
    c .COMPUTATION_ITEM item_name,
    c .COMPUTATION_SEQUENCE execution_sequence,
    --
    decode(
      c .COMPUTATION_POINT,
      'ON_NEW_INSTANCE',
      'On New Instance (e.g. On Login)',
      'BEFORE_HEADER',
      'Before Header',
      'AFTER_HEADER',
      'After Header',
      'BEFORE_BOX_BODY',
      'Before Region(s)',
      'AFTER_BOX_BODY',
      'After Region(s)',
      'BEFORE_FOOTER',
      'Before Footer',
      'AFTER_FOOTER',
      'After Footer',
      'AFTER_SUBMIT',
      'After Submit',
      c .COMPUTATION_POINT
    ) computation_point,
    --
    decode(
      c .COMPUTATION_TYPE,
      'STATIC_ASSIGNMENT',
      'Static Assignment',
      'FUNCTION_BODY',
      'PL/SQL Function Body',
      'QUERY',
      'SQL Query (return single value)',
      'QUERY_COLON',
      'SQL Query (return colon separated value)',
      'SQL_EXPRESSION',
      'SQL Expression',
      'PLSQL_EXPRESSION',
      'PL/SQL Expression',
      'ITEM_VALUE',
      'Item Value',
      c .COMPUTATION_TYPE
    ) computation_type,
    --c.COMPUTATION_PROCESSED        computation_processed,
    c .COMPUTATION computation,
    --
    decode(
      c .COMPUTE_WHEN_TYPE,
      '%' || 'null%',
      null,
      nvl(
        (
          select
            r
          from
            apex_standard_conditions
          where
            d = c .COMPUTE_WHEN_TYPE
        ),
        c .COMPUTE_WHEN_TYPE
      )
    ) condition_type,
    c .compute_when_type condition_type_code,
    c .COMPUTE_WHEN condition_expression1,
    c .COMPUTE_WHEN_TEXT condition_expression2,
    c .COMPUTATION_ERROR_MESSAGE error_message,
    (
      select
        case
          when c .required_patch > 0 then PATCH_NAME
          else '{Not ' || PATCH_NAME || '}'
        end PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(c .REQUIRED_PATCH)
    ) build_option,
    --
    decode(substr(c .SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(c .SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      c .SECURITY_SCHEME
    ) authorization_scheme,
    c .SECURITY_SCHEME authorization_scheme_id,
    c .LAST_UPDATED_BY last_updated_by,
    c .LAST_UPDATED_ON last_updated_on,
    c .COMPUTATION_COMMENT component_comment,
    --
    c .COMPUTATION_ITEM || c .COMPUTATION_SEQUENCE || c .COMPUTATION_POINT || c .COMPUTATION_TYPE || length(c .COMPUTATION) || c .COMPUTE_WHEN_TYPE || length(c .COMPUTE_WHEN) || length(c .COMPUTE_WHEN_TEXT) || length(c .COMPUTATION_ERROR_MESSAGE)(
      select
        case
          when c .required_patch > 0 then PATCH_NAME
          else '{Not ' || PATCH_NAME || '}'
        end PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(c .REQUIRED_PATCH)
    ) || decode(substr(c .SECURITY_SCHEME, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(c .SECURITY_SCHEME, '!')
          and flow_id = f.id
      ),
      'Not found'
    ) component_signature,
    --
    c .id computation_id
  from
    wwv_flow_step_computations c,
    wwv_flow_steps p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = p.security_group_id
    and f.security_group_id = c .security_group_id
    and f.id = p.flow_id
    and f.id = c .flow_id
    and p.id = c .flow_step_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
columns: []
referencedTables: []
