schema: APEX_050000
name: APEX_APPLICATION_LOVS
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 436
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 436
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 12
  dataTypeLength:
- name: LIST_OF_VALUES_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: LIST_OF_VALUES_QUERY
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 4000
- name: LOV_ENTRIES
  dataType: NUMBER
  nullable: true
  ordinalPosition: 8
  dataTypeLength:
- name: LOV_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 14
  dataTypeLength:
- name: LOV_TYPE
  dataType: VARCHAR2
  textMaxLength: 7
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 7
- name: REFERENCED_LOV_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 15
  dataTypeLength:
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 297
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_LISTS_OF_VALUES$
- schema: APEX_050000
  name: WWV_FLOW_LIST_OF_VALUES_DATA
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    l.LOV_NAME list_of_values_name,
    --
    decode(
      substr(l.lov_query, 1, 1),
      '.',
      'Static',
      'Dynamic'
    ) lov_type,
    decode(
      substr(l.lov_query, 1, 1),
      '.',
      null,
      l.LOV_QUERY
    ) list_of_values_query,
    (
      select
        count(*)
      from
        wwv_flow_list_of_values_data
      where
        flow_id = f.id
        and lov_id = l.id
    ) lov_entries,
    --
    decode(l.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name n
      from
        wwv_flow_lists_of_values$
      where
        id = l.reference_id
    ) subscribed_from,
    --
    l.LAST_UPDATED_BY last_updated_by,
    l.LAST_UPDATED_ON last_updated_on,
    l.LOV_COMMENT component_comment,
    --
    l.ID lov_id,
    l.REFERENCE_ID referenced_lov_id,
    --
    l.LOV_NAME || ' t=' || decode(substr(l.lov_query, 1, 1), '.', 'Static', 'Dynamic') || ' q=' || decode(
      substr(l.lov_query, 1, 1),
      '.',
      null,
      substr(l.LOV_QUERY, 1, 30) || length(l.LOV_QUERY)
    ) || ' ref=' || decode(l.REFERENCE_ID, null, 'No', 'Yes') component_signature
  from
    wwv_flow_lists_of_values$ l,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = l.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
