schema: APEX_050000
name: APEX_APPLICATION_THEMES
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.theme_id theme_number,
    t.theme_name theme_name,
    t.ui_type_id,
    uit.name ui_type_name,
    t.reference_id,
    case
      t.navigation_type
      when 'T' then 'Tabs'
      when 'L' then 'Navigation Menu List'
    end as navigation_type,
    t.navigation_type as navigation_type_code,
    t.default_nav_list_position,
    case
      t.nav_bar_type
      when 'NAVBAR' then 'Navigation Bar'
      when 'LIST' then 'List'
    end as nav_bar_type,
    t.nav_bar_type as nav_bar_type_code,
    t.is_locked,
    case
      when exists (
        select
          1
        from
          wwv_flow_user_interfaces ui
        where
          ui.flow_id = t.flow_id
          and ui.theme_id = t.theme_id
      ) then 'Yes'
      else 'No'
    end as is_current,
    (
      select
        name
      from
        wwv_flow_templates
      where
        id = t.default_page_template
    ) default_page_template,
    --t.error_template                   ,
    --t.printer_friendly_template        ,
    --t.breadcrumb_display_point         ,
    --t.sidebar_display_point,
    --t.login_template                   ,
    (
      select
        template_name
      from
        wwv_flow_button_templates
      where
        id = t.default_button_template
    ) default_button_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_region_template
    ) default_region_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_chart_template
    ) default_chart_rg_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_form_template
    ) default_form_rg_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_reportr_template
    ) default_report_region_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_tabform_template
    ) default_tabular_form_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_wizard_template
    ) default_wizard_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_menur_template
    ) default_breadcrumb_rg_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_listr_template
    ) default_list_region_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_irr_template
    ) default_irr_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_header_template
    ) default_header_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_footer_template
    ) default_footer_template,
    (
      select
        row_template_name
      from
        wwv_flow_row_templates
      where
        id = t.default_report_template
    ) default_report_row_template,
    (
      select
        template_Name
      from
        wwv_flow_field_templates
      where
        id = t.default_label_template
    ) default_item_label_template,
    (
      select
        name
      from
        wwv_flow_menu_templates
      where
        id = t.default_menu_template
    ) default_breadcrumb_template,
    (
      select
        name
      from
        wwv_flow_cal_templates
      where
        id = t.default_calendar_template
    ) default_calendar_template,
    (
      select
        list_template_name
      from
        wwv_flow_list_templates
      where
        id = t.default_list_template
    ) default_list_template,
    (
      select
        list_template_name
      from
        wwv_flow_list_templates
      where
        id = t.default_nav_list_template
    ) default_nav_list_template,
    (
      select
        list_template_name
      from
        wwv_flow_list_templates
      where
        id = t.default_top_nav_list_template
    ) default_top_nav_list_template,
    (
      select
        list_template_name
      from
        wwv_flow_list_templates
      where
        id = t.default_side_nav_list_template
    ) default_side_nav_list_template,
    (
      select
        template_name
      from
        wwv_flow_field_templates
      where
        id = t.default_option_label
    ) default_option_label,
    (
      select
        template_name
      from
        wwv_flow_field_templates
      where
        id = t.default_required_label
    ) default_required_label,
    (
      select
        list_template_name
      from
        wwv_flow_list_templates
      where
        id = t.default_nav_bar_list_template
    ) default_nav_bar_list_template,
    --
    (
      select
        name
      from
        wwv_flow_templates
      where
        id = t.default_dialog_template
    ) default_dialog_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_dialogr_template
    ) default_dialogr_template,
    (
      select
        page_plug_template_name
      from
        wwv_flow_page_plug_templates
      where
        id = t.default_dialogbtnr_template
    ) default_dialogbtnr_template,
    --
    t.default_page_transition,
    t.default_popup_transition,
    --
    t.last_updated_on last_updated_on,
    t.last_updated_by last_updated_by,
    t.calendar_icon calendar_icon_image_name,
    t.calendar_icon_attr calendar_icon_attributes,
    t.custom_icon_classes,
    t.custom_icon_prefix_class,
    t.custom_library_file_urls,
    t.icon_library,
    t.javascript_file_urls,
    t.css_file_urls,
    t.id theme_id,
    t.theme_description theme_description,
    t.file_prefix,
    t.files_version,
    --
    t.theme_id || ' n=' || substr(
      t.theme_name,
      1,
      30
    ) || ' p=' || substr(
      (
        select
          name
        from
          wwv_flow_templates
        where
          id = t.default_page_template
      ),
      1,
      30
    ) || ' e=' || substr(
      (
        select
          name
        from
          wwv_flow_templates
        where
          id = t.error_template
      ),
      1,
      30
    ) || ' b=' || substr(
      (
        select
          template_name
        from
          wwv_flow_button_templates
        where
          id = t.default_button_template
      ),
      1,
      30
    ) || ' r=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_region_template
      ),
      1,
      30
    ) || ' c=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_chart_template
      ),
      1,
      30
    ) || ' f=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_form_template
      ),
      1,
      30
    ) || ' r=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_reportr_template
      ),
      1,
      30
    ) || ' t=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_tabform_template
      ),
      1,
      30
    ) || ' w=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_wizard_template
      ),
      1,
      30
    ) || ' b=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_menur_template
      ),
      1,
      30
    ) || ' l=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_listr_template
      ),
      1,
      30
    ) || ' i=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_irr_template
      ),
      1,
      30
    ) || ' h=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_header_template
      ),
      1,
      30
    ) || ' f=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_footer_template
      ),
      1,
      30
    ) || ' r=' || substr(
      (
        select
          row_template_name
        from
          wwv_flow_row_templates
        where
          id = t.default_report_template
      ),
      1,
      30
    ) || ' i=' || substr(
      (
        select
          template_Name
        from
          wwv_flow_field_templates
        where
          id = t.default_label_template
      ),
      1,
      30
    ) || ' b=' || substr(
      (
        select
          name
        from
          wwv_flow_menu_templates
        where
          id = t.default_menu_template
      ),
      1,
      30
    ) || ' c=' || substr(
      (
        select
          name
        from
          wwv_flow_cal_templates
        where
          id = t.default_calendar_template
      ),
      1,
      30
    ) || ' l=' || substr(
      (
        select
          list_template_name
        from
          wwv_flow_list_templates
        where
          id = t.default_list_template
      ),
      1,
      30
    ) || ' l=' || substr(
      (
        select
          list_template_name
        from
          wwv_flow_list_templates
        where
          id = t.default_nav_list_template
      ),
      1,
      30
    ) || ' l=' || substr(
      (
        select
          list_template_name
        from
          wwv_flow_list_templates
        where
          id = t.default_top_nav_list_template
      ),
      1,
      30
    ) || ' l=' || substr(
      (
        select
          list_template_name
        from
          wwv_flow_list_templates
        where
          id = t.default_side_nav_list_template
      ),
      1,
      30
    ) || ' l=' || substr(
      (
        select
          template_Name
        from
          wwv_flow_field_templates
        where
          id = t.default_option_label
      ),
      1,
      30
    ) || ' l=' || substr(
      (
        select
          template_Name
        from
          wwv_flow_field_templates
        where
          id = t.default_required_label
      ),
      1,
      30
    ) || ' l=' || substr(
      (
        select
          list_template_name
        from
          wwv_flow_list_templates
        where
          id = t.default_nav_bar_list_template
      ),
      1,
      30
    ) || ' c=' || substr(t.calendar_icon, 1, 30) || ' c=' || substr(t.calendar_icon_attr, 1, 30) || ' dbr=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_dialogbtnr_template
      ),
      1,
      30
    ) || ' dr=' || substr(
      (
        select
          page_plug_template_name
        from
          wwv_flow_page_plug_templates
        where
          id = t.default_dialogr_template
      ),
      1,
      30
    ) component_signature
  from
    wwv_flow_themes t,
    wwv_flow_ui_types uit,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
    and uit.id = t.ui_type_id
