schema: APEX_050000
name: APEX_APPLICATION_PAGE_RPT
updatedAllowed: true
insertAllowed: true
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    p.flow_id application_id,
    f.name application_name,
    p.id page_id,
    p.name page_name,
    --
    r.plug_name region_name,
    decode(
      r.PLUG_SOURCE_TYPE,
      'NATIVE_SQL_REPORT',
      'Report',
      'NATIVE_FNC_REPORT',
      'Report',
      'NATIVE_TABFORM',
      'Tabular Form'
    ) source_type,
    PRN_BODY_BG_COLOR body_background_color,
    PRN_BODY_FONT_COLOR body_font_color,
    PRN_BODY_FONT_FAMILY body_font_family,
    PRN_BODY_FONT_SIZE body_font_size,
    PRN_BODY_FONT_WEIGHT body_font_weight,
    PRN_BORDER_COLOR border_color,
    PRN_BORDER_WIDTH border_width,
    PRN_FORMAT format,
    PRN_FORMAT_ITEM format_item,
    PRN_PAGE_HEADER page_header,
    PRN_PAGE_HEADER_ALIGNMENT page_header_alignment,
    PRN_PAGE_HEADER_FONT_COLOR page_header_font_color,
    PRN_PAGE_HEADER_FONT_FAMILY page_header_font_family,
    PRN_PAGE_HEADER_FONT_SIZE page_header_font_size,
    PRN_PAGE_HEADER_FONT_WEIGHT page_header_font_weight,
    PRN_HEADER_BG_COLOR header_background_color,
    PRN_HEADER_FONT_COLOR header_font_color,
    PRN_HEADER_FONT_FAMILY header_font_family,
    PRN_HEADER_FONT_SIZE header_font_size,
    PRN_HEADER_FONT_WEIGHT header_font_weight,
    PRN_HEIGHT height,
    PRN_ORIENTATION orientation,
    PRN_OUTPUT output,
    prn_print_server_overwrite print_server_override,
    PRN_OUTPUT_FILE_NAME output_file_name,
    prn_content_disposition content_disposition,
    prn_document_header document_header,
    PRN_OUTPUT_LINK_TEXT output_link_text,
    PRN_OUTPUT_SHOW_LINK show_output_link,
    PRN_PAGE_FOOTER footer,
    PRN_PAGE_FOOTER_ALIGNMENT footer_alignment,
    PRN_PAGE_FOOTER_FONT_COLOR footer_font_color,
    PRN_PAGE_FOOTER_FONT_FAMILY footer_font_family,
    PRN_PAGE_FOOTER_FONT_SIZE footer_font_size,
    PRN_PAGE_FOOTER_FONT_WEIGHT footer_font_weight,
    --
    PRN_PAPER_SIZE paper_size,
    PRN_TEMPLATE_ID template_id,
    PRN_UNITS paper_size_units,
    prn_width_units paper_size_width_units,
    PRN_WIDTH paper_size_width,
    --
    r.LAST_UPDATED_BY last_updated_by,
    r.LAST_UPDATED_ON last_updated_on,
    r.PLUG_COMMENT component_comment,
    r.id region_id,
    --
    region_name || '.' || PRN_BODY_BG_COLOR || PRN_BODY_FONT_COLOR || PRN_BODY_FONT_FAMILY || PRN_BODY_FONT_SIZE || PRN_BODY_FONT_WEIGHT || PRN_BORDER_COLOR || PRN_BORDER_WIDTH || length(PRN_FORMAT) || PRN_FORMAT_ITEM || length(PRN_PAGE_HEADER) || PRN_PAGE_HEADER_ALIGNMENT || PRN_PAGE_HEADER_FONT_COLOR || PRN_PAGE_HEADER_FONT_FAMILY || PRN_PAGE_HEADER_FONT_SIZE || PRN_PAGE_HEADER_FONT_WEIGHT || PRN_HEADER_BG_COLOR || PRN_HEADER_FONT_COLOR || PRN_HEADER_FONT_FAMILY || PRN_HEADER_FONT_SIZE || PRN_HEADER_FONT_WEIGHT || PRN_HEIGHT || PRN_ORIENTATION || PRN_OUTPUT || PRN_OUTPUT_FILE_NAME || PRN_CONTENT_DISPOSITION || PRN_DOCUMENT_HEADER || PRN_UNITS || PRN_OUTPUT_LINK_TEXT || PRN_OUTPUT_SHOW_LINK || length(PRN_PAGE_FOOTER) || PRN_PAGE_FOOTER_ALIGNMENT || PRN_PAGE_FOOTER_FONT_COLOR || PRN_PAGE_FOOTER_FONT_FAMILY || PRN_PAGE_FOOTER_FONT_SIZE || PRN_PAGE_FOOTER_FONT_WEIGHT || PRN_PAPER_SIZE || PRN_TEMPLATE_ID || PRN_UNITS || PRN_WIDTH component_signature
  from
    wwv_flow_page_plugs r,
    wwv_flow_steps p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = p.security_group_id
    and f.id = p.flow_id
    and f.id = r.flow_id
    and p.id = r.page_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
    and r.PLUG_SOURCE_TYPE in (
      'NATIVE_SQL_REPORT',
      'NATIVE_FNC_REPORT',
      'NATIVE_TABFORM'
    )
columns: []
referencedTables: []
