schema: APEX_050000
name: APEX_APPLICATION_TEMP_LIST
updatedAllowed: true
insertAllowed: true
columns:
- name: A01_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 39
  dataTypeLength: 4000
- name: A02_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 40
  dataTypeLength: 4000
- name: A03_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 41
  dataTypeLength: 4000
- name: A04_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 42
  dataTypeLength: 4000
- name: A05_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 4000
- name: A06_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 44
  dataTypeLength: 4000
- name: A07_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 4000
- name: A08_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 46
  dataTypeLength: 4000
- name: A09_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 47
  dataTypeLength: 4000
- name: A10_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 48
  dataTypeLength: 4000
- name: A11_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 49
  dataTypeLength: 4000
- name: A12_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 50
  dataTypeLength: 4000
- name: A13_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 51
  dataTypeLength: 4000
- name: A14_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 52
  dataTypeLength: 4000
- name: A15_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 53
  dataTypeLength: 4000
- name: A16_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 54
  dataTypeLength: 4000
- name: A17_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 55
  dataTypeLength: 4000
- name: A18_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 56
  dataTypeLength: 4000
- name: A19_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 57
  dataTypeLength: 4000
- name: A20_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 58
  dataTypeLength: 4000
- name: AFTER_SUB_LIST
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: BEFORE_SUB_LIST
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: BETWEEN_ITEMS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: BETWEEN_SUB_LIST_ITEMS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 59
  dataTypeLength: 4000
- name: CSS_FILE_URLS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 4000
- name: DEFAULT_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 255
- name: FIRST_LIST_TEMPLATE_CURRENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: FIRST_LIST_TEMPLATE_NONCURRENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: FITEM_TEMPLATE_NONCURR_W_CHILD
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 4000
- name: F_ITEM_TEMPLATE_CURR_W_CHILD
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 4000
- name: INLINE_CSS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 4000
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 3
- name: ITEM_TEMPLATE_CURR_W_CHILD
  dataType: CLOB
  nullable: true
  ordinalPosition: 20
  dataTypeLength:
- name: ITEM_TEMPLATE_NONCURR_W_CHILD
  dataType: CLOB
  nullable: true
  ordinalPosition: 21
  dataTypeLength:
- name: JAVASCRIPT_CODE_ONLOAD
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 4000
- name: JAVASCRIPT_FILE_URLS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 4000
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 31
  dataTypeLength:
- name: LIST_TEMPLATE_AFTER_ROWS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: LIST_TEMPLATE_BEFORE_ROWS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: LIST_TEMPLATE_CURRENT
  dataType: CLOB
  nullable: true
  ordinalPosition: 10
  dataTypeLength:
- name: LIST_TEMPLATE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 38
  dataTypeLength:
- name: LIST_TEMPLATE_NONCURRENT
  dataType: CLOB
  nullable: true
  ordinalPosition: 11
  dataTypeLength:
- name: PRESET_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 255
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 297
- name: SUB_LIST_ITEM_CURRENT
  dataType: CLOB
  nullable: true
  ordinalPosition: 18
  dataTypeLength:
- name: SUB_LIST_ITEM_NONCURRENT
  dataType: CLOB
  nullable: true
  ordinalPosition: 19
  dataTypeLength:
- name: SUB_TEMPLATE_CURR_W_CHILD
  dataType: CLOB
  nullable: true
  ordinalPosition: 22
  dataTypeLength:
- name: SUB_TEMPLATE_NONCURR_W_CHILD
  dataType: CLOB
  nullable: true
  ordinalPosition: 23
  dataTypeLength:
- name: TEMPLATE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: THEME_CLASS
  dataType: VARCHAR2
  textMaxLength: 40
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 40
- name: THEME_NUMBER
  dataType: NUMBER
  nullable: true
  ordinalPosition: 32
  dataTypeLength:
- name: TRANSLATE_THIS_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 1
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_LIST_TEMPLATES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.LIST_TEMPLATE_NAME template_name,
    --
    t.JAVASCRIPT_FILE_URLS javascript_file_urls,
    t.JAVASCRIPT_CODE_ONLOAD javascript_code_onload,
    t.CSS_FILE_URLS css_file_urls,
    t.INLINE_CSS inline_css,
    --
    t.LIST_TEMPLATE_CURRENT,
    t.LIST_TEMPLATE_NONCURRENT,
    t.LIST_TEMPLATE_BEFORE_ROWS,
    t.LIST_TEMPLATE_AFTER_ROWS,
    t.BETWEEN_ITEMS,
    t.BEFORE_SUB_LIST,
    t.AFTER_SUB_LIST,
    t.BETWEEN_SUB_LIST_ITEMS,
    t.SUB_LIST_ITEM_CURRENT,
    t.SUB_LIST_ITEM_NONCURRENT,
    t.ITEM_TEMPLATE_CURR_W_CHILD,
    t.ITEM_TEMPLATE_NONCURR_W_CHILD,
    t.SUB_TEMPLATE_CURR_W_CHILD,
    t.SUB_TEMPLATE_NONCURR_W_CHILD,
    --
    t.FIRST_LIST_TEMPLATE_NONCURRENT,
    t.FIRST_LIST_TEMPLATE_CURRENT,
    t.F_ITEM_TEMPLATE_CURR_W_CHILD,
    t.FITEM_TEMPLATE_NONCURR_W_CHILD,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        WWV_FLOW_LIST_TEMPLATES
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    t.LAST_UPDATED_BY,
    t.LAST_UPDATED_ON,
    t.THEME_ID theme_number,
    decode(
      t.THEME_CLASS_ID,
      '1',
      'Vertical Unordered List with Bullets',
      '2',
      'Vertical Ordered List',
      '3',
      'Horizontal Links List',
      '4',
      'Horizontal Images with Label List',
      '5',
      'Vertical Images List',
      '6',
      'Button List',
      '7',
      'Tabbed Navigation List',
      '9',
      'Custom 1',
      '10',
      'Custom 2',
      '11',
      'Custom 3',
      '12',
      'Custom 4',
      '13',
      'Custom 5',
      '14',
      'Custom 6',
      '15',
      'Custom 7',
      '16',
      'Custom 8',
      '17',
      'Wizard Progress List',
      '18',
      'Vertical Unordered List without Bullets',
      '19',
      'Vertical Sidebar List',
      '20',
      'Pull Down Menu',
      '21',
      'Pull Down Menu with Image',
      '22',
      'Hierarchical Expanding',
      '23',
      'Hierarchical Expanded',
      t.THEME_CLASS_ID
    ) theme_class,
    t.default_template_options default_template_options,
    t.preset_template_options preset_template_options,
    t.TRANSLATE_THIS_TEMPLATE,
    t.LIST_TEMPLATE_COMMENT component_comment,
    t.id list_template_id,
    --
    t.a01_label,
    t.a02_label,
    t.a03_label,
    t.a04_label,
    t.a05_label,
    t.a06_label,
    t.a07_label,
    t.a08_label,
    t.a09_label,
    t.a10_label,
    t.a11_label,
    t.a12_label,
    t.a13_label,
    t.a14_label,
    t.a15_label,
    t.a16_label,
    t.a17_label,
    t.a18_label,
    t.a19_label,
    t.a20_label,
    --
    t.LIST_TEMPLATE_NAME || ' t=' || t.THEME_ID || ' c=' || t.THEME_CLASS_ID || ' 1=' || sys.dbms_lob.substr(t.LIST_TEMPLATE_CURRENT, 40, 1) || '.' || sys.dbms_lob.getlength(t.LIST_TEMPLATE_CURRENT) || ' 2=' || sys.dbms_lob.substr(t.LIST_TEMPLATE_NONCURRENT, 40, 1) || '.' || sys.dbms_lob.getlength(t.LIST_TEMPLATE_NONCURRENT) || ' 3=' || sys.dbms_lob.substr(t.SUB_LIST_ITEM_CURRENT, 40, 1) || '.' || sys.dbms_lob.getlength(t.SUB_LIST_ITEM_CURRENT) || ' 4=' || sys.dbms_lob.substr(t.SUB_LIST_ITEM_NONCURRENT, 40, 1) || '.' || sys.dbms_lob.getlength(t.SUB_LIST_ITEM_NONCURRENT) || ' 5=' || sys.dbms_lob.substr(t.ITEM_TEMPLATE_CURR_W_CHILD, 40, 1) || '.' || sys.dbms_lob.getlength(t.ITEM_TEMPLATE_CURR_W_CHILD) || ' 6=' || sys.dbms_lob.substr(t.ITEM_TEMPLATE_NONCURR_W_CHILD, 40, 1) || '.' || sys.dbms_lob.getlength(t.ITEM_TEMPLATE_NONCURR_W_CHILD) || ' 7=' || sys.dbms_lob.substr(t.SUB_TEMPLATE_CURR_W_CHILD, 40, 1) || '.' || sys.dbms_lob.getlength(t.SUB_TEMPLATE_CURR_W_CHILD) || ' 8=' || sys.dbms_lob.substr(t.SUB_TEMPLATE_NONCURR_W_CHILD, 40, 1) || '.' || sys.dbms_lob.getlength(t.SUB_TEMPLATE_NONCURR_W_CHILD) || ' t=' || t.TRANSLATE_THIS_TEMPLATE || ' r=' || decode(t.REFERENCE_ID, null, 'N', 'Y') || ' b=' || substr(t.LIST_TEMPLATE_BEFORE_ROWS, 1, 20) || length(t.LIST_TEMPLATE_BEFORE_ROWS) || ' a=' || substr(t.LIST_TEMPLATE_AFTER_ROWS, 1, 20) || length(t.LIST_TEMPLATE_AFTER_ROWS) || ' b=' || substr(t.BETWEEN_ITEMS, 1, 20) || length(t.BETWEEN_ITEMS) || ' b=' || substr(t.BEFORE_SUB_LIST, 1, 20) || length(t.BEFORE_SUB_LIST) || ' a=' || substr(t.AFTER_SUB_LIST, 1, 20) || length(t.AFTER_SUB_LIST) || ' b=' || substr(t.BETWEEN_SUB_LIST_ITEMS, 1, 20) || length(t.BETWEEN_SUB_LIST_ITEMS) component_signature
  from
    WWV_FLOW_LIST_TEMPLATES t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
