schema: APEX_050000
name: APEX_APPLICATION_AUTHORIZATION
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: ATTRIBUTE_01
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 4000
- name: ATTRIBUTE_02
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 4000
- name: ATTRIBUTE_03
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: ATTRIBUTE_04
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: ATTRIBUTE_05
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: ATTRIBUTE_06
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: ATTRIBUTE_07
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: ATTRIBUTE_08
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: ATTRIBUTE_09
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: ATTRIBUTE_10
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: ATTRIBUTE_11
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: ATTRIBUTE_12
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 4000
- name: ATTRIBUTE_13
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: ATTRIBUTE_14
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: ATTRIBUTE_15
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 4000
- name: AUTHORIZATION_SCHEME_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 29
  dataTypeLength:
- name: AUTHORIZATION_SCHEME_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: CACHING
  dataType: VARCHAR2
  textMaxLength: 20
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 20
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 575
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 575
- name: ERROR_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: false
  ordinalPosition: 23
  dataTypeLength: 4000
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 27
  dataTypeLength:
- name: REFERENCED_SCHEME_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 30
  dataTypeLength:
- name: SCHEME_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 255
- name: SCHEME_TYPE_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 7
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PLUGINS
- schema: APEX_050000
  name: WWV_FLOW_SECURITY_SCHEMES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    a .NAME authorization_scheme_name,
    case
      substr(a .scheme_type, 1, 7)
      when 'NATIVE_' then (
        select
          display_name
        from
          wwv_flow_plugins
        where
          flow_id = 4411
          and plugin_type = 'AUTHORIZATION TYPE'
          and name = substr(a .scheme_type, 8)
      )
      when 'PLUGIN_' then (
        select
          display_name
        from
          wwv_flow_plugins
        where
          flow_id = a .flow_id
          and plugin_type = 'AUTHORIZATION TYPE'
          and name = substr(a .scheme_type, 8)
      )
      else a .scheme_type
    end scheme_type,
    a .SCHEME_TYPE scheme_type_code,
    a .attribute_01,
    a .attribute_02,
    a .attribute_03,
    a .attribute_04,
    a .attribute_05,
    a .attribute_06,
    a .attribute_07,
    a .attribute_08,
    a .attribute_09,
    a .attribute_10,
    a .attribute_11,
    a .attribute_12,
    a .attribute_13,
    a .attribute_14,
    a .attribute_15,
    --
    a .ERROR_MESSAGE error_message,
    --
    decode(
      a .CACHING,
      'BY_USER_BY_PAGE_VIEW',
      'Once per page view',
      'BY_USER_BY_SESSION',
      'Once per session',
      a .CACHING
    ) caching,
    decode(a .REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    a .LAST_UPDATED_BY last_updated_by,
    a .LAST_UPDATED_ON last_updated_on,
    a .COMMENTS component_comment,
    --
    a .id authorization_scheme_id,
    a .REFERENCE_ID referenced_scheme_id,
    --
    substr(a .NAME, 1, 30) || length(a .NAME) || ' t=' || substr(a .SCHEME_TYPE, 1, 30) || length(a .SCHEME_TYPE) || ' e=' || substr(a .ERROR_MESSAGE, 1, 30) || length(a .ERROR_MESSAGE) || ' s=' || decode(
      a .CACHING,
      'BY_USER_BY_PAGE_VIEW',
      'Once per page view',
      'BY_USER_BY_SESSION',
      'Once per session',
      substr(a .CACHING, 1, 20)
    ) || ' r=' || decode(a .REFERENCE_ID, null, 'No', 'Yes') component_signature
  from
    WWV_FLOW_SECURITY_SCHEMES a,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = a .flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
