schema: APEX_050000
name: APEX_APPLICATION_ITEMS
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_ITEM_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 13
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: BUILD_OPTION
  dataType: VARCHAR2
  textMaxLength: 261
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 261
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 555
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 555
- name: DATA_TYPE
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 30
- name: ITEM_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 11
  dataTypeLength:
- name: SCOPE
  dataType: VARCHAR2
  textMaxLength: 6
  nullable: false
  ordinalPosition: 6
  dataTypeLength: 6
- name: SESSION_STATE_PROTECTION
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 1
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_ITEMS
- schema: APEX_050000
  name: WWV_FLOW_PATCHES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    --
    i.name item_name,
    i.scope scope,
    --i.name_length
    i.data_type data_type,
    --i.is_persistent                  ,
    i.protection_level session_state_protection,
    (
      select
        case
          when i.required_patch > 0 then patch_name
          else '{Not ' || patch_name || '}'
        end patch_name
      from
        wwv_flow_patches
      where
        id = abs(i.required_patch)
    ) build_option,
    i.last_updated_by,
    i.last_updated_on,
    i.item_comment component_comment,
    i.id application_item_id,
    --
    i.name || ' dt=' || i.data_type || ' prot=' || i.protection_level || ' bo='(
      select
        patch_name
      from
        wwv_flow_patches
      where
        id = i.required_patch
    ) component_signature
  from
    wwv_flow_items i,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.provisioning_company_id
    )
    and f.security_group_id = w.provisioning_company_id
    and s.schema = f.owner
    and s.security_group_id = w.provisioning_company_id
    and f.id = i.flow_id
    and (
      d.sgid != 0
      or nvl(f.build_status, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.provisioning_company_id != 0
