schema: APEX_050000
name: APEX_WS_APPLICATIONS
updatedAllowed: true
insertAllowed: true
columns:
- name: ACL_TYPE
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 30
- name: ALLOW_PUBLIC_ACCESS_YN
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 1
- name: ALLOW_SQL_YN
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 1
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 2
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: AUTH_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 17
  dataTypeLength:
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 35
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: false
  ordinalPosition: 34
  dataTypeLength:
- name: CUSTOM_CSS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: DATE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 255
- name: DESCRIPTION
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 4000
- name: EMAIL_FROM
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 255
- name: HOME_PAGE_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 10
  dataTypeLength:
- name: LANGUAGE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 255
- name: LOGIN_PAGE_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: LOGIN_URL
  dataType: VARCHAR2
  textMaxLength: 2000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 2000
- name: LOGOUT_URL
  dataType: VARCHAR2
  textMaxLength: 2000
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 2000
- name: LOGO_FILEPATH
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 4000
- name: LOGO_FILEPATH_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 4000
- name: LOGO_IMAGE_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: LOGO_IMAGE_CHARSET
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 255
- name: LOGO_IMAGE_FILENAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 255
- name: LOGO_IMAGE_LAST_UPDATE
  dataType: DATE
  nullable: true
  ordinalPosition: 29
  dataTypeLength:
- name: LOGO_IMAGE_MIMETYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 255
- name: LOGO_IMAGE_SIZE
  dataType: NUMBER
  nullable: true
  ordinalPosition: 25
  dataTypeLength:
- name: LOGO_TEXT
  dataType: VARCHAR2
  textMaxLength: 500
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 500
- name: LOGO_TEXT_ATTRIBUTES
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: LOGO_TYPE
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 30
- name: OWNER
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: PAGE_STYLE
  dataType: NUMBER
  nullable: true
  ordinalPosition: 11
  dataTypeLength:
- name: SHOW_RESET_PASSWD_YN
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 1
- name: STATUS
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 30
- name: TERRITORY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 255
- name: UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 255
- name: UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 36
  dataTypeLength:
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
referencedTables:
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_WS_APPLICATIONS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    a .id application_id,
    a .security_group_id workspace_id,
    a .name application_name,
    a .OWNER,
    a .DESCRIPTION,
    a .STATUS,
    a .LOGIN_URL,
    a .LOGOUT_URL,
    a .HOME_PAGE_ID,
    a .page_style,
    a .custom_css,
    a .show_reset_passwd_yn,
    a .allow_sql_yn,
    a .allow_public_access_yn,
    a .login_page_message,
    a .AUTH_ID,
    a .ACL_TYPE,
    a .DATE_FORMAT,
    a .language,
    a .territory,
    a .LOGO_TYPE,
    a .LOGO_TEXT,
    a .LOGO_TEXT_ATTRIBUTES,
    sys.dbms_lob.getlength(a .LOGO_IMAGE) logo_image_size,
    a .LOGO_IMAGE_FILENAME,
    a .LOGO_IMAGE_MIMETYPE,
    a .LOGO_IMAGE_CHARSET,
    a .LOGO_IMAGE_LAST_UPDATE,
    a .LOGO_IMAGE_ATTRIBUTES,
    a .LOGO_FILEPATH,
    a .LOGO_FILEPATH_ATTRIBUTES,
    a .email_from,
    --
    a .created_on,
    a .created_by,
    a .updated_on,
    a .updated_by
  from
    wwv_flow_ws_applications a,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.is_apex$_schema = 'Y'
    and a .security_group_id = w.PROVISIONING_COMPANY_ID
    and w.provisioning_company_id != 0
