schema: APEX_050000
name: APEX_APPLICATION_TEMP_REPORT
updatedAllowed: true
insertAllowed: true
columns:
- name: AFTER_COLUMN_HEADING
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: BEFORE_COLUMN_HEADING
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 4000
- name: COLUMN_HEADING_SORT_ASC_TEMP
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 4000
- name: COLUMN_HEADING_SORT_DESC_TEMP
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: COLUMN_HEADING_SORT_TEMP
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: COLUMN_HEADING_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 4000
- name: COL_TEMPLATE1
  dataType: CLOB
  nullable: true
  ordinalPosition: 13
  dataTypeLength:
- name: COL_TEMPLATE2
  dataType: CLOB
  nullable: true
  ordinalPosition: 16
  dataTypeLength:
- name: COL_TEMPLATE3
  dataType: CLOB
  nullable: true
  ordinalPosition: 19
  dataTypeLength:
- name: COL_TEMPLATE4
  dataType: CLOB
  nullable: true
  ordinalPosition: 22
  dataTypeLength:
- name: COL_TEMPLATE_AFTER_LAST
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 4000
- name: COL_TEMPLATE_AFTER_ROWS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 4000
- name: COL_TEMPLATE_BEFORE_FIRST
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 4000
- name: COL_TEMPLATE_BEFORE_ROWS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: COL_TEMPLATE_CONDITION1
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: COL_TEMPLATE_CONDITION2
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: COL_TEMPLATE_CONDITION3
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: COL_TEMPLATE_CONDITION4
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 4000
- name: COL_TEMPLATE_DISPLAY_COND1
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 30
- name: COL_TEMPLATE_DISPLAY_COND2
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 30
- name: COL_TEMPLATE_DISPLAY_COND3
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 30
- name: COL_TEMPLATE_DISPLAY_COND4
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 30
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 46
  dataTypeLength: 4000
- name: DEFAULT_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 42
  dataTypeLength: 255
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 38
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 39
  dataTypeLength:
- name: NEXT_PAGE_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: NEXT_SET_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 4000
- name: PAGINATION_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 4000
- name: PRESET_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 255
- name: PREVIOUS_PAGE_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 4000
- name: PREVIOUS_SET_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 4000
- name: ROW_STYLE_CHECKED
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 255
- name: ROW_STYLE_MOUSE_OVER
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 255
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 297
- name: TEMPLATE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 47
  dataTypeLength:
- name: TEMPLATE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: TEMPLATE_TYPE
  dataType: VARCHAR2
  textMaxLength: 33
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 33
- name: THEME_CLASS
  dataType: VARCHAR2
  textMaxLength: 40
  nullable: true
  ordinalPosition: 41
  dataTypeLength: 40
- name: THEME_NUMBER
  dataType: NUMBER
  nullable: true
  ordinalPosition: 40
  dataTypeLength:
- name: TRANSLATE_THIS_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 44
  dataTypeLength: 3
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_ROW_TEMPLATES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.ROW_TEMPLATE_NAME template_name,
    decode(
      t.ROW_TEMPLATE_TYPE,
      'GENERIC_COLUMNS',
      'Generic Columns (column template)',
      'NAMED_COLUMNS',
      'Named Column (row template)',
      t.ROW_TEMPLATE_TYPE
    ) template_type,
    --
    t.before_column_heading,
    t.COLUMN_HEADING_TEMPLATE,
    t.column_heading_sort_asc_temp,
    t.column_heading_sort_desc_temp,
    t.column_heading_sort_temp,
    t.after_column_heading,
    t.ROW_TEMPLATE1 col_TEMPLATE1,
    t.ROW_TEMPLATE_CONDITION1 col_TEMPLATE_CONDITION1,
    t.ROW_TEMPLATE_DISPLAY_COND1 col_TEMPLATE_DISPLAY_COND1,
    t.ROW_TEMPLATE2 col_TEMPLATE2,
    t.ROW_TEMPLATE_CONDITION2 col_TEMPLATE_CONDITION2,
    t.ROW_TEMPLATE_DISPLAY_COND2 col_TEMPLATE_DISPLAY_COND2,
    t.ROW_TEMPLATE3 col_TEMPLATE3,
    t.ROW_TEMPLATE_CONDITION3 col_TEMPLATE_CONDITION3,
    t.ROW_TEMPLATE_DISPLAY_COND3 col_TEMPLATE_DISPLAY_COND3,
    t.ROW_TEMPLATE4 col_TEMPLATE4,
    t.ROW_TEMPLATE_CONDITION4 col_TEMPLATE_CONDITION4,
    t.ROW_TEMPLATE_DISPLAY_COND4 col_TEMPLATE_DISPLAY_COND4,
    t.ROW_TEMPLATE_BEFORE_ROWS col_TEMPLATE_BEFORE_ROWS,
    t.ROW_TEMPLATE_AFTER_ROWS col_TEMPLATE_AFTER_ROWS,
    t.ROW_TEMPLATE_BEFORE_FIRST col_TEMPLATE_BEFORE_FIRST,
    t.ROW_TEMPLATE_AFTER_LAST col_TEMPLATE_AFTER_LAST,
    --t.ROW_TEMPLATE_TABLE_ATTRIBUTES  col_TEMPLATE_TABLE_ATTRIBUTES,
    t.PAGINATION_TEMPLATE,
    t.NEXT_PAGE_TEMPLATE,
    t.PREVIOUS_PAGE_TEMPLATE,
    t.NEXT_SET_TEMPLATE,
    t.PREVIOUS_SET_TEMPLATE,
    t.ROW_STYLE_MOUSE_OVER,
    --t.ROW_STYLE_MOUSE_OUT            ,
    t.ROW_STYLE_CHECKED,
    --t.ROW_STYLE_UNCHECKED            ,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        WWV_FLOW_ROW_TEMPLATES
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    t.LAST_UPDATED_BY,
    t.LAST_UPDATED_ON,
    t.THEME_ID theme_number,
    --
    decode(
      t.THEME_CLASS_ID,
      '1',
      'Borderless',
      '2',
      'Horizontal Border',
      '3',
      'One Column Unordered List',
      '4',
      'Standard',
      '5',
      'Standard, Alternating Row Colors',
      '6',
      'Value Attribute Pairs',
      '7',
      'Custom 1',
      '8',
      'Custom 2',
      '9',
      'Custom 3',
      '10',
      'Custom 4',
      '11',
      'Custom 5',
      '12',
      'Custom 6',
      '13',
      'Custom 7',
      '14',
      'Custom 8',
      t.THEME_CLASS_ID
    ) theme_class,
    t.default_template_options default_template_options,
    t.preset_template_options preset_template_options,
    decode(
      t.TRANSLATE_THIS_TEMPLATE,
      'Y',
      'Yes',
      'N',
      'No',
      'Yes'
    ) translate_this_template,
    t.ROW_TEMPLATE_COMMENT component_comment,
    --
    t.ROW_TEMPLATE_NAME || ' t=' || t.THEME_ID || ' c=' || t.THEME_CLASS_ID || ' t=' || t.ROW_TEMPLATE_TYPE || ' 1=' || sys.dbms_lob.substr(t.ROW_TEMPLATE1, 1, 40) || sys.dbms_lob.getlength(t.ROW_TEMPLATE1) || ' c=' || substr(t.ROW_TEMPLATE_CONDITION1, 1, 20) || length(t.ROW_TEMPLATE_CONDITION1) || ' c=' || substr(t.ROW_TEMPLATE_DISPLAY_COND1, 1, 20) || length(t.ROW_TEMPLATE_DISPLAY_COND1) || ' 2=' || sys.dbms_lob.substr(t.ROW_TEMPLATE2, 1, 40) || sys.dbms_lob.getlength(t.ROW_TEMPLATE2) || ' c=' || substr(t.ROW_TEMPLATE_CONDITION2, 1, 20) || length(t.ROW_TEMPLATE_CONDITION2) || ' c=' || substr(t.ROW_TEMPLATE_DISPLAY_COND2, 1, 20) || length(t.ROW_TEMPLATE_DISPLAY_COND2) || ' 3=' || sys.dbms_lob.substr(t.ROW_TEMPLATE3, 1, 40) || sys.dbms_lob.getlength(t.ROW_TEMPLATE3) || ' c=' || substr(t.ROW_TEMPLATE_CONDITION3, 1, 20) || length(t.ROW_TEMPLATE_CONDITION3) || ' c=' || substr(t.ROW_TEMPLATE_DISPLAY_COND3, 1, 20) || length(t.ROW_TEMPLATE_DISPLAY_COND3) || ' 4=' || sys.dbms_lob.substr(t.ROW_TEMPLATE4, 1, 40) || sys.dbms_lob.getlength(t.ROW_TEMPLATE4) || decode(t.REFERENCE_ID, null, 'N', 'Y') component_signature,
    t.id template_id
  from
    WWV_FLOW_ROW_TEMPLATES t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
