schema: APEX_050000
name: APEX_APPLICATION_CACHING
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    c .page_id page_id,
    (
      select
        name
      from
        wwv_flow_steps s
      where
        s.security_group_id = c .security_group_id
        and s.flow_id = c .flow_id
        and s.id = c .page_id
    ) page_name,
    case
      when c .region_id is null then 'Page Cache'
      when p.plug_source_type like 'NATIVE%CHART%' then 'Chart Region Cache'
      else 'Region Cache'
    end cache_type,
    c .language language,
    c .user_name caching_user,
    sys.dbms_lob.getlength(c .page_text) cache_size,
    p.plug_name region_name,
    c .cached_on cached_on,
    case
      when c .region_id is null then (
        select
          cache_timeout_seconds
        from
          wwv_flow_steps s
        where
          s.security_group_id = c .security_group_id
          and s.flow_id = c .flow_id
          and s.id = c .page_id
      )
      else p.plug_caching_max_age_in_sec
    end cached_for_seconds,
    --
    round((sysdate - c .cached_on) * 3600 * 24, 0) age_in_seconds,
    --
    case
      when c .region_id is null then (
        select
          cache_timeout_seconds
        from
          wwv_flow_steps s
        where
          s.security_group_id = c .security_group_id
          and s.flow_id = c .flow_id
          and s.id = c .page_id
      )
      else p.plug_caching_max_age_in_sec
    end - round((sysdate - c .cached_on) * 3600 * 24, 0) timeout_in_seconds,
    c .REGION_ID region_id,
    c .SECURITY_GROUP_ID workspace_id
  from
    wwv_flow_page_cache c,
    wwv_flow_page_plugs p,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and c .flow_id = f.id
    and f.security_group_id = w.provisioning_company_id
    and f.security_group_id = s.security_group_id
    and c .flow_id = p.flow_id(+)
    and c .region_id = p.id(+)
    and c .security_group_id = p.security_group_id(+)
    and s.schema = f.owner
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
