schema: APEX_050000
name: APEX_APPLICATION_TEMP_POPUPLOV
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.POPUP_ICON,
    t.POPUP_ICON_ATTR,
    t.POPUP_ICON2,
    t.POPUP_ICON_ATTR2,
    --t.PAGE_NAME                      ,
    t.PAGE_TITLE,
    t.PAGE_HTML_HEAD,
    t.PAGE_BODY_ATTR,
    t.BEFORE_FIELD_TEXT,
    t.AFTER_FIELD_TEXT,
    t.PAGE_HEADING_TEXT,
    t.PAGE_FOOTER_TEXT,
    t.BEFORE_RESULT_SET,
    t.AFTER_RESULT_SET,
    t.FILTER_WIDTH,
    t.FILTER_MAX_WIDTH,
    t.FILTER_TEXT_ATTR,
    t.FIND_BUTTON_TEXT,
    t.FIND_BUTTON_IMAGE,
    t.FIND_BUTTON_ATTR,
    t.CLOSE_BUTTON_TEXT,
    t.CLOSE_BUTTON_IMAGE,
    t.CLOSE_BUTTON_ATTR,
    t.NEXT_BUTTON_TEXT,
    t.NEXT_BUTTON_IMAGE,
    t.NEXT_BUTTON_ATTR,
    t.PREV_BUTTON_TEXT,
    t.PREV_BUTTON_IMAGE,
    t.PREV_BUTTON_ATTR,
    t.SCROLLBARS,
    t.RESIZABLE,
    t.WIDTH,
    t.HEIGHT,
    t.RESULT_ROW_X_OF_Y,
    t.RESULT_ROWS_PER_PG,
    t.WHEN_NO_DATA_FOUND_MESSAGE,
    t.BEFORE_FIRST_FETCH_MESSAGE,
    t.MINIMUM_CHARACTERS_REQUIRED,
    t.THEME_ID theme_number,
    --
    decode(
      t.THEME_CLASS_ID,
      '1',
      'Standard',
      t.THEME_CLASS_ID
    ) theme_class,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        WWV_FLOW_POPUP_LOV_TEMPLATE
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    t.LAST_UPDATED_ON last_updated_on,
    t.LAST_UPDATED_BY last_updated_by,
    decode(
      t.TRANSLATE_THIS_TEMPLATE,
      'N',
      'No',
      'Y',
      'Yes',
      'Yes'
    ) translatable,
    t.TEMPLATE_COMMENT component_comment,
    t.id template_id,
    --
    'pop' || ' =' || substr(POPUP_ICON, 1, 20) || length(POPUP_ICON) || ' =' || substr(POPUP_ICON_ATTR, 1, 20) || length(POPUP_ICON_ATTR) || ' =' || substr(POPUP_ICON2, 1, 20) || length(POPUP_ICON2) || ' =' || substr(POPUP_ICON_ATTR2, 1, 20) || length(POPUP_ICON_ATTR2) || ' =' || substr(PAGE_TITLE, 1, 20) || length(PAGE_TITLE) || ' =' || substr(PAGE_HTML_HEAD, 1, 20) || length(PAGE_HTML_HEAD) || ' =' || substr(PAGE_BODY_ATTR, 1, 20) || length(PAGE_BODY_ATTR) || ' =' || substr(BEFORE_FIELD_TEXT, 1, 20) || length(BEFORE_FIELD_TEXT) || ' =' || substr(AFTER_FIELD_TEXT, 1, 20) || length(AFTER_FIELD_TEXT) || ' =' || substr(PAGE_HEADING_TEXT, 1, 20) || length(PAGE_HEADING_TEXT) || ' =' || substr(PAGE_FOOTER_TEXT, 1, 20) || length(PAGE_FOOTER_TEXT) || ' =' || substr(BEFORE_RESULT_SET, 1, 20) || length(BEFORE_RESULT_SET) || ' =' || substr(AFTER_RESULT_SET, 1, 20) || length(AFTER_RESULT_SET) || ' =' || substr(FILTER_WIDTH, 1, 20) || length(FILTER_WIDTH) || ' =' || substr(FILTER_MAX_WIDTH, 1, 20) || length(FILTER_MAX_WIDTH) || ' =' || substr(FILTER_TEXT_ATTR, 1, 20) || length(FILTER_TEXT_ATTR) || ' =' || substr(FIND_BUTTON_TEXT, 1, 20) || length(FIND_BUTTON_TEXT) || ' =' || substr(FIND_BUTTON_IMAGE, 1, 20) || length(FIND_BUTTON_IMAGE) || ' =' || substr(FIND_BUTTON_ATTR, 1, 20) || length(FIND_BUTTON_ATTR) || ' =' || substr(CLOSE_BUTTON_TEXT, 1, 20) || length(CLOSE_BUTTON_TEXT) || ' =' || substr(CLOSE_BUTTON_IMAGE, 1, 20) || length(CLOSE_BUTTON_IMAGE) || ' =' || substr(CLOSE_BUTTON_ATTR, 1, 20) || length(CLOSE_BUTTON_ATTR) || ' =' || substr(NEXT_BUTTON_TEXT, 1, 20) || length(NEXT_BUTTON_TEXT) || ' =' || substr(NEXT_BUTTON_IMAGE, 1, 20) || length(NEXT_BUTTON_IMAGE) || ' =' || substr(NEXT_BUTTON_ATTR, 1, 20) || length(NEXT_BUTTON_ATTR) || ' =' || substr(PREV_BUTTON_TEXT, 1, 20) || length(PREV_BUTTON_TEXT) || ' =' || substr(PREV_BUTTON_IMAGE, 1, 20) || length(PREV_BUTTON_IMAGE) || ' =' || substr(PREV_BUTTON_ATTR, 1, 20) || length(PREV_BUTTON_ATTR) || ' =' || substr(SCROLLBARS, 1, 20) || length(SCROLLBARS) || ' =' || substr(RESIZABLE, 1, 20) || length(RESIZABLE) || ' =' || substr(WIDTH, 1, 20) || length(WIDTH) || ' =' || substr(HEIGHT, 1, 20) || length(HEIGHT) || ' =' || substr(RESULT_ROW_X_OF_Y, 1, 20) || length(RESULT_ROW_X_OF_Y) || ' =' || RESULT_ROWS_PER_PG || ' =' || substr(WHEN_NO_DATA_FOUND_MESSAGE, 1, 20) || length(WHEN_NO_DATA_FOUND_MESSAGE) || ' =' || substr(BEFORE_FIRST_FETCH_MESSAGE, 1, 20) || length(BEFORE_FIRST_FETCH_MESSAGE) || ' =' || substr(MINIMUM_CHARACTERS_REQUIRED, 1, 20) || length(MINIMUM_CHARACTERS_REQUIRED) || ' r=' || decode(t.REFERENCE_ID, null, 'N', 'Y') component_signature
  from
    WWV_FLOW_POPUP_LOV_TEMPLATE t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
