schema: APEX_050000
name: APEX_APPLICATION_TEMP_CALENDAR
updatedAllowed: true
insertAllowed: true
columns:
- name: AGENDA_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 62
  dataTypeLength: 4000
- name: AGENDA_FUTURE_DAY_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 65
  dataTypeLength: 4000
- name: AGENDA_FUTURE_ENTRY_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 68
  dataTypeLength: 4000
- name: AGENDA_PAST_DAY_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 63
  dataTypeLength: 4000
- name: AGENDA_PAST_ENTRY_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 66
  dataTypeLength: 4000
- name: AGENDA_TODAY_DAY_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 64
  dataTypeLength: 4000
- name: AGENDA_TODAY_ENTRY_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 67
  dataTypeLength: 4000
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: CALENDAR_TEMPLATE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 72
  dataTypeLength:
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 71
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 598
  nullable: true
  ordinalPosition: 73
  dataTypeLength: 598
- name: DAILY_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 4000
- name: DAILY_DAY_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 55
  dataTypeLength: 4000
- name: DAILY_DAY_OF_WEEK_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 49
  dataTypeLength: 4000
- name: DAILY_DAY_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 54
  dataTypeLength: 4000
- name: DAILY_DAY_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 53
  dataTypeLength: 4000
- name: DAILY_HOUR_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 61
  dataTypeLength: 4000
- name: DAILY_HOUR_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 60
  dataTypeLength: 4000
- name: DAILY_MONTH_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 52
  dataTypeLength: 4000
- name: DAILY_MONTH_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 51
  dataTypeLength: 4000
- name: DAILY_MONTH_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 50
  dataTypeLength: 4000
- name: DAILY_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 4000
- name: DAILY_TIME_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 58
  dataTypeLength: 4000
- name: DAILY_TIME_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 57
  dataTypeLength: 4000
- name: DAILY_TIME_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 59
  dataTypeLength: 4000
- name: DAILY_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: DAILY_TODAY_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 56
  dataTypeLength: 4000
- name: DAY_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 4000
- name: DAY_OF_WEEK_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: DAY_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: DAY_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 7
  dataTypeLength:
- name: MONTH_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: MONTH_DATA_ENTRY_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 70
  dataTypeLength: 4000
- name: MONTH_DATA_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 69
  dataTypeLength: 4000
- name: MONTH_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: MONTH_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: NONDAY_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 4000
- name: NONDAY_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: NONDAY_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 554
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 554
- name: TEMPLATE_NAME
  dataType: VARCHAR2
  textMaxLength: 512
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 512
- name: THEME_CLASS
  dataType: VARCHAR2
  textMaxLength: 40
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 40
- name: THEME_NUMBER
  dataType: NUMBER
  nullable: true
  ordinalPosition: 8
  dataTypeLength:
- name: TODAY_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: TRANSLATABLE
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 3
- name: WEEKEND_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 4000
- name: WEEKEND_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 4000
- name: WEEKEND_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: WEEKLY_DAY_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 39
  dataTypeLength: 4000
- name: WEEKLY_DAY_OF_WEEK_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 4000
- name: WEEKLY_DAY_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 38
  dataTypeLength: 4000
- name: WEEKLY_DAY_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 4000
- name: WEEKLY_HOUR_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 48
  dataTypeLength: 4000
- name: WEEKLY_HOUR_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 47
  dataTypeLength: 4000
- name: WEEKLY_MONTH_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 4000
- name: WEEKLY_MONTH_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 4000
- name: WEEKLY_TIME_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 4000
- name: WEEKLY_TIME_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 44
  dataTypeLength: 4000
- name: WEEKLY_TIME_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 46
  dataTypeLength: 4000
- name: WEEKLY_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 4000
- name: WEEKLY_TODAY_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 40
  dataTypeLength: 4000
- name: WEEKLY_WEEKEND_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 4000
- name: WEEKLY_WEEKEND_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 42
  dataTypeLength: 4000
- name: WEEKLY_WEEKEND_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 41
  dataTypeLength: 4000
- name: WEEK_CLOSE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 4000
- name: WEEK_OPEN_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 4000
- name: WEEK_TITLE_FORMAT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 4000
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_CAL_TEMPLATES
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.NAME template_name,
    t.LAST_UPDATED_BY,
    t.LAST_UPDATED_ON,
    t.THEME_ID theme_number,
    decode(
      t.THEME_CLASS_ID,
      '1',
      'Calendar',
      '2',
      'Calendar, Alternative 1',
      '3',
      'Small Calendar',
      '4',
      'Custom 1',
      '5',
      'Custom 2',
      '6',
      'Custom 3',
      '7',
      'Custom 4',
      '8',
      'Custom 5',
      '9',
      'Custom 6',
      '10',
      'Custom 7',
      '11',
      'Custom 8',
      t.THEME_CLASS_ID
    ) theme_class,
    --
    decode(
      t.TRANSLATE_THIS_TEMPLATE,
      'Y',
      'Yes',
      'N',
      'No',
      'Yes'
    ) translatable,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        WWV_FLOW_CAL_TEMPLATES
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    t.MONTH_TITLE_FORMAT,
    t.DAY_OF_WEEK_FORMAT,
    t.MONTH_OPEN_FORMAT,
    t.MONTH_CLOSE_FORMAT,
    t.DAY_TITLE_FORMAT,
    t.DAY_OPEN_FORMAT,
    t.DAY_CLOSE_FORMAT,
    t.TODAY_OPEN_FORMAT,
    t.WEEKEND_TITLE_FORMAT,
    t.WEEKEND_OPEN_FORMAT,
    t.WEEKEND_CLOSE_FORMAT,
    t.NONDAY_TITLE_FORMAT,
    t.NONDAY_OPEN_FORMAT,
    t.NONDAY_CLOSE_FORMAT,
    t.WEEK_TITLE_FORMAT,
    t.WEEK_OPEN_FORMAT,
    t.WEEK_CLOSE_FORMAT,
    t.DAILY_TITLE_FORMAT,
    t.DAILY_OPEN_FORMAT,
    t.DAILY_CLOSE_FORMAT,
    t.weekly_title_format,
    t.weekly_day_of_week_format,
    t.weekly_month_open_format,
    t.weekly_month_close_format,
    t.weekly_day_title_format,
    t.weekly_day_open_format,
    t.weekly_day_close_format,
    t.weekly_today_open_format,
    t.weekly_weekend_title_format,
    t.weekly_weekend_open_format,
    t.weekly_weekend_close_format,
    t.weekly_time_open_format,
    t.weekly_time_close_format,
    t.weekly_time_title_format,
    t.weekly_hour_open_format,
    t.weekly_hour_close_format,
    t.daily_day_of_week_format,
    t.daily_month_title_format,
    t.daily_month_open_format,
    t.daily_month_close_format,
    t.daily_day_title_format,
    t.daily_day_open_format,
    t.daily_day_close_format,
    t.daily_today_open_format,
    t.daily_time_open_format,
    t.daily_time_close_format,
    t.daily_time_title_format,
    t.daily_hour_open_format,
    t.daily_hour_close_format,
    t.agenda_format,
    t.agenda_past_day_format,
    t.agenda_today_day_format,
    t.agenda_future_day_format,
    t.agenda_past_entry_format,
    t.agenda_today_entry_format,
    t.agenda_future_entry_format,
    t.month_data_format,
    t.month_data_entry_format,
    t.TEMPLATE_COMMENTS component_comment,
    t.id calendar_template_id,
    --
    t.NAME || ' t=' || t.THEME_ID || ' c=' || t.THEME_CLASS_ID component_signature
  from
    WWV_FLOW_CAL_TEMPLATES t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
