schema: APEX_050000
name: APEX_APPLICATION_PAGE_IR_GRPBY
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: APPLICATION_USER
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 255
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 13
  dataTypeLength:
- name: FUNCTION_01
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 255
- name: FUNCTION_02
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 255
- name: FUNCTION_03
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 255
- name: FUNCTION_04
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 255
- name: FUNCTION_05
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 41
  dataTypeLength: 255
- name: FUNCTION_06
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 47
  dataTypeLength: 255
- name: FUNCTION_07
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 53
  dataTypeLength: 255
- name: FUNCTION_08
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 59
  dataTypeLength: 255
- name: FUNCTION_COLUMN_01
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 255
- name: FUNCTION_COLUMN_02
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 255
- name: FUNCTION_COLUMN_03
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 255
- name: FUNCTION_COLUMN_04
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 255
- name: FUNCTION_COLUMN_05
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 42
  dataTypeLength: 255
- name: FUNCTION_COLUMN_06
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 48
  dataTypeLength: 255
- name: FUNCTION_COLUMN_07
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 54
  dataTypeLength: 255
- name: FUNCTION_COLUMN_08
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 60
  dataTypeLength: 255
- name: FUNCTION_DB_COLUMN_NAME_01
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 30
- name: FUNCTION_DB_COLUMN_NAME_02
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 30
- name: FUNCTION_DB_COLUMN_NAME_03
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 30
- name: FUNCTION_DB_COLUMN_NAME_04
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 30
- name: FUNCTION_DB_COLUMN_NAME_05
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 30
- name: FUNCTION_DB_COLUMN_NAME_06
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 49
  dataTypeLength: 30
- name: FUNCTION_DB_COLUMN_NAME_07
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 55
  dataTypeLength: 30
- name: FUNCTION_DB_COLUMN_NAME_08
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 61
  dataTypeLength: 30
- name: FUNCTION_FORMAT_MASK_01
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 255
- name: FUNCTION_FORMAT_MASK_02
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 255
- name: FUNCTION_FORMAT_MASK_03
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 255
- name: FUNCTION_FORMAT_MASK_04
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 39
  dataTypeLength: 255
- name: FUNCTION_FORMAT_MASK_05
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 255
- name: FUNCTION_FORMAT_MASK_06
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 51
  dataTypeLength: 255
- name: FUNCTION_FORMAT_MASK_07
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 57
  dataTypeLength: 255
- name: FUNCTION_FORMAT_MASK_08
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 63
  dataTypeLength: 255
- name: FUNCTION_LABEL_01
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: FUNCTION_LABEL_02
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 4000
- name: FUNCTION_LABEL_03
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 4000
- name: FUNCTION_LABEL_04
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 38
  dataTypeLength: 4000
- name: FUNCTION_LABEL_05
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 44
  dataTypeLength: 4000
- name: FUNCTION_LABEL_06
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 50
  dataTypeLength: 4000
- name: FUNCTION_LABEL_07
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 56
  dataTypeLength: 4000
- name: FUNCTION_LABEL_08
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 62
  dataTypeLength: 4000
- name: FUNCTION_SUM_01
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 1
- name: FUNCTION_SUM_02
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 1
- name: FUNCTION_SUM_03
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 1
- name: FUNCTION_SUM_04
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 40
  dataTypeLength: 1
- name: FUNCTION_SUM_05
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 46
  dataTypeLength: 1
- name: FUNCTION_SUM_06
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 52
  dataTypeLength: 1
- name: FUNCTION_SUM_07
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 58
  dataTypeLength: 1
- name: FUNCTION_SUM_08
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 64
  dataTypeLength: 1
- name: GROUP_BY_COLUMNS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: GROUP_BY_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 11
  dataTypeLength:
- name: INTERACTIVE_REPORT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 15
  dataTypeLength:
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 5
  dataTypeLength:
- name: REPORT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 8
  dataTypeLength:
- name: REPORT_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 255
- name: SORT_COLUMN_01
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 65
  dataTypeLength: 255
- name: SORT_COLUMN_02
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 67
  dataTypeLength: 255
- name: SORT_COLUMN_03
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 69
  dataTypeLength: 255
- name: SORT_COLUMN_04
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 71
  dataTypeLength: 255
- name: SORT_COLUMN_05
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 73
  dataTypeLength: 255
- name: SORT_COLUMN_06
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 75
  dataTypeLength: 255
- name: SORT_DIRECTION_01
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 66
  dataTypeLength: 255
- name: SORT_DIRECTION_02
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 68
  dataTypeLength: 255
- name: SORT_DIRECTION_03
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 70
  dataTypeLength: 255
- name: SORT_DIRECTION_04
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 72
  dataTypeLength: 255
- name: SORT_DIRECTION_05
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 74
  dataTypeLength: 255
- name: SORT_DIRECTION_06
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 76
  dataTypeLength: 255
- name: WEBSHEET_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 7
  dataTypeLength:
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEETS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEET_GROUP_BY
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEET_RPTS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    r.page_id page_id,
    r.worksheet_id interactive_report_id,
    g.websheet_id websheet_id,
    r.id report_id,
    r.application_user application_user,
    r.name report_name,
    g.id group_by_id,
    group_by_columns,
    g.created_on,
    g.created_by,
    g.updated_on last_updated_on,
    g.updated_by last_updated_by,
    g.function_01,
    g.function_column_01,
    g.function_db_column_name_01,
    g.function_label_01,
    g.function_format_mask_01,
    g.function_sum_01,
    g.function_02,
    g.function_column_02,
    g.function_db_column_name_02,
    g.function_label_02,
    g.function_format_mask_02,
    g.function_sum_02,
    g.function_03,
    g.function_column_03,
    g.function_db_column_name_03,
    g.function_label_03,
    g.function_format_mask_03,
    g.function_sum_03,
    g.function_04,
    g.function_column_04,
    g.function_db_column_name_04,
    g.function_label_04,
    g.function_format_mask_04,
    g.function_sum_04,
    g.function_05,
    g.function_column_05,
    g.function_db_column_name_05,
    g.function_label_05,
    g.function_format_mask_05,
    g.function_sum_05,
    g.function_06,
    g.function_column_06,
    g.function_db_column_name_06,
    g.function_label_06,
    g.function_format_mask_06,
    g.function_sum_06,
    g.function_07,
    g.function_column_07,
    g.function_db_column_name_07,
    g.function_label_07,
    g.function_format_mask_07,
    g.function_sum_07,
    g.function_08,
    g.function_column_08,
    g.function_db_column_name_08,
    g.function_label_08,
    g.function_format_mask_08,
    g.function_sum_08,
    --
    g.sort_column_01,
    g.sort_direction_01,
    g.sort_column_02,
    g.sort_direction_02,
    g.sort_column_03,
    g.sort_direction_03,
    g.sort_column_04,
    g.sort_direction_04,
    g.sort_column_05,
    g.sort_direction_05,
    g.sort_column_06,
    g.sort_direction_06 --
  from
    wwv_flow_worksheet_group_by g,
    wwv_flow_worksheet_rpts r,
    wwv_flow_worksheets ws,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = r.security_group_id
    and f.id = ws.flow_id
    and ws.id = r.worksheet_id
    and r.id = g.report_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
