schema: APEX_050000
name: APEX_APPLICATION_SUPP_OBJECTS
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: BUILD_OPTIONS
  dataType: NUMBER
  nullable: true
  ordinalPosition: 5
  dataTypeLength:
- name: BUILD_OPTIONS_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 4000
- name: CONFIGURATION_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 4000
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 26
  dataTypeLength:
- name: DEINSTALLATION_SCRIPT
  dataType: CLOB
  nullable: true
  ordinalPosition: 22
  dataTypeLength:
- name: DEINSTALL_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: DEINSTALL_SUCCESS_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: INCLUDE_IN_APPLICATION_EXPORT
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 3
- name: INSTALLATION_FAILURE_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: INSTALLATION_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: INSTALLATION_SCRIPTS
  dataType: NUMBER
  nullable: true
  ordinalPosition: 13
  dataTypeLength:
- name: INSTALLATION_SUCCESS_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 24
  dataTypeLength:
- name: LICENSE_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 4000
- name: REQUIRED_FREE_KB
  dataType: NUMBER
  nullable: true
  ordinalPosition: 29
  dataTypeLength:
- name: REQUIRED_NAMES_AVAILABLE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 4000
- name: REQUIRED_SYSTEM_PRIVILEGES
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: SUPPORTING_OBJECT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 32
  dataTypeLength:
- name: UPGRADE_CONFIRM_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: UPGRADE_FAILURE_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: UPGRADE_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: UPGRADE_SCRIPTS
  dataType: NUMBER
  nullable: true
  ordinalPosition: 19
  dataTypeLength:
- name: UPGRADE_SUCCESS_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: UPGRADE_WHEN_QUERY
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: VALIDATION_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 4000
- name: WELCOME_MESSAGE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 4000
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_INSTALL
- schema: APEX_050000
  name: WWV_FLOW_INSTALL_BUILD_OPT
- schema: APEX_050000
  name: WWV_FLOW_INSTALL_SCRIPTS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    (
      select
        count(*)
      from
        wwv_flow_install_build_opt
      where
        install_id = i.id
    ) build_options,
    --
    decode(
      i.INCLUDE_IN_EXPORT_YN,
      'Y',
      'Yes',
      'N',
      'No',
      i.INCLUDE_IN_EXPORT_YN
    ) include_in_application_export,
    i.WELCOME_MESSAGE,
    i.LICENSE_MESSAGE,
    i.VALIDATION_MESSAGE,
    --
    i.INSTALL_MESSAGE installation_message,
    i.INSTALL_SUCCESS_MESSAGE installation_success_message,
    i.INSTALL_FAILURE_MESSAGE installation_failure_message,
    (
      select
        count(*)
      from
        wwv_flow_install_scripts
      where
        i.id = install_id
        and nvl(script_type, 'INSTALL') = 'INSTALL'
    ) installation_scripts,
    --
    i.get_version_sql_query upgrade_when_query,
    i.upgrade_message upgrade_message,
    i.upgrade_confirm_message upgrade_confirm_message,
    i.upgrade_success_message upgrade_success_message,
    i.upgrade_failure_message upgrade_failure_message,
    (
      select
        count(*)
      from
        wwv_flow_install_scripts
      where
        i.id = install_id
        and nvl(script_type, 'INSTALL') = 'UPGRADE'
    ) upgrade_scripts,
    --
    --
    i.DEINSTALL_MESSAGE,
    i.DEINSTALL_SUCCESS_MESSAGE,
    --i.DEINSTALL_FAILURE_MESSAGE      ,
    i.DEINSTALL_SCRIPT deinstallation_script,
    --
    --i.PROMPT_SUBSTITUTION_01_YN      ,
    --i.PROMPT_SUBSTITUTION_02_YN      ,
    --i.PROMPT_SUBSTITUTION_03_YN      ,
    --i.PROMPT_SUBSTITUTION_04_YN      ,
    --i.PROMPT_SUBSTITUTION_05_YN      ,
    --i.PROMPT_SUBSTITUTION_06_YN      ,
    --i.PROMPT_SUBSTITUTION_07_YN      ,
    --i.PROMPT_SUBSTITUTION_08_YN      ,
    --i.PROMPT_SUBSTITUTION_09_YN      ,
    --i.PROMPT_SUBSTITUTION_10_YN      ,
    --i.PROMPT_SUBSTITUTION_11_YN      ,
    --i.PROMPT_SUBSTITUTION_12_YN      ,
    --i.PROMPT_SUBSTITUTION_13_YN      ,
    --i.PROMPT_SUBSTITUTION_14_YN      ,
    --i.PROMPT_SUBSTITUTION_15_YN      ,
    --i.PROMPT_SUBSTITUTION_16_YN      ,
    --i.PROMPT_SUBSTITUTION_17_YN      ,
    --i.PROMPT_SUBSTITUTION_18_YN      ,
    --i.PROMPT_SUBSTITUTION_19_YN      ,
    --i.PROMPT_SUBSTITUTION_20_YN      ,
    ----
    --i.PROMPT_IF_MULT_AUTH_YN         ,
    --i.PROMPT_BUILD_OPTIONS           ,
    --
    i.LAST_UPDATED_BY,
    i.LAST_UPDATED_ON,
    i.CREATED_BY,
    i.CREATED_ON,
    --
    --i.INSTALL_PROMPT_01              ,
    --i.INSTALL_PROMPT_02              ,
    --i.INSTALL_PROMPT_03              ,
    --i.INSTALL_PROMPT_04              ,
    --i.INSTALL_PROMPT_05              ,
    --i.INSTALL_PROMPT_06              ,
    --i.INSTALL_PROMPT_07              ,
    --i.INSTALL_PROMPT_08              ,
    --i.INSTALL_PROMPT_09              ,
    --i.INSTALL_PROMPT_10              ,
    --i.INSTALL_PROMPT_11              ,
    --i.INSTALL_PROMPT_12              ,
    --i.INSTALL_PROMPT_13              ,
    --i.INSTALL_PROMPT_14              ,
    --i.INSTALL_PROMPT_15              ,
    --i.INSTALL_PROMPT_16              ,
    --i.INSTALL_PROMPT_17              ,
    --i.INSTALL_PROMPT_18              ,
    --i.INSTALL_PROMPT_19              ,
    --i.INSTALL_PROMPT_20              ,
    i.CONFIGURATION_MESSAGE,
    -- obsolete i.TRIGGER_INSTALL_WHEN_COND      ,
    -- obsolete i.TRIGGER_INSTALL_WHEN_EXP1      ,
    -- obsolete i.TRIGGER_INSTALL_WHEN_EXP2      ,
    -- obsolete i.TRIGGER_FAILURE_MESSAGE        ,
    i.BUILD_OPTIONS_MESSAGE,
    i.REQUIRED_FREE_KB,
    i.REQUIRED_SYS_PRIVS required_system_privileges,
    i.REQUIRED_NAMES_AVAILABLE,
    --
    i.id supporting_object_id
  from
    wwv_flow_install i,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and f.id = i.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
