schema: APEX_050000
name: APEX_APPLICATION_PAGE_FLASH5_S
updatedAllowed: true
insertAllowed: true
columns:
- name: ACTION_LINK
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: ACTION_LINK_CHECKSUM_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 255
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: AUTHORIZATION_SCHEME
  dataType: VARCHAR2
  textMaxLength: 259
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 259
- name: AUTHORIZATION_SCHEME_ID
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 255
- name: BUILD_OPTION
  dataType: VARCHAR2
  textMaxLength: 261
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 261
- name: BUILD_OPTION_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 17
  dataTypeLength:
- name: CHART_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 9
  dataTypeLength:
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION1
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 4000
- name: CONDITION_EXPRESSION2
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: CONDITION_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 255
- name: CONDITION_TYPE_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 255
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 31
  dataTypeLength:
- name: PAGE_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 5
  dataTypeLength:
- name: PAGE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 255
- name: REGION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 7
  dataTypeLength:
- name: REGION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: SERIES_AJAX_ITEMS_TO_SUBMIT
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 255
- name: SERIES_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 10
  dataTypeLength:
- name: SERIES_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 12
  dataTypeLength: 255
- name: SERIES_QUERY
  dataType: CLOB
  nullable: false
  ordinalPosition: 19
  dataTypeLength:
- name: SERIES_QUERY_NO_DATA_FOUND
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 4000
- name: SERIES_QUERY_PARSE_OPT
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 255
- name: SERIES_QUERY_ROW_COUNT_MAX
  dataType: NUMBER
  nullable: true
  ordinalPosition: 23
  dataTypeLength:
- name: SERIES_QUERY_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 18
  dataTypeLength: 255
- name: SERIES_SEQ
  dataType: NUMBER
  nullable: false
  ordinalPosition: 11
  dataTypeLength:
- name: SERIES_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 255
- name: SHOW_ACTION_LINK
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 1
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: APEX_STANDARD_CONDITIONS
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_FLASH_CHART5_SERIES
- schema: APEX_050000
  name: WWV_FLOW_FLASH_CHARTS_5
- schema: APEX_050000
  name: WWV_FLOW_PAGE_PLUGS
- schema: APEX_050000
  name: WWV_FLOW_PATCHES
- schema: APEX_050000
  name: WWV_FLOW_SECURITY_SCHEMES
- schema: APEX_050000
  name: WWV_FLOW_STEPS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    c .page_id page_id,
    (
      select
        name
      from
        wwv_flow_steps
      where
        id = c .page_id
        and flow_id = c .flow_id
    ) page_name,
    c .region_id region_id,
    (
      select
        plug_name
      from
        wwv_flow_page_plugs
      where
        id = c .region_id
        and flow_id = c .flow_id
    ) region_name,
    --
    cs.chart_id chart_id,
    cs.id series_id,
    cs.series_seq series_seq,
    cs.series_name series_name,
    cs.series_type series_type,
    decode(substr(cs.series_required_role, 1, 1), '!', 'Not ') || nvl(
      (
        select
          name
        from
          wwv_flow_security_schemes
        where
          to_char(id) = ltrim(cs.series_required_role, '!')
          and flow_id = f.id
      ),
      cs.series_required_role
    ) authorization_scheme,
    cs.series_required_role authorization_scheme_id,
    (
      select
        case
          when cs.required_patch > 0 then PATCH_NAME
          else '{Not ' || PATCH_NAME || '}'
        end PATCH_NAME
      from
        wwv_flow_patches
      where
        id = abs(cs.REQUIRED_PATCH)
    ) build_option,
    cs.required_patch build_option_id,
    cs.series_query_type series_query_type,
    cs.series_query series_query,
    cs.series_ajax_items_to_submit series_ajax_items_to_submit,
    cs.series_query_parse_opt series_query_parse_opt,
    cs.series_query_no_data_found series_query_no_data_found,
    cs.series_query_row_count_max series_query_row_count_max,
    cs.action_link action_link,
    cs.show_action_link show_action_link,
    cs.action_link_checksum_type action_link_checksum_type,
    nvl(
      (
        select
          r
        from
          apex_standard_conditions
        where
          d = cs.DISPLAY_WHEN_COND_TYPE
      ),
      cs.DISPLAY_WHEN_COND_TYPE
    ) condition_type,
    cs.display_when_cond_type condition_type_code,
    cs.DISPLAY_WHEN_CONDITION condition_expression1,
    cs.DISPLAY_WHEN_CONDITION2 condition_expression2,
    cs.updated_on last_updated_on,
    cs.updated_by last_updated_by,
    --
    cs.series_name || ' seq=' || lpad(cs.series_seq, 5, '00000') || ' q=' || sys.dbms_lob.substr(cs.series_query, 20, 1) || '.' || sys.dbms_lob.getlength(cs.series_query) || ' max=' || cs.series_query_row_count_max || ' nd_msg=' || substr(cs.series_query_no_data_found, 1, 20) || length(cs.series_query_no_data_found) || ' link=' || substr(cs.action_link, 1, 20) || ':' || cs.show_action_link component_signature
  from
    wwv_flow_flash_chart5_series cs,
    wwv_flow_flash_charts_5 c,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = cs.flow_id
    and c .id = cs.chart_id
    and c .flow_id = cs.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
