schema: APEX_050000
name: APEX_APPLICATION_AUTH
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: ATTRIBUTE_01
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 4000
- name: ATTRIBUTE_02
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 4000
- name: ATTRIBUTE_03
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 4000
- name: ATTRIBUTE_04
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 24
  dataTypeLength: 4000
- name: ATTRIBUTE_05
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 4000
- name: ATTRIBUTE_06
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 4000
- name: ATTRIBUTE_07
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 4000
- name: ATTRIBUTE_08
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 4000
- name: ATTRIBUTE_09
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 29
  dataTypeLength: 4000
- name: ATTRIBUTE_10
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 4000
- name: ATTRIBUTE_11
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 4000
- name: ATTRIBUTE_12
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 32
  dataTypeLength: 4000
- name: ATTRIBUTE_13
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 4000
- name: ATTRIBUTE_14
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 34
  dataTypeLength: 4000
- name: ATTRIBUTE_15
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 35
  dataTypeLength: 4000
- name: AUTHENTICATION_SCHEME_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 41
  dataTypeLength:
- name: AUTHENTICATION_SCHEME_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 9
  dataTypeLength: 255
- name: COMMENTS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 40
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 47
  dataTypeLength: 4000
- name: COOKIE_DOMAIN
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 4000
- name: COOKIE_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: COOKIE_PATH
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: COOKIE_SECURE
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 3
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 45
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 46
  dataTypeLength:
- name: HELP_TEXT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 39
  dataTypeLength: 4000
- name: INVALID_SESSION_TYPE
  dataType: VARCHAR2
  textMaxLength: 13
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 13
- name: INVALID_SESSION_URL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 11
  dataTypeLength: 4000
- name: IS_CURRENT_AUTHENTICATION
  dataType: CHAR
  textMaxLength: 1
  nullable: true
  ordinalPosition: 5
  dataTypeLength: 1
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 6
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 43
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 44
  dataTypeLength:
- name: LOGOUT_URL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 4000
- name: PLSQL_CODE
  dataType: CLOB
  nullable: true
  ordinalPosition: 12
  dataTypeLength:
- name: POST_AUTHENTICATION_PROCESS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 255
- name: PRE_AUTHENTICATION_PROCESS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 255
- name: RAS_DYNAMIC_ROLES
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 37
  dataTypeLength: 4000
- name: RAS_MODE
  dataType: VARCHAR2
  textMaxLength: 14
  nullable: true
  ordinalPosition: 36
  dataTypeLength: 14
- name: RAS_NAMESPACES
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 38
  dataTypeLength: 4000
- name: REFERENCED_SCHEMA_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 42
  dataTypeLength:
- name: SCHEME_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 255
- name: SCHEME_TYPE_CODE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 8
  dataTypeLength: 255
- name: VERIFICATION_FUNCTION
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_AUTHENTICATIONS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PLUGINS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    --
    case
      when f.authentication_id = a .id then 'Y'
      else 'N'
    end is_current_authentication,
    decode(a .reference_id, null, 'No', 'Yes') is_subscribed,
    case
      substr(a .scheme_type, 1, 7)
      when 'NATIVE_' then (
        select
          display_name
        from
          wwv_flow_plugins
        where
          flow_id = 4411
          and plugin_type = 'AUTHENTICATION TYPE'
          and name = substr(a .scheme_type, 8)
      )
      when 'PLUGIN_' then (
        select
          display_name
        from
          wwv_flow_plugins
        where
          flow_id = a .flow_id
          and plugin_type = 'AUTHENTICATION TYPE'
          and name = substr(a .scheme_type, 8)
      )
      else a .scheme_type
    end scheme_type,
    a .scheme_type scheme_type_code,
    a .name authentication_scheme_name,
    --
    a .invalid_session_type invalid_session_type,
    a .invalid_session_url invalid_session_url,
    --
    a .plsql_code plsql_code,
    a .verification_function verification_function,
    a .pre_auth_process pre_authentication_process,
    a .post_auth_process post_authentication_process,
    --
    a .cookie_name cookie_name,
    a .cookie_path cookie_path,
    a .cookie_domain cookie_domain,
    decode(a .use_secure_cookie_yn, 'Y', 'Yes', 'N', 'No', 'No') cookie_secure,
    --
    a .logout_url logout_url,
    --
    a .attribute_01 attribute_01,
    a .attribute_02 attribute_02,
    a .attribute_03 attribute_03,
    a .attribute_04 attribute_04,
    a .attribute_05 attribute_05,
    a .attribute_06 attribute_06,
    a .attribute_07 attribute_07,
    a .attribute_08 attribute_08,
    a .attribute_09 attribute_09,
    a .attribute_10 attribute_10,
    a .attribute_11 attribute_11,
    a .attribute_12 attribute_12,
    a .attribute_13 attribute_13,
    a .attribute_14 attribute_14,
    a .attribute_15 attribute_15,
    --
    case
      a .ras_mode
      when 0 then 'Disabled'
      when 1 then 'External Users'
      when 2 then 'Internal Users'
    end ras_mode,
    a .ras_dynamic_roles ras_dynamic_roles,
    a .ras_namespaces ras_namespaces,
    --
    a .help_text help_text,
    a .comments comments,
    --
    a .id authentication_scheme_id,
    a .reference_id referenced_schema_id,
    --
    a .last_updated_by last_updated_by,
    a .last_updated_on last_updated_on,
    a .created_by created_by,
    a .created_on created_on,
    --
    a .name || ' ' || a .scheme_type || ' ' || decode(a .reference_id, null, 'No', 'Yes') || substr(a .invalid_session_type, 1, 20) || length(a .invalid_session_type) || '.' || substr(a .invalid_session_url, 1, 20) || length(a .invalid_session_url) || '.' || sys.dbms_lob.substr(a .pre_auth_process, 20, 1) || sys.dbms_lob.getlength(a .pre_auth_process) || '.' || sys.dbms_lob.substr(a .post_auth_process, 20, 1) || sys.dbms_lob.getlength(a .post_auth_process) || '.' || substr(a .cookie_name, 1, 20) || length(a .cookie_name) || '.' || substr(a .cookie_path, 1, 20) || length(a .cookie_path) || '.' || substr(a .cookie_domain, 1, 20) || length(a .cookie_domain) || '.' || substr(a .use_secure_cookie_yn, 1, 1) || length(a .use_secure_cookie_yn) || '.' || substr(a .attribute_01, 1, 20) || length(a .attribute_01) || '.' || substr(a .attribute_02, 1, 20) || length(a .attribute_02) || '.' || substr(a .attribute_03, 1, 20) || length(a .attribute_03) || '.' || substr(a .attribute_04, 1, 20) || length(a .attribute_04) || '.' || substr(a .attribute_05, 1, 20) || length(a .attribute_05) || '.' || substr(a .attribute_06, 1, 20) || length(a .attribute_06) || '.' || substr(a .attribute_07, 1, 20) || length(a .attribute_07) || '.' || substr(a .attribute_08, 1, 20) || length(a .attribute_08) || '.' || substr(a .attribute_09, 1, 20) || length(a .attribute_09) || '.' || substr(a .attribute_10, 1, 20) || length(a .attribute_10) || '.' || substr(a .attribute_11, 1, 20) || length(a .attribute_11) || '.' || substr(a .attribute_12, 1, 20) || length(a .attribute_12) || '.' || substr(a .attribute_13, 1, 20) || length(a .attribute_13) || '.' || substr(a .attribute_14, 1, 20) || length(a .attribute_14) || '.' || substr(a .attribute_15, 1, 20) || length(a .attribute_15) component_signature
  from
    wwv_flow_authentications a,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.provisioning_company_id
    and s.security_group_id = w.provisioning_company_id
    and s.schema = f.owner
    and f.id = a .flow_id
    and (
      d.sgid != 0
      or nvl(f.build_status, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.provisioning_company_id != 0
