schema: APEX_050000
name: APEX_APPLICATION_PAGE_IR_COMP
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: APPLICATION_USER
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: COMPUTATION_COLUMN_ALIAS
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: false
  ordinalPosition: 11
  dataTypeLength: 30
- name: COMPUTATION_COLUMN_IDENTIFIER
  dataType: VARCHAR2
  textMaxLength: 10
  nullable: false
  ordinalPosition: 12
  dataTypeLength: 10
- name: COMPUTATION_COLUMN_TYPE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 255
- name: COMPUTATION_EXPRESSION
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 4000
- name: COMPUTATION_FORMAT_MASK
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 255
- name: COMPUTATION_FORM_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: false
  ordinalPosition: 17
  dataTypeLength: 4000
- name: COMPUTATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 10
  dataTypeLength:
- name: COMPUTATION_REPORT_LABEL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: false
  ordinalPosition: 16
  dataTypeLength: 4000
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 18
  dataTypeLength:
- name: INTERACTIVE_REPORT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 21
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 20
  dataTypeLength:
- name: PAGE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 5
  dataTypeLength:
- name: REPORT_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 7
  dataTypeLength:
- name: REPORT_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 255
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEETS
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEET_COMPUTATION
- schema: APEX_050000
  name: WWV_FLOW_WORKSHEET_RPTS
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.id application_id,
    f.name application_name,
    r.page_id page_id,
    r.worksheet_id interactive_report_id,
    r.id report_id,
    r.application_user application_user,
    r.name report_name,
    c .id computation_id,
    c .db_column_name computation_column_alias,
    c .column_identifier computation_column_identifier,
    c .computation_expr computation_expression,
    c .format_mask computation_format_mask,
    c .column_type computation_column_type,
    c .report_label computation_report_label,
    c .column_label computation_form_label,
    -- audit
    --
    c .created_on,
    c .created_by,
    c .updated_on last_updated_on,
    c .updated_by last_updated_by --
  from
    wwv_flow_worksheet_computation c,
    wwv_flow_worksheet_rpts r,
    wwv_flow_worksheets ws,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.security_group_id = r.security_group_id
    and f.id = ws.flow_id
    and ws.id = r.worksheet_id
    and r.id = c .report_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
