schema: APEX_050000
name: APEX_APPLICATION_TEMP_REGION
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 3
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 4
  dataTypeLength: 255
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 31
  dataTypeLength: 4000
- name: COMPONENT_SIGNATURE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 33
  dataTypeLength: 4000
- name: DEFAULT_BUTTON_POSITION
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 25
  dataTypeLength: 30
- name: DEFAULT_BUTTON_TEMPLATE_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 24
  dataTypeLength:
- name: DEFAULT_FIELD_ALIGNMENT
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 23
  dataTypeLength: 30
- name: DEFAULT_FIELD_TEMPLATE_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 20
  dataTypeLength:
- name: DEFAULT_LABEL_ALIGNMENT
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: true
  ordinalPosition: 22
  dataTypeLength: 30
- name: DEFAULT_REQ_FIELD_TEMPLATE_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 21
  dataTypeLength:
- name: DEFAULT_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 255
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 26
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 28
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 29
  dataTypeLength:
- name: LAYOUT
  dataType: VARCHAR2
  textMaxLength: 10
  nullable: false
  ordinalPosition: 10
  dataTypeLength: 10
- name: PLUG_FONT_SIZE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 19
  dataTypeLength: 255
- name: PLUG_HEADING_BGCOLOR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 255
- name: PLUG_TABLE_BGCOLOR
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 255
- name: PRESET_TEMPLATE_OPTIONS
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 255
- name: REGION_TEMPLATE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 32
  dataTypeLength:
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 297
  nullable: true
  ordinalPosition: 27
  dataTypeLength: 297
- name: SUB_REGION_HEADER_ENTRY_TEMPL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 4000
- name: SUB_REGION_HEADER_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 4000
- name: SUB_REGION_TEMPLATE
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 16
  dataTypeLength: 4000
- name: TEMPLATE
  dataType: CLOB
  nullable: false
  ordinalPosition: 11
  dataTypeLength:
- name: TEMPLATE2
  dataType: CLOB
  nullable: true
  ordinalPosition: 12
  dataTypeLength:
- name: TEMPLATE3
  dataType: CLOB
  nullable: true
  ordinalPosition: 13
  dataTypeLength:
- name: TEMPLATE_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: THEME_CLASS
  dataType: VARCHAR2
  textMaxLength: 40
  nullable: true
  ordinalPosition: 7
  dataTypeLength: 40
- name: THEME_NUMBER
  dataType: NUMBER
  nullable: true
  ordinalPosition: 6
  dataTypeLength:
- name: TRANSLATABLE
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 30
  dataTypeLength: 3
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 1
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 2
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOWS
- schema: APEX_050000
  name: WWV_FLOW_COMPANIES
- schema: APEX_050000
  name: WWV_FLOW_COMPANY_SCHEMAS
- schema: APEX_050000
  name: WWV_FLOW_PAGE_PLUG_TEMPLATES
- schema: SYS
  name: DUAL
viewDefinition: |-
  select
    w.short_name workspace,
    w.display_name workspace_display_name,
    f.ID application_id,
    f.NAME application_name,
    --
    t.PAGE_PLUG_TEMPLATE_NAME template_name,
    t.THEME_ID theme_number,
    --
    decode(
      t.THEME_CLASS_ID,
      'RETURN_VALUE',
      'DISPLAY_VALUE',
      '1',
      'Hide and Show Region',
      '2',
      'Sidebar Region',
      '3',
      'Sidebar Region, Alternative 1',
      '4',
      'Button Region with Title',
      '5',
      'Navigation Region',
      '6',
      'Breadcrumb Region',
      '7',
      'Borderless Region',
      '8',
      'Form Region',
      '9',
      'Reports Region',
      '10',
      'Reports Region, Alternative 1',
      '11',
      'Region without Title',
      '12',
      'Wizard Region',
      '13',
      'Reports Region 100% Width',
      '16',
      'Navigation Region, Alternative 1',
      '17',
      'Button Region without Title',
      '18',
      'Bracketed Region',
      '19',
      'Region without Buttons and Title',
      '20',
      'Wizard Region with Icon',
      '21',
      'Custom 1',
      '22',
      'Custom 2',
      '23',
      'Custom 3',
      '24',
      'Custom 4',
      '25',
      'Custom 5',
      '26',
      'Custom 6',
      '27',
      'Custom 7',
      '28',
      'Custom 8',
      '29',
      'List Region with Icon',
      '30',
      'Chart Region',
      t.theme_class_id
    ) theme_class,
    t.default_template_options default_template_options,
    t.preset_template_options preset_template_options,
    --
    t.layout,
    t.template,
    t.template2,
    t.template3,
    t.sub_plug_header_template as sub_region_header_template,
    t.sub_plug_header_entry_template as sub_region_header_entry_templ,
    t.sub_plug_template as sub_region_template,
    t.plug_table_bgcolor,
    t.plug_heading_bgcolor,
    t.plug_font_size,
    t.default_field_template_id,
    t.default_req_field_template_id,
    t.default_label_alignment,
    t.default_field_alignment,
    t.default_button_template_id,
    t.default_button_position,
    --
    decode(t.REFERENCE_ID, null, 'No', 'Yes') is_subscribed,
    (
      select
        flow_id || '. ' || name
      from
        WWV_FLOW_PAGE_PLUG_TEMPLATES
      where
        id = t.REFERENCE_ID
    ) subscribed_from,
    --
    t.LAST_UPDATED_BY last_updated_by,
    t.LAST_UPDATED_ON last_updated_on,
    decode(
      t.TRANSLATE_THIS_TEMPLATE,
      'N',
      'No',
      'Y',
      'Yes',
      'Yes'
    ) translatable,
    t.TEMPLATE_COMMENT component_comment,
    t.id region_template_id,
    --
    t.PAGE_PLUG_TEMPLATE_NAME || ' t=' || t.THEME_ID || ' c=' || THEME_CLASS_ID || ' 1=' || sys.dbms_lob.substr(t.TEMPLATE, 40, 1) || '.' || sys.dbms_lob.getlength(t.TEMPLATE) || ' 2=' || sys.dbms_lob.substr(t.TEMPLATE2, 40, 1) || '.' || sys.dbms_lob.getlength(t.TEMPLATE2) || ' 3=' || sys.dbms_lob.substr(t.TEMPLATE3, 40, 1) || '.' || sys.dbms_lob.getlength(t.TEMPLATE3) || ' b=' || substr(t.PLUG_TABLE_BGCOLOR, 1, 20) || ' b=' || substr(t.PLUG_HEADING_BGCOLOR, 1, 20) || ' f=' || substr(t.PLUG_FONT_SIZE, 1, 20) || ' t=' || TRANSLATE_THIS_TEMPLATE || ' r=' || decode(t.REFERENCE_ID, null, 'N', 'Y') component_signature
  from
    WWV_FLOW_PAGE_PLUG_TEMPLATES t,
    wwv_flows f,
    wwv_flow_companies w,
    wwv_flow_company_schemas s,
    (
      select
        nvl(v('FLOW_SECURITY_GROUP_ID'), 0) sgid,
        (
          select
            sys_context('USERENV', 'CURRENT_USER')
          from
            sys.dual
        ) cu
      from
        sys.dual
    ) d
  where
    (
      s.schema = cu
      or (
        select
          wwv_flow_security.has_apex_administrator_role_yn(cu)
        from
          sys.dual
      ) = 'Y'
      or d.sgid = w.PROVISIONING_COMPANY_ID
    )
    and f.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.security_group_id = w.PROVISIONING_COMPANY_ID
    and s.schema = f.owner
    and f.id = t.flow_id
    and (
      d.sgid != 0
      or nvl(f.BUILD_STATUS, 'x') != 'RUN_AND_HIDDEN'
    )
    and w.PROVISIONING_COMPANY_ID != 0
