schema: APEX_050000
name: APEX_APPLICATION_THEME_STYLES
updatedAllowed: true
insertAllowed: true
columns:
- name: APPLICATION_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 4
  dataTypeLength:
- name: APPLICATION_NAME
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 5
  dataTypeLength: 255
- name: COMPONENT_COMMENT
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 17
  dataTypeLength: 4000
- name: CREATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 18
  dataTypeLength: 255
- name: CREATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 19
  dataTypeLength:
- name: CSS_FILE_URLS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 8
  dataTypeLength: 4000
- name: IS_CURRENT
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 9
  dataTypeLength: 3
- name: IS_SUBSCRIBED
  dataType: VARCHAR2
  textMaxLength: 3
  nullable: true
  ordinalPosition: 14
  dataTypeLength: 3
- name: LAST_UPDATED_BY
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: true
  ordinalPosition: 20
  dataTypeLength: 255
- name: LAST_UPDATED_ON
  dataType: DATE
  nullable: true
  ordinalPosition: 21
  dataTypeLength:
- name: NAME
  dataType: VARCHAR2
  textMaxLength: 30
  nullable: false
  ordinalPosition: 7
  dataTypeLength: 30
- name: SUBSCRIBED_FROM
  dataType: VARCHAR2
  textMaxLength: 72
  nullable: true
  ordinalPosition: 15
  dataTypeLength: 72
- name: SUBSCRIBED_FROM_ID
  dataType: NUMBER
  nullable: true
  ordinalPosition: 16
  dataTypeLength:
- name: THEME_NUMBER
  dataType: NUMBER
  nullable: false
  ordinalPosition: 6
  dataTypeLength:
- name: THEME_ROLLER_CONFIG
  dataType: CLOB
  nullable: true
  ordinalPosition: 11
  dataTypeLength:
- name: THEME_ROLLER_INPUT_FILE_URLS
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 10
  dataTypeLength: 4000
- name: THEME_ROLLER_OUTPUT_FILE_URL
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 12
  dataTypeLength: 4000
- name: THEME_ROLLER_READ_ONLY
  dataType: VARCHAR2
  textMaxLength: 1
  nullable: true
  ordinalPosition: 13
  dataTypeLength: 1
- name: THEME_STYLE_ID
  dataType: NUMBER
  nullable: false
  ordinalPosition: 1
  dataTypeLength:
- name: WORKSPACE
  dataType: VARCHAR2
  textMaxLength: 255
  nullable: false
  ordinalPosition: 2
  dataTypeLength: 255
- name: WORKSPACE_DISPLAY_NAME
  dataType: VARCHAR2
  textMaxLength: 4000
  nullable: true
  ordinalPosition: 3
  dataTypeLength: 4000
referencedTables:
- schema: APEX_050000
  name: WWV_FLOW_AUTHORIZED
- schema: APEX_050000
  name: WWV_FLOW_THEME_STYLES
viewDefinition: |-
  select
    s.id as theme_style_id,
    f.workspace,
    f.workspace_display_name,
    f.application_id,
    f.application_name,
    s.theme_id as theme_number,
    s.name,
    s.css_file_urls,
    case
      s.is_current
      when 'Y' then 'Yes'
      else 'No'
    end as is_current,
    s.theme_roller_input_file_urls,
    s.theme_roller_config,
    s.theme_roller_output_file_url,
    s.theme_roller_read_only,
    nvl2(s.reference_id, 'Yes', 'No') as is_subscribed,
    (
      select
        s2.flow_id || '. ' || s2.name
      from
        wwv_flow_theme_styles s2
      where
        s2.id = s.reference_id
    ) as subscribed_from,
    s.reference_id as subscribed_from_id,
    s.component_comment,
    s.created_by,
    s.created_on,
    s.last_updated_by,
    s.last_updated_on
  from
    wwv_flow_authorized f,
    wwv_flow_theme_styles s
  where
    s.flow_id = f.application_id
