schema: ORDSYS
name: SI_VALUES
updatedAllowed: true
insertAllowed: true
columns: []
referencedTables: []
viewDefinition: |-
  select
    SI_value,
    SI_supported_Value
  from
    ordsys.SI_Values_tab
