targetObjectSchema: XDB
targetObjectName: XDB$RESCONFIG
targetObjectType: TABLE
name: XDB$RESCONFIG$xd
eventTiming: AFTER EACH ROW
event: UPDATE OR DELETE
eventActionBody: |-
  BEGIN
    IF (deleting) THEN xdb.xdb_pitrig_pkg.pitrig_del(
      'XDB',
      'XDB$RESCONFIG',
      :old.sys_nc_oid$,
      'FD9ACFECC11F48A9E043B6A9E80AFB6F'
    );
  END IF;
  IF (updating) THEN xdb.xdb_pitrig_pkg.pitrig_upd(
    'XDB',
    'XDB$RESCONFIG',
    :old.sys_nc_oid$,
    'FD9ACFECC11F48A9E043B6A9E80AFB6F',
    user
  );
  END IF;
  END;
executionOrder: 1
